### ISSUE TITLE
embark--strip-prefix should strip the consult-location prefix instead of the unicode characters

### ISSUE THREAD

**Issue by minad** [oantolin/embark#107]

**Comment by oantolin** [comment]
Sadly it is used from actions, so there is no `consult-location` text property available. Remember we discussed that the target finder for default completion strips properties?

I guess it could strip the `consult-location` characters if it happens to find them and otherwise strip the unicode prefix.

**Comment by minad** [comment]
Ah I see, then I would rather keep it as is!
