### ISSUE TITLE
display-line-numbers-mode reveals extra line at the top of collect buffers

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#116]
Hello Omar!  I have noticed that the following hook will reveal a new line at the top of the collect buffer which contains two tabular headings for "Candidate" and "Annotation":

```elisp
(add-hook 'embark-collect-mode-hook #'display-line-numbers-mode)
```

![Screenshot from 2021-01-17 11-19-38](https://user-images.githubusercontent.com/12828033/104836334-e76df500-58b5-11eb-9718-1b4de1e3bd59.png)

**Comment by oantolin** [comment]
Yes, collect mode is derived from tabulated list mode, and tabulated list buffers have that heading. If you click on the word "candidates", it sorts them alphabetically.

**Comment by oantolin** [comment]
I am a little surprised that display line numbers mode reveals the header line.

**Comment by protesilaos** [comment]
> I am a little surprised that display line numbers mode reveals the header line.

This is what surprised me as well, so I thought I would inform you about it.  The help for `display-line-numbers` has this at the end, though I understand why it may have no place here:

```
Lisp programs can disable display of a line number of a particular
buffer line by putting the ‘display-line-numbers-disable’ text property
or overlay property on the first visible character of that line.
```

I have not tried it yet to see what "disable display" means here: is it for the whole line, or just not count the number?

Anyhow, feel free to close this.  It was just informative in nature.

**Comment by oantolin** [comment]
That extra line you are seeing is what tabulated-list-mode calls a "fake header line". As I'm sure you know, Emacs windows can have a header line, whose format is controlled by `header-line-format`. Tabulated list mode can use that header line to display the names of columns, and let you click on them to sort the buffer; you get a header line if `tabulated-list-use-header-line` is `t`.

Now, here's the odd part. :) If `tabulated-list-use-header-line` is `nil`, then tabulated list mode still makes a fake header line, which is an actual line of text inserted into the buffer. That's the line you are seeing.

I've decided that for Embark Collect buffers I will forbid "fake header lines", so if `tabulated-list-use-header-line` is `t` you get a real Emacs window header and if it is `nil` you get nothing, no fake header. 7cd31b089615293714b2f021024b4d600ea30cd8

There was already command `embark-collect-toggle-header` to toggle between the two settings, by the way. What's new now is that I'm setting that fake header to `nil`, because of your discovery that `display-line-numbers-mode` makes it visible.

**Comment by protesilaos** [comment]
Yes, I already pulled the changes.  It works with that hook now.  Thank you!  My hope is that this does not have some unintended consequence, though I cannot think of any.

Even though you have fixed it, it still feels like an odd case.

As for the `header-line-format`, I feel this has potential to be used to, e.g., show the number of candidates.  Though I guess that might be better left to user configs.
