### ISSUE TITLE
Exiting the minibuffer

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#118]
I want to reform the minibuffer exiting behavior, but since this might be a little disruptive, I want to warn people and ask for feedback before I do it. There was been related discussion in #44.

# Current situation

- We have both `embark-act` and `embark-act-noexit`. Both can be used from the minibuffer and from outside the minibuffer, and they behave identically except that if called from the minibuffer, `embark-act` exits the minibuffer.
- When `embark-act` exits the minibuffer, it uses `top-level`, which means in particular that it exits not just the minibuffer you called it from, but if your are in a recursive minibuffer, it exits all the containing minibuffers too!
- If you use actions that pop up new windows (like `find-file-other-window`, for example) from `embark-act-noexit` in a minibuffer and later close that minibuffer with `C-g`, the windows get killed. (This is not really Embark-specific: try enabling recursive minibuffers and opening a file from within `C-h f`, and then canceling the `C-h f` with `C-g`.) 
- `embark-collect-snapshot` does not exit the minibuffer. It replaced `embark-occur` which did exit the minibuffer. I find myself missing the old behavior so I always call `embark-collect-snapshot` from `embark-act`.

# Proposed changes

- Have only one command, `embark-act`. This command on its own will not exit the minibuffer. You can of course exit afterwards with `C-g`.
- The disappearing window problem is annoying, so I'll add an `embark-exit` command that you can bind to `C-g` which exits one level of minibuffer, keeping any windows you opened from it.
- For people who mostly use the current `embark-act` it will be annoying to have to exit the minibuffer manually, so I'll recommend they use `(setq 'embark-post-action-hook 'embark-exit)`. This could even be the default.
- Change `embark-collect-snapshot` to always exit the minibuffer, like the old `embark-occur` command did. (This change was also requested by @clemera.)

# Observations on the proposal

- It simplifies Embark a little bit, since there would be only one command to run an action. You no longer would be tempted to waste timing planning ahead to choose between `embark-act` and `embark-act-noexit`, but would just press `C-g` at the moment you want to exit. (You can already use `embark-act-noexit` exclusively and `C-g` when you need to exit, of course, this change just pushes people towards that workflow.)
- It's easy to adapt to: I believe many people use `embark-act` exclusively or `embark-act-noexit` exclusively. For those people using the new `embark-act` (with `embark-exit` as a post action hook for the exiters) will be an identical experience. People (like me) who use both `embark-act` and `embark-act-noexit` will save a key binding and probably will have no trouble getting used to `C-g`.
- It solves the annoying disappearing window problem. Currently, to get around it what I do is to use only one window-spawning action per minibuffer session, arrange for it to be that last action I do, and run that one with `embark-act` instead of `embark-act-noexit`.

**Comment by oantolin** [comment]
I've discussed parts of this a bit before with @minad, @clemera, @protesilaos and @holgerschurig.

**Comment by minad** [comment]
Sounds like a good and well thought out proposal. I like in particular how you made `embark-act` exiting in a backward compatible way. If it simplifies things I like it even more! :rocket:

I guess you will also change that `embark-exit` leaves only one minibuffer recursion level instead of going all the way to the toplevel as happens with the current `embark-act`?

**Comment by oantolin** [comment]
> I guess you will also change that `embark-exit` leaves only one minibuffer recursion level instead of going all the way to the toplevel as happens with the current `embark-act`?

Yes, I edited that in after you read the proposal. 😛

**Comment by jaor** [comment]
From a very new user of embark: this sounds good to me.  Personally, i
tend to forget about noexit until it's too late.  

Instead of making embark-exit the default for embark-post-action-hook,
or asking people to set that variable if they want that behaviour, i
would perhaps have a customizable flag controlling it: i think that
would make the feature easier to document and easier to discover; and
one could even make `C-u embark-act` toggle the flag's value for the
invocation at hand.

Just my 2 pennies from the peanut gallery!

**Comment by clemera** [comment]
This sounds all good to me, but regarding the action exit behaviour my views differ: I like that I can decide to exit or not to exit, most of the time I exit, sometimes not. Making exit the default wouldn't be nice for me as I wouldn't be able to choose not to exit when it is preferable but I also wouldn't like to press `C-g` most of the time.

**Comment by minad** [comment]
> Instead of making embark-exit the default for embark-post-action-hook,
or asking people to set that variable if they want that behaviour, i
would perhaps have a customizable flag controlling it: i think that
would make the feature easier to document and easier to discover; and
one could even make `C-u embark-act` toggle the flag's value for the
invocation at hand.

@jaor Maybe slightly easier or it depends on the perspective. You wouldn't get the feature for free. By simply adding the embark-exit command to the post-action-hook you don't need an extra customizable option. I consider that an improvement!

> This sounds all good to me, but regarding the action exit behaviour my view is the following: I like that I can decide to exit or not to exit, most of the time I exit, sometimes not. Making exit the default wouldn't be nice for me as I wouldn't be able to choose not to exit when it is preferable but I also wouldn't like to press C-g most of the time.

@clemera You are right. My judgment is biased since I would just remove the embark-exit from the post-action-hook and continue to enjoy the non-exiting Embark! The proposal is lacking if you assume that there are users who need both exiting and non-exiting commands. But in this case I think you could easily mitigate that by removing the embark-exit from the hook and then writing a small wrapper my-embark-with-exit which adds it back temporarily?

@oantolin So maybe the proposal should be changed such that you do not add embark-exit by default to the post-action-hooks? 

* Add embark-exit, but do not put it in post-action-hooks
* Rename embark-act-noexit -> embark-act
* Add embark-act-exit which adds embark-exit temporarily to the post-action-hooks

**Comment by jaor** [comment]
On Thu, Jan 21 2021, Daniel Mendler wrote:

>     Instead of making embark-exit the default for embark-post-action-hook,
>     or asking people to set that variable if they want that behaviour, i
>     would perhaps have a customizable flag controlling it: i think that
>     would make the feature easier to document and easier to discover; and
>     one could even make C-u embark-act toggle the flag's value for the
>     invocation at hand.
>    
> @jaor Maybe slightly easier or it depends on the perspective. You wouldn't get the feature for free. By
> simply adding the embark-exit command to the post-action-hook you don't need an extra customizable option. I
> consider that an improvement!

@minad you might well be right; but putting myself in the shoes of a new
embark user (which turns out to be easy :)) and thinking of the scenario
where i use embark-act, i see it not exiting and i want it to, my first
reaction would be to go to embark's defcustoms and look for something
with 'act' in its name, or perhaps 'exit'.  i don't think i'd just think
"oh, there must be a post-action hook where i can change that".  

also, i can see scenarios where the position of embark-exit in the list
of post hooks might be relevant, and it's a pain to control that it
always ends last in that list (especially with deferred, third-party
package loading a la use-package).

**Comment by minad** [comment]
@jaor These are good points. I think I agree. There the nice proposal goes... And we will get `embark-act`, `embark-act-exit` and `embark-exit` in the end.

**Comment by oantolin** [comment]
@joar Good point about the discoverability of a boolean variable vs putting something on a hook.

@clemera So you mostly exit, but want to be able to occasionally not exit. That case is indeed not well served by my proposal. :(

I can imagine three different variants of `embark-act`:

- one that always exits (the current `embark-act`), 
- one that doesn't exit (the current `embark-act-noexit`), and
- a configurable one (the `embark-act` of the proposal, whether it is configured through hooks or through a boolean variable as @jaor suggests is an independent decision).

For any of the three types we could decide that `C-u` makes it have the opposite exiting behavior. (The current `embark-act{,-noexit}` don't use the prefix argument for anything; to pass a `C-u` to the action, you press `C-u` right *after* `embark-act{,-noexit}`.)

So @clemera, what user interface would you prefer to indicate a non-exiting action?

- Having two commands: any choices two of the three types works, and then they don't even need the `C-u` behavior toggle.
- Having one command with the `C-u` toggle: again, any of the three types works, but I'd probably go with the configurable.
- Something else?

**Comment by oantolin** [comment]
I think my current favorite is basically what @jaor suggested: have a single `embark-act` command, whose exit behavior is controlled by a boolean defcustom, and for which `C-u` makes it do the opposite of what you configured it to do. I'd probably make exiting the default, because I want to call it `embark-act` and preserve the meaning.

I'll still add `embark-exit` because even if it isn't recommend for the post action hook, I would still use it on its own, and having it will allow me to simplify the implementation of `embark-act`.

**Comment by oantolin** [comment]
Mmh. I think Emacs terminology says to call the command `embark-abort` rather than `embark-exit`: exiting seems to mean *accepting* the minibuffer input.

**Comment by jaor** [comment]
On Thu, Jan 21 2021, Daniel Mendler wrote:

> @jaor These are good points. I think I agree. There the nice proposal
> goes... And we will get embark-act, embark-act-exit and embark-exit in
> the end.

hmm, do you really prefer that to (C-u) embark-act and
embark-act-exit-p? (i'm probably missing a use case or two here, i
suppose).

**Comment by minad** [comment]
Regarding the `embark-exit` command and top-level modification I think we all agree. But the name `abort` I find questionable, since you also have the name `embark-act-noexit`.

But I am pretty much indifferent regarding the choice of the commands, since it will always be possible to write simple command wrappers to achieve the desired behavior. I would prefer the simpler solution. Maybe just have two commands `embark-act-exit` and `embark-act-noexit` without a toggle and without a configuration is the simplest thing, as it is now.

**Comment by minad** [comment]
@joar I didn't understand you. Do you prefer having a single `embark-act` command and then use a `C-u` toggle to switch the exiting behavior over two separate `embark-act-exit` and `embark-act-noexit` commands? I am indifferent honestly.

**Comment by jaor** [comment]
On Thu, Jan 21 2021, Daniel Mendler wrote:

> @joar I didn't understand you. Do you prefer having a single
> embark-act command and then use a C-u toggle to switch the exiting
> behavior over two separate embark-act-exit and embark-act-noexit
> commands?

yes, that's what i was proposing.  it's totally subjective, but to me it
feels more elegant to have single name for the command, since both
variants are doing the same bulk job.  C-u for variants is such a common
idiom; and with the C-u toggle, if i happen to like the default value or
if i use both variants similarly often, i don't even need to know the
boolean option exists. finally, i only need to define one shortcut,
which is nice because they're in short supply :)

of course i can always define my own jao-embark-act and have all that,
no matter what, but it's kind of nice to get it just out of the box...

**Comment by protesilaos** [comment]
Hi everyone! This happened while I was asleep. Just joining in!

Overall I like the proposal and only want to focus on the following point:

> oantolin: I think my current favorite is basically what @jaor suggested: have a single embark-act command, whose exit behavior is controlled by a boolean defcustom, and for which C-u makes it do the opposite of what you configured it to do. I'd probably make exiting the default, because I want to call it embark-act and preserve the meaning.
>
> [...]
>
> jaor: yes, that's what i was proposing.  it's totally subjective, but to me it feels more elegant to have single name for the command, since both variants are doing the same bulk job.  C-u for variants is such a common idiom; and with the C-u toggle, if i happen to like the default value or if i use both variants similarly often, i don't even need to know the boolean option exists. finally, i only need to define one shortcut, which is nice because they're in short supply :)

I think this is the right approach.  You can also add an example key binding in the docs on how to get both prefixed and unprefixed versions to work side-by-side (there is at least one case where I do that in my config).  For example:

```elisp
(use-package embark
  ...
  :bind (("C-," . embark-act)
         ("C-." . (lambda ()
                    (interactive)
                    (embark-act '(4))))))
```

> oantolin: Mmh. I think Emacs terminology says to call the command embark-abort rather than embark-exit: exiting seems to mean accepting the minibuffer input.

Yes, this is correct albeit obscure.

**Comment by clemera** [comment]
> So @clemera, what user interface would you prefer to indicate a non-exiting action?
>
>    Having two commands: any choice of two of the three types works, and then they don't even need the C-u behavior toggle.
>    Having one command with the C-u toggle: again, any of the three types works, but I'd probably go with the configurable.
>    Something else?

I think having a command with `C-u` prefix and an option to configure the default would be optimal. Users can decide which should be the default behaviour and can toggle it via `C-u` and if they like they can add another command to their config.

**Comment by oantolin** [comment]
OK, I've implemented the @jaor option. I decided to rename `embark-exit` to `embark-quit`, since "exit" means something else and while both "abort" and "quit" have the right meaning I prefer the sound of "quit".

Oh, @protesilaos, `embark-quit` would be a good option for `C-g` in `embark-collect-mode-map`, I made sure it ran the minibuffer exit hook so you could use it that way.

**Comment by oantolin** [comment]
I also changed `embark-collect-snapshot` to quit the minibuffer, since no-one complained about that one. 😉 

Thanks everyone for your help and suggestions!
