### ISSUE TITLE
Configurable input getter 

### ISSUE THREAD

**Issue by clemera** [oantolin/embark#12]
Right now `embark--metadata` uses `minibuffer-contents`. For selectrum and other frameworks another function would be needed so maybe an `embark-input-finders` option would do?

**Comment by oantolin** [comment]
I don't understand: are you suggesting that `embark--metadata` still consult `minibuffer-completion-table` and `minibuffer-completion-predicate` but use something more general in place of `minibuffer-contents`? That sounds odd to me.

Plus, it's also unnecessary: the main purpose of `embark--metadata` is for `embark-category`, and that in turn is only used as a classifier. The classification is already fully configurable, that's what the variable `embark-classifiers` is for.

Maybe I'm not understanding the purpose of generalizing one of the three ingredients in `embark--metadata` but not the others.

**Comment by clemera** [comment]
> are you suggesting that embark--metadata still consult minibuffer-completion-table and minibuffer-completion-predicate but use something more general in place of minibuffer-contents?

Yes, it may be odd but in selectrum (and I believe ivy, too) the input is not defined by `minibuffer-contents` (which includes the candidate list for those frameworks). The metadata can depend on the input as you mentioned on reddit. But it's true that the category should not depend on user input so this accuracy might not be necessary in practice.

**Comment by oantolin** [comment]
You don't need anything to change in embark for this. Today you can already do:

```elisp
(defun my-category ()
  (completion-metadata-get
   (completion-metadata (however-one-gets-the-input)
                        minibuffer-completion-table
                        minibuffer-completion-predicate)
   'category))

(setq embark-classifiers
      '(embark-buffer-local-type
        my-category
        embark-package
        embark-symbol))
```

Or even:

```elisp
(defun my-category ()
  (completion-metadata-get
   (completion-metadata (however-one-gets-the-input)
                        minibuffer-completion-table
                        minibuffer-completion-predicate)
   'category))

(defalias 'embark-category 'my-category)
```

**Comment by clemera** [comment]
Thanks, somehow the `The classification is already fully configurable, that's what the variable embark-classifiers is for.` sentence didn't sink in ;)

**Comment by clemera** [comment]
This still requires one to

**Comment by oantolin** [comment]
> Thanks, somehow the `The classification is already fully configurable, that's what the variable embark-classifiers is for.` sentence didn't sink in ;)

No problem! 

And the completion category is not really that informative anyway: if you look at the default value of `embark-classifiers` you'll see it has several functions besides `embark-category`. On Emacs 26.1, `M-x` doesn't even set the `command` completion category...

**Comment by clemera** [comment]
I believe there isn't a `command` category in Emacs 26 at least I can't find it in the documentation which says:

    currently, the ‘buffer’, ‘file’, and ‘unicode-name’ categories are
     defined, but others can be defined via specialized completion
     functions (*note Programmed Completion::).

**Comment by clemera** [comment]
But `completion-category-defaults` also mentions `project-file` and `info-menu` as additional categories.

**Comment by oantolin** [comment]
Grepping in the Emacs 28 source these are the completion categories I found: bookmark, dabbrev, info-menu, environment-variable, command, email, buffer, unicode-name, project-file, bibtex-key, bibtex-string, ecomplete.

I haven't checked for other versions of Emacs yet.

Lots of stuff about completion is ad hoc. For examples, `C-h v` and `C-h f` use actual symbols instead of strings and don't report any completion category! But `M-x` uses strings; on Emacs 26 it doesn't report any completion category either, on Emacs 28, as I mentioned it says "command". *shrug*.

That's why I have an `embark-classifiers` variable in the first place: I knew obtaining the completion category was nowhere near good enough. I currently have, besides the completion category:

- a way to detect symbols, designed to catch variables, functions and commands.
- a way to detect packages

Why aren't packages, variables, and functions not completion categories? :)

**Comment by clemera** [comment]
> Why aren't packages, variables, and functions not completion categories? 

Sounds like a good candidate for `report-emacs-bug`
