### ISSUE TITLE
Add Embark transformer to strip consult-isearch tofu

### ISSUE THREAD

**Issue by minad** [oantolin/embark#124]
I am using the 'invisible property sometimes with the unicode prefix, e.g. in consult-buffer and consult-isearch. In the 'consult-location case I am using the 'consult-location prefix with a 'display property. You said you cannot rely on the properties since they are stripped. However would it be possible to just *always* strip the unicode prefix in actions like embark-save/embark-insert? Maybe replace embark-save/embark-insert in embark-consult with the variants which strip the unicode prefix? Or is there any other possibility to signal to Embark that such processing is needed? For consult-buffer you are using these Embark transformer facilities, for consult-location you use an extra keymap, which I consider a bit of an overkill. Could we just use the transformer in all of those cases - consult-location, consult-buffer and consult-isearch?

**EDIT**: Stripping the prefix via a transformer does not work for consult-location since there you want to retain it for occur-mode? So maybe the only thing needed would be to add consult-isearch and similar tofu-prefixed categories to the transformers?

**Comment by oantolin** [comment]
Let me explain my reasoning process for the way things currently are, and then we can decide if anything should change.

First, I worry a bit about `embark-insert` always stripping the prefix. It is a general action and might get used in a case where the prefix is really a part of the candidate. This seems unlikely, but I'm not sure seeming unlikely is a good enough reason to ignore the possibility.
 
Second for `consult-location`, the default action needs the prefix to disambiguate (`consult-line` needs to distinguish indentical lines, `consult-mark` needs to distinguish between marks on the same line), so it shouldn't be removed by a transformer. This, combined with not wanting `embark-{insert,save}` to always remove the prefix, led me to add a separate keymap for `consult-location`.

Now, why didn't I do the same thing for `consult-buffer`? Well, there it was because the dedicated keymap would have been huge! But also, and I'm a bit embarrassed by this, I didn't stop to think whether the default action, the `consult-buffer` command really needs the prefix or not because I don't use it much myself yet. I think it should probably work unless you have coincidences between buffer names and bookmark names, etc.

**Comment by minad** [comment]
> First, I worry a bit about embark-insert always stripping the prefix.

Agree. I suspected this reason.

> Second for consult-location, the default action needs the prefix to disambiguate (consult-line needs to distinguish indentical lines, consult-mark needs to distinguish between marks on the same line), so it shouldn't be removed by a transformer.

Okay, thank you for explaining this and confirming.

> Now, why didn't I do the same thing for consult-buffer? Well, there it was because the dedicated keymap would have been huge! 

Agree. A dedicated keymap would be over the top. I like the dispatching behavior we are having now.

> But also, and I'm a bit embarrassed by this, I didn't stop to think whether the default action, the consult-buffer command really needs the prefix or not because I don't use it much myself yet. 

It would be safer to have the prefix but I don't think it will hurt too much if you always remove it as you are doing right now.

> and then we can decide if anything should change.

My suggestion would be to keep things as is and only add a transformer for consult-isearch which strips the prefix. We should simply do this for all categories with tofu prefixes where we do not care too much about the disambiguation.

**Comment by oantolin** [comment]
Mmh. The default action for `consult-buffer` does not work: since it gets the candidate without the prefix it doesn't match and `consult-buffer`, "oh, the user must want a brand new buffer with this name".

**Comment by oantolin** [comment]
For the `consult-location` and `consult-buffer` categories, at least, it would be great if the default action got the original candidate and all other actions got the transformed candidate. There isn't a nice way in Embark to do that right now, the transformer applies to all actions including the default one...

**Comment by oantolin** [comment]
The default action is special in that it is the source of the candidates. It would make sense that for the default action the transformers are not applied.

**Comment by oantolin** [comment]
It would be so nice if the candidates were reliably more than strings, even just strings + reliable text properties would be nice.

**Comment by minad** [comment]
Yes, indeed. In Consult I switched some metadata to properties now, since when accessing candidates directly I have access to reliable properties. Sometimes this is an improvement. The only problem is really the return value of completing-read which removes all the useful information. 

My proposal would be to change completing-read such that it must always retain the properties of the selected candidate. The plain string is only allowed in the case when you enter a new candidate (require-match=nil). I don't understand why it is not implemented like this.
