### ISSUE TITLE
Embark Export with Consult Multiple Sources

### ISSUE THREAD

**Issue by tpeacock19** [oantolin/embark#141]
Currently embark actions work on individual candidates using a consult function with multiple sources. However, is it possible to allow for `embark-export` to identify the individual candidate categories? Perhaps if its restricted to narrowed candidates? I often find myself using `consult-buffer` and wanting to export, say, a list of buffers or files but its restricted to just the embark collect buffer.

**Comment by oantolin** [comment]
Good idea! I'll definitely do something like this. If all the candidates have the same type (all buffers or all files, for example) you should get the usual export for them (ibuffer or dired, in those examples).

The question is what to do if they are of mixed types. I think the reasonable options are:

1. Fallback to embark-collect
2. Export those of each type separately. 

Maybe 2 is best even thought it could produce several buffers.

**Comment by tpeacock19** [comment]
I think that 1 would probably be the most applicable. If someone were to export I imagine it means they want to act on, or refer to, all of the items as a collective. So keeping them in one place/buffer would be best?

**Comment by minad** [comment]
I tend to agree with @tpeacock19 to use the simpler option 1. But option 2 also has some appeal, it is like "decomposing" the candidates somehow, but probably too different from how collect operates usually. I would not expect multiple buffers.

I see these alternatives:

1. Fallback to collect
2. Export each type to its own buffer
3. Refuse to export
4. Export only the first type or the nth type depending on the prefix argument
5. Ask the user for the type, then export
6. Exit Emacs

**Comment by minad** [comment]
Seriously, I am unsure. Which behavior would be the least unexpected?

**Comment by minad** [comment]
I have another option, I think this would be my preferred one - Fallback to collect but be a little bit verbose about it. This could be done generally for export. "No exporter available - falling back to collect", "Cannot export multiple candidate categories - falling back to collect".

**Comment by jaor** [comment]
i would use a single buffer, but grouping entries by type, in some
way that is visual and navigable, i.e., having a command to move to the
next group of matches... showing the candidates as an outline seems the
quickest way of providing that, the hosing commands being very
useful. and then another command (a toggle, actually) to flatten the
list and recover matching order.

so it'd be a bit like multiple buffers, but all in one.

**Comment by minad** [comment]
@jaor Unfortunately this seems not possible since the export buffers have a special major mode, like dired or ibuffer. But for the collect buffer this enhancement sounds like a good idea, having some sections. It could even work for live collect, then we get some helm-like headlines.

**Comment by jaor** [comment]
On Mon, Feb 01 2021, Daniel Mendler wrote:

> @jaor Unfortunately this seems not possible since the export buffers
> have a special major mode, like dired or ibuffer.

well, there's things like https://polymode.github.io/, but probably too
complex for this use case.

> But for the collect buffer this enhancement sounds like a good idea,
> having some sections. It could even work for live collect, then we get
> some helm-like headlines.

i'm wondering if selectrum could do that too (maybe it already
can?)... at any rate, it'd be a useful feature in my book (twenty years
ago, i used macs for a couple of years, and grew very fond of a
helm-like thing called quicksilver; there you would start typing
searching by default for all possible categories, like having a unique
"consult" command, and the ui would arrange them for you and give you
easy ways of jumping between them.  i think consult's narrowing is near
to it, but i haven't learned how it use it properly yet).

cheers,
jao
-- 
A student came to the master and asked, for the master was one of them
who knew such things: "Does Emacs have the Buddha nature?" The master
contemplated this for some time, and answered: "I don't see why not,
it has about everything else."

**Comment by oantolin** [comment]
@minad

> Seriously, I am unsure. Which behavior would be the least unexpected?

I insist that the least unexpected is either 1 (just collect 'em) or 2 (one buffer per type), and I don't think I'd seriously consider 3 (unhelpful), 4 (which one is the nth?) or 5 (I don't like it, export should export all candidates, that's it's purpose). 

@jaor: As @minad said the point of export is that you get buffers in a type specific major mode. If you just want a single buffer where you can see all candidates and have type-appropriate actions for each, why invent some new type of buffer? An embark collect buffer already does that! We can discuss if the **collect** buffer should maybe be subdivided by candidate type, but this is definitely not something **export** should try to do. (Unless things like poly-mode are actually able to have part of a buffer in dired mode and part in ibuffer mode, which I seriously doubt.)

For the collect buffer, how about changing nothing in grid view, but in list view adding a column with the candidate type, so that you can sort on it if you want?

**Comment by minad** [comment]
@jaor 

> well, there's things like https://polymode.github.io/, but probably too
complex for this use case.

Yes, I am aware. But I had somehow already excluded this as a possible solution :)

> i'm wondering if selectrum could do that too (maybe it already
can?)... 

As far as I know it cannot. You can propose it there. But the consult-multi completion category is consult specific, so there is no good way to communicate to Selectrum that the candidates belong to different groups.

> i used macs for a couple of years, and grew very fond of a
helm-like thing called quicksilver; there you would start typing
searching by default for all possible categories, like having a unique
"consult" command, and the ui would arrange them for you and give you
easy ways of jumping between them.  i think consult's narrowing is near
to it, but i haven't learned how it use it properly yet).

So you would probably like to have something like this too: https://github.com/minad/consult/issues/196?

**Comment by minad** [comment]
@oantolin 

> I insist that the least unexpected is either 1 (just collect 'em) or 2 (one buffer per type), and I don't think I'd seriously consider 3 (unhelpful), 4 (which one is the nth?) or 5 (I don't like it, export should export all candidates, that's it's purpose).

What about option 6, printing a helpful message?

> For the collect buffer, how about changing nothing in grid view, but in list view adding a column with the candidate type, so that you can sort on it if you want?

Sounds like a good idea too, more aligned with the list view you already have.

**Comment by oantolin** [comment]
> What about option 7, printing a helpful message?

You mean falling back to collect but also printing a message? That's just lipstick on option 1. I don't mind adding a message, but it's an empty gesture and it isn't really any more useful than 1 without a message in my opinion. I mean, if we go with 1 I might as well add the message, but to me, the message does not make option 1 any more or less attractive vs option 2.

**Comment by oantolin** [comment]
Oh, I just realized that I should enhance the candidate collector for collect buffer so that if a region is active, it only grabs those candidates. That way, even if we go with the fallback-to-collect option, you can select a region of only files, say, and export that to dired.

**Comment by oantolin** [comment]
Similarly the dired target collector should only grab the marked files, and ditto for ibuffer.

**Comment by jaor** [comment]
On Mon, Feb 01 2021, Daniel Mendler wrote:

> So you would probably like to have something like this too:
> minad/consult#196?

Possibly.  Although i must confess i am not sure i'd use it enough to
justify a big development effort.  If embark-become can switch between
different consult commands retaining my current candidate, that'd be
probably a good "quicksilver" experience for me.

**Comment by jaor** [comment]
> For the collect buffer, how about changing nothing in grid view, but
> in list view adding a column with the candidate type, so that you can
> sort on it if you want?

sounds pretty good to me.

**Comment by minad** [comment]
> Possibly.  Although i must confess i am not sure i'd use it enough to
justify a big development effort.  If embark-become can switch between
different consult commands retaining my current candidate, that'd be
probably a good "quicksilver" experience for me.

@jaor 

I must admit I fail to see a compelling use case for async multi sources. For basic async multi source support without delay/debouncing not much code would be required - not significantly more than what I have now. I just don't think I want to combine multiple static and async sources together. Async sources by itself are a relatively heavy feature in comparison to the rest, since they require interaction with the completion UI. Furthermore refreshing too often makes Emacs slow, triggering the candidate generation too often creates unnecessary load and so on. In particular in commands which are supposed to be very fast like buffer switching I would dislike any slowdown, due to UI updates or starting background file search processes. One would have to delay starting the search as has been suggested in minad/consult#196 - such debouncing would make things more complex in any case.

My mistake was that I called the sources "sources", I should have better called them "groups" or "collections". Source sounds too dynamic ;)

@oantolin What do you think about async multi sources? Sorry for hijacking this issue.

**Comment by oantolin** [comment]
Following @tpeacock19's advice (and @minad's), I've implemented the first option: if all candidates transform to the same type use the exporter for that type, otherwise fall back to collect. bc042465dbc5b29df23ab736b924b48fe7d074e2

I forgot the (so-called 😛) helpful message. I'll add it next.

I ran into some trouble using this with `consult-buffer`. It seems to work well for buffers, but for files I get an error about non-existing files. I haven't investigated thoroughly yet, but I think dired needs the files to exist and recentf doesn't check if they still do. If that's indeed the problem, I'll silently drop non-existing files in the dired exporter (violating the idea that export should handle **all** candidates, but what else can I do?)

**Comment by minad** [comment]
What is dired doing if you delete files behind its back from outside Emacs? I expect that dired handles this properly?!

**Comment by oantolin** [comment]
I may just be wrong about what is going on.

**Comment by oantolin** [comment]
> What is dired doing if you delete files behind its back from outside Emacs? I expect that dired handles this properly?!

I think dired handles file deletions graceful once the dired buffer is up and running, but when you create it using `(dired (cons directory files))` it assumes that all files in the `files` list do exist.

**Comment by minad** [comment]
Okay, probably doing the file cleanup during export is the right thing then. I don't want to cleanup the recent files directly in the buffer source in order to avoid fs access there. But for the export I think this is acceptable.

**Comment by oantolin** [comment]
> But for the export I think this is acceptable.

Either it is acceptable or it fails with an error message, so I'm going with acceptable. 😉

I think I would have discovered this problem with non-existent files sooner if ... I tested with Selectrum! I mostly used dired export from within `find-file`, and since the file completion table is dynamic, it's never stale. So with default completion or icomplete, the dired exporter never receives deleted files from `find-file`, even if you delete them while `find-file` is open (and even if you haven't refreshed the completion UI). But Selectrum is static, so if you delete a file while `find-file` is running and then export, this triggers the error.

**Comment by oantolin** [comment]
OK, I fixed the dired issue. 4082a69b4a003458bb8fa1ea09802106c55bd8c3

This reminds me that I don't have a bookmark exporter yet. I should do that.

**Comment by oantolin** [comment]
I tried adding the "Multiple candidate categories - falling back to %s" message, but realized that embark-collect-snapshot displays a "Quit" message that covers it up, so maybe it's not worth it.

**Comment by oantolin** [comment]
Added a bookmark exporter. e361607d448243b1a5c6b6eac71627e7636fdabc

**Comment by minad** [comment]
Okay, I guess leaving out the message is okay then. Better than doing another workaround to hide the quit message.

**Comment by oantolin** [comment]
Yeah, I looked into it once. The message is given by `(get 'quit 'error-message)`. I thought maybe a temporary `(put 'quit 'error-message nil)` would mean no message, so it would leave the previous message up, but no, that property must be a string and if you set it to nil you get "peculiar error" (I'm not making this up!). You can set it to `""`, which at least removes the quit message, but it still erases any previous message. So I thought, fine, I'll just get the previous message and redisplay it after quitting. But `(current-message)` is very short lived, and almost always returns `nil`. Then I gave up. 😆

**Comment by oantolin** [comment]
>  What do you think about async multi sources?

While these are implemented very generally in consult, they are mostly meant for external processes, right? In that case it sounds a little weird to combine them: you happen to have several external programs that all take command line arguments in the same format, with the same options, but that still give different enough results that you want to combine their output? *Extremely* improbable.

And mixing sync with async is a bad idea because of the differing minibuffer input formats: the async command use `#cli args#emacs filter` format. I like that a lot about consult commands, and giving up on either of the two parts of the async input just to mix it with some sync sources doesn't sound like a good trade-off to me.

So, I guess I am against all participation of async source in consult--multi.

> Sorry for hijacking this issue.

Not a problem!

**Comment by minad** [comment]
> While async sources are implemented very generally in consult, they are mostly meant for external processes, right?

Well, they are used for processes as of now. But one could also use it for web scraping as @jaor is doing or even async threads within the Emacs runtime as long as we will get this at some point, hopefully not in the form of js workers.

>  In that case it sounds a little weird to combine them: you happen to have several external programs that all take command line arguments in the same format, with the same options, but that still give different enough results that you want to combine their output? Extremely improbable.
> And mixing sync with async is a bad idea because of the differing minibuffer input formats: the async command use #cli args#emacs filter format. 

This does not make any sense. I agree. The idea in the consult proposal was rather to have async sources which just produce without receiving input. One could also devise schemes where the input is somehow distributed to the async sources. But I don't see the point honestly as I already wrote there. I've also read that helm is very fragile in that respect, you cannot just combine each source with each other, but they must be carefully selected. This makes it even less useful.

> I like that a lot about consult commands, and giving up on either of the two parts of the async input just to mix it with some sync sources doesn't sound like a good trade-off to me.

I will not give up on anything just for the sake of having an obscure feature. This is a no-go.

Thank you for your opinion. We will see. As long as nobody comes along with a compelling use case which I can see myself using or which I find at least convincing such a feature won't get it.

**Comment by oantolin** [comment]
I think this issue is basically dealt with. I haven't added the third column to the collect list view, but I'm not sure we really need it. For `consult-buffer`, at least, the candidates are naturally grouped by type anyway. I think I won't add it for now, but if it seems necessary in the future we can certainly revisit this decision.

As usual, please test @tpeacock19.

Oh, and I also haven't fixed the candidate collectors to take the region or marked files in dired, etc., into account. That probably is a good idea.

**Comment by oantolin** [comment]
If you are getting a collect buffer for bookmarks, maybe you don't have the `(bookmark . embark-export-bookmarks)` entry present in your `embark-exporters-alist`, @tpeacock19. Loading a `defcustom` again doesn't set the variable value, since you might have changed it. You can put point on the `defcustom` and press `C-M-x` to get the new default value.

**Comment by oantolin** [comment]
Also, there was a horrible typo that kept the exporter from working, a misplaced parenthesis. cc0749dccc815887227fc65d4792407b0744378d

Sorry, about that. But I think your problem was what I said above, because if you did have the right exporter the typo would have meant that nothing happened. And instead of nothing you did get a collect buffer.

**Comment by tpeacock19** [comment]
The problem was that I did not have a buffer named `*Bookmark List*`. The `embark-export-bookmarks` function will not execute unless it is already created. Can we have the function create the buffer if necessary?

**Comment by oantolin** [comment]
I don't believe that is the issue, @tpeacock19, since I've tested it both with an without that buffer existing.

**Comment by tpeacock19** [comment]
```elisp
(defun embark-export-bookmarks (bookmarks)
  (let ((bookmark-alist
         (cl-remove-if-not
          (lambda (bmark)
            (member (car bmark) bookmarks))
          bookmark-alist))
        saved-buffer)
    (when-let ((buffer (get-buffer "*Bookmark List*")))
      (with-current-buffer buffer
        (setq saved-buffer (rename-buffer "*Saved Bookmark List*" t)))
    (bookmark-bmenu-list)
    (pop-to-buffer
     (with-current-buffer "*Bookmark List*"
       (rename-buffer "*Embark Export Bookmarks*" t)))
    (when saved-buffer
      (with-current-buffer saved-buffer
        (rename-buffer "*Bookmark List*"))))))
```

`get-buffer` returns nil if the buffer does not exist. The when-let will not execute, correct?

**Comment by oantolin** [comment]
That's correct and is not the problem. You are using the version where I misplaced a parenthesis and put everything inside the `when-let` by accident! Please test the updated version. ab4b4371883425991ae8b8e9f3e809d20b20251c

**Comment by tpeacock19** [comment]
I see, its working on the latest commit now. I guess defined variables do not update when you reload a file. Something I probably should have known.

**Comment by oantolin** [comment]
Great, glad it's working, @tpeacock19. The thing with custom variables not updating has bitten me many times. It's for a good reason: if people did customize them you wouldn't want reloading to overwrite the customized value. Even using `C-x C-e` won't change the value, but `C-M-x` does.
