### ISSUE TITLE
embark-consult-refine-multi-type falls back to 'general

### ISSUE THREAD

**Issue by jakanakaevangeli** [oantolin/embark#143]
Consult-buffer treats a string that doesn't match any candidate as a buffer,
creating it. Perhaps it would be sensible for embark to also fall back to
'buffer rather than 'general in this case.

**Comment by minad** [comment]
No this does not work unfortunately since the consult-multi category can be used also by other consult--multi commands, which may not even be buffers. If you type a new buffer name it has the category general. When do you want to execute actions on a new, non-existing buffer?

**Comment by jakanakaevangeli** [comment]
I didn't know consult--multi could be used for other things, that's pretty
neat. I personally only ever use embark on a non-existing buffer to open it in
a new window. I guess it won't hurt me so much to use `C-x 4 b` for thoes rare
occasions.

Shall I close this issue or do you think there might be a way to somehow
specify a fallback category for nonexistent candidates in consult--multi
commands?

**Comment by minad** [comment]
> I guess it won't hurt me so much to use C-x 4 b for thoes rare
occasions.

Yes, I think that's the way to go. Or create the buffer and fix the windows afterwards.

> Shall I close this issue or do you think there might be a way to somehow
specify a fallback category for nonexistent candidates in consult--multi
commands?

I thought about that, but it seems to me that there is no way to communicate this to Embark easily. Right now things are very simple, every candidate just gets the consult-multi text property attached. This is a very clean boundary between Marginalia/Embark and Consult. For this reason I just decided to go with the 'general category in this case and just hope that this slight inconvenience is okay for everyone.

So my initial reaction would be to keep it as is and close this issue. But I just saw that I made a mistake during my recent consult--multi refactorings/generalisations. **Right now the new buffer creation is broken.** I will fix this and maybe I will have another idea about this issue on the way.

**Comment by jakanakaevangeli** [comment]
Daniel Mendler <notifications@github.com> writes:
> Right now the new buffer creation is broken.
Oh I didn't notice that, because I was using a non-recent version of
consult. Good look with fixing.

**Comment by minad** [comment]
The fix is easy, it was just an oversight. No serious problem. Regarding this issue, I think we should keep it as is. I don't want to communicate this as additional metadata, as global variable or via some other means. This is not really worth it I think. Note that you can also use embark-become from consult-buffer if you want to create in another window.

**Comment by jakanakaevangeli** [comment]
Actually a technically simple but kind of daunting idea just came upon
me. Posting it here in case you are interested, but of course no
pressure on implementing it, because it is far from perfect.

Basically, instead of 'consult-multi, each consult--multi command could
report a different category, perhaps consult-multi-buffer for
consult-buffer-* and consult-multi-foo for consult-foo-* or whatever. In
embark-transformer-alist, each of this categories would then be handled
by functions identical to each other except for their fallback
subcategory.

This way you can avoid introducing new global variables but the daunting
part is of course having to maintain embark's alist to follow consult's
additions of new consult--multi commands. Perhaps
embark-transformer-alist could be somehow generalised to allow one
function to handle all symbols starting with consult-multi- or maybe all
symbols with a certain property.

**Comment by oantolin** [comment]
Another possibility, @jakanakaevangeli, is to bind `o` to `switch-to-buffer-other-window` in `embark-general-map`. The other more specific keymaps have higher priority, so this binding for `o` would only be used for general candidates.

**Comment by jakanakaevangeli** [comment]
> bind `o` to `switch-to-buffer-other-window` in `embark-general-map`.
Good idea, thanks.

**Comment by minad** [comment]
@jakanakaevangeli This idea is what we had before, we had a special consult-buffer category. But now it is more generic with the consult-multi category and I have no interest in going back to introducing a category for every command. But if you really care about this issue in your config, you can hack this yourself. It is all configurable. You can overwrite the category of consult-buffer, introducing a consult-buffer category. You can register the consult-multi transformer in Embark for this category. There are many many alternatives here. But doing this by default is not worth it since the configuration effort would be larger, and the reason being only that we do not want to have the 'general menu for unknown candidates. Note also that the user could create their own consult--multi commands, maybe even with :require-match=t which would not even have this problem. These custom consult--multi commands will work right away without any further configuration. I would like to keep this :)

**Comment by jakanakaevangeli** [comment]
Thanks!
