### ISSUE TITLE
Default action for consult-*grep doesn't work if you bind directly to `embark-collect-snapshot`

### ISSUE THREAD

**Issue by aaronjensen** [oantolin/embark#146]
Similar issue to #80, though it only reproduces if you have a key bound to `embark-collect-snapshot` and use it, rather than `embark-act`. 

I'm guessing it's because `embark-act` invokes `embark--target`, which sets `embark--command`. Is binding to `embark-collect-snapshot` not supported or is this a bug?

**Comment by oantolin** [comment]
Calling `embark-collect-snapshot` from a key binding definitely *is* supported. I recently changed some things in embark-consult, and must have broken this then. I'll look into it. in the meantime, as a workaround, maybe you can use `embark-export` instead.

**Comment by aaronjensen** [comment]
Great, good to know. For now I'm just using:

```elisp
(defun aj/embark-collect-snapshot ()
    "Embark collect snapshot without act"
    (interactive)
    (embark--target)
    (command-execute #'embark-collect-snapshot))
```

**Comment by oantolin** [comment]
Oh, I didn't screw this up in the recent changes, I must have screwed this up a while ago. :D

If you use `embark-act` and then `RET`, the default action does work. It only fails if you use `RET` on its own, because I forgot to call the functions from `embark-transformer-alist` in that case.

**Comment by oantolin** [comment]
> I'm guessing it's because `embark-act` invokes `embark--target`, which sets `embark--command`

By the way, that wasn't exactly why `embark-act` worked around the bug. It's not `embark-act` that sets `embark--command`, that is set in a minibuffer setup hook, because `embark--command` is whatever command opened the minibuffer, i.e., the value of `this-command` when the minibuffer opens.

So `embark--command` was correctly begin set to `consult-grep`. What the default action does is run `embark--command` on the target, i.e., feed the target back into the command you got it from. But the `consult-grep` commands are very peculiar: the completion candidates they produce are *not* valid inputs for the command, the candidates are in `grep`'s `file:lineno:text` format, not in the `#args#filter` format you type at the minibuffer.

They are in fact the only commands I use that offer completions that are not valid input! So, for the `consult-grep` family I have a target transformer that sets `embark--default-action` to something different from `embark--command`.

Calling that transfomer via `embark--target` is the reason your `aj/embark-collect-snapshot` function worked around the bug.

**Comment by minad** [comment]
> They are in fact the only commands I use that offer completions that are not valid input! So, for the consult-grep family I have a target transformer that sets embark--default-action to something different from embark--command.

This is not true. I am using the rot13 completion style by default :stuck_out_tongue: 

Seriously, this is an interesting argument against the current async design and I wasn't actually aware that this works against Embark when we devised this. But since the accepted inputs differs a lot from the actual format of the candidates (e.g. when using orderless), the statement sounds worse than it actually is. There is no possibility to make this work since the grep filter expression is not part of the candidate string. The whole async model breaks the Embark default action idea since you wouldn't want to restart the whole async process every time. I recall that I argued for doing this when discussing @jaor's spotify client by introducing some caching layer, but it may not have been the best idea.

Note that if we would use the model used by built-in `grep` with a two-step input it would also not work since Embark does not support such multi-minibuffers. Furthermore you wouldn't know what to inject at the first interaction.

**Comment by oantolin** [comment]
I think the consult-grep commands are fine as they are now, I would not suggest changing anything. Embark's idea of the default action works fine most of the time and I think it's OK if it doesn't work _all_ of the time. I'm happy to have a special case for the default action for those commands.

**Comment by aaronjensen** [comment]
Thank you for the quick fix!

**Comment by oantolin** [comment]
I decided to undo that fix and take a more disciplined approach. Here's the backstory of the bug in this issue:

For a long time in Embark, the default action for targets that are minibuffer completion candidates was the command that opened the minibuffer (and non-minibuffer target simply had no default action associated to them). This was not adequate for the consult-grep family, since they produce completion candidates that don't have the same syntax as the minibuffer input.

To fix this first I used a horrible hack: I added a transformer for the xref-location type that was the identity function with the side effect of changing the value of embark--command from consult-grep to embark-goto-location.

(Then I noticed changing embark--command messed with embark-become: it could no longer find the right keymap to offer the user. So I added an embark--default-action variable that the side-effectful transformer for xref-location set. But this is just an aside.)

Then came this issue, where the problem was that I wasn't running the transformer when the user pressed RET in an embark collect snapshot buffer. I wrote a quick fix for that, but now decided to take a less hacky approach. So I dropped the side-effectful transformer and instead added the configuration variables in this commit: 5dbda510f18fcc2aa2333671bf36ac78ee63920d

**Comment by oantolin** [comment]
@minad I've implemented the special casing for `xref-location` in a much better way now. 5dbda510f18fcc2aa2333671bf36ac78ee63920d

And while I was at it, added some default actions for non-minibuffer targets, which didn't use to have a notion of default action before.

**Comment by minad** [comment]
I wonder about the default action fallbacks - why even offer them? I would prefer if default actions would just not be present in this case, since I rather prefer to execute the specific actions then.

**Comment by minad** [comment]
Maybe you could remove this and just don't show the default action in that case/remove it from the keymap. Would that simplify things? I don't like that we have the duplication of keymaps and also this action alist now.

**Comment by minad** [comment]
I have not tested this, but something along these lines. I think a keymap-based approach is a better fit for embarK.

~~~ elisp
diff --git a/embark.el b/embark.el
index 3ffe0ba..c5fe794 100644
--- a/embark.el
+++ b/embark.el
@@ -249,17 +248,0 @@ minibuffer and this variable is irrelevant in that case."
-(defcustom embark-default-action-fallbacks
-  '((file . find-file)
-    (buffer . switch-to-buffer)
-    (symbol . embark-find-definition)
-    (command . embark-find-definition)
-    (variable . embark-find-definition)
-    (identifier . xref-find-definitions))
-  "Alist associating target types with fallback default actions.
-When the source of a target is minibuffer completion, the default
-action for it is usually the command that opened the minibuffer
-in the first place (but this can be overridden for a given type
-by an entry in `embark-default-action-overrides').  But when a
-target comes from a regular buffer (typically a thing at point),
-the default action for each target type is determined by this
-alist."
-  :type '(alist :key-type symbol :value-type command))
-
@@ -565,2 +548,5 @@ relative path."
-   (or embark-overriding-keymap
-        (symbol-value (alist-get type embark-keymap-alist)))
+   (delq nil (list
+              (when-let (def (embark--default-action type))
+                `(keymap (13 . ,def)))
+              (or embark-overriding-keymap
+                  (symbol-value (alist-get type embark-keymap-alist)))))
@@ -569,3 +555 @@ relative path."
-     (make-composed-keymap
-      `(keymap (13 . ,(embark--default-action type)))
-      embark-general-map))))
+     embark-general-map)))
@@ -821,3 +805 @@ default action is given by `embark-default-action-fallbacks'."
-  (or (alist-get type embark-default-action-overrides)
-      embark--command
-      (alist-get type embark-default-action-fallbacks)))
+  (or (alist-get type embark-default-action-overrides) embark--command))
@@ -2050,0 +2033 @@ and leaves the point to the left of it."
+  ("RET" find-file)
@@ -2074,0 +2058 @@ and leaves the point to the left of it."
+  ("RET" switch-to-buffer)
@@ -2085,0 +2070 @@ and leaves the point to the left of it."
+  ("RET" xref-find-definitions)
@@ -2090,0 +2076 @@ and leaves the point to the left of it."
+  ("RET" embark-find-definition)
@@ -2099,0 +2086 @@ and leaves the point to the left of it."
+  ("RET" embark-find-definition)
@@ -2107,0 +2095 @@ and leaves the point to the left of it."
+  ("RET" embark-find-definition)
~~~

**Comment by oantolin** [comment]
Sure, that would definitely work for `<embark-act> RET`, @minad. I did it the other way because I also wanted it to work for `RET` in embark collect snapshot buffers. Of course, I could change `RET` in snapshot buffers to use whatever binding for `RET` it finds in the action keymap.

**Comment by oantolin** [comment]
I'll use the keymap way you suggested, because that way I don't need to repeat `embark-find-definition` for commands, variables and symbols, it'll be enough to put it in the symbol map. More generally, it'll be nice to have inheritance for these default action fallbacks.

**Comment by oantolin** [comment]
I adopted your suggestion, @minad of specifying the fallback action with the binding of RET. It's nice that you get to use keymap inheritance that way. I made it also work for `RET` in embark collect snapshot buffers, which was my flimsy excuse for not doing it this way in the first place. a0c785013153bfbcddc463348320d6e2444dbcf5

**Comment by aaronjensen** [comment]
FWIW, this does not work at all for me anymore. I get "No error here" any time I press enter on an entry. It doesn't matter if I use `embark-act` or `embark-collect-snapshot` directly.

**Comment by oantolin** [comment]
I'd be happy to help if I could reproduce that error, @aaronjensen. But it works fine both in my usual configuration and testing in `emacs -q` as follows:

- `M-x package-intialize`
- `M-x set-variable RET enable-recursive-minibuffers RET t RET`
- `M-x consult-grep RET #some#search M-x embark-collect-snapshot`

If you help me reproduce the error, I will do my best to debug it.

**Comment by minad** [comment]
I am also unable to reproduce.

@oantolin Somehow related, when doing snapshot of grep candidates, and calling the default action, the grep candidates are shown in the same window. This is different from pressing RET on snapshotted consult-line candidates. Is this desired? Maybe this is related to the recent https://github.com/oantolin/embark/commit/659df4bb9b9ac9abbb1afddcae35564137be0d9d?

**Comment by oantolin** [comment]
I don't like that the default action takes over the same window. And I am not sure, but I think this annoying behavior was already present before that commit. I'll look into it.

**Comment by minad** [comment]
> I don't like that the default action takes over the same window. 

Yes, this is what I mean. Ideally, it shouldn't do that.

**Comment by oantolin** [comment]
I think this fixes that taking-over-the-window problem, @minad. 26e73117910e78afa209524ecb8f07add45a9ec3

**Comment by minad** [comment]
Okay, will give it a try soon!

**Comment by aaronjensen** [comment]
I can't repro w/ a minimum repro either, so I'll work on narrowing a repro down
