### ISSUE TITLE
Question: Embark collect buffer

### ISSUE THREAD

**Issue by iris-garcia** [oantolin/embark#150]
Hi, I'm trying to replicate the actions I used to do with Swiper/Ivy/Counsel in which I started a search with Swiper then from the narrowed list I could export to an `ivy-occur` buffer then edit the lines and apply the changes.

Now using `consult-line` when I export to an Embark Collect buffer I don't see an option to edit the lines then apply them, is this intended? 

Thanks.

**Comment by oantolin** [comment]
You should use `embark-export` instead of `embark-collect-snapshot` for this. The difference is that `embark-export` tries to make a buffer with a major mode that is specialized to the type of things you are working with. If you have the embark-consult package loaded, then `embark-export` for `consult-line` will produce a buffer that is in the built-in occur mode. You can then press `e` to put it in `occur-edit-mode`. (One of the goals of Embark is to reuse built-in tools whenever possible, which is why instead of implementing a new method for editing search results, we just export to occur mode.)

Further example: the default configuration for `embark-export` uses dired, ibuffer, package-menu-mode, bookmark-bmenu-mode for files, buffers, packages and bookmarks, respectively.

**Comment by oantolin** [comment]
I guess I didn't answer your question: is this lack of editing capability in embark collect buffers intended? The answer is yes. 😛 But I hope you come to agree that `embark-export` covers this adequately.

**Comment by oantolin** [comment]
If you use `embark-export` from the `consult-grep` family of commands, you get a buffer in `grep-mode`. And then if you have the popular `wgrep` package installed, you can edit the search results in place.

**Comment by oantolin** [comment]
I should point out that if you already have an embark collect buffer and realize you actually wanted to export, you don't need to restart your search: just run `embark-export` in the collect buffer.

**Comment by iris-garcia** [comment]
Hi @oantolin, first of all, thanks for the quick reply. Maybe I'm missing something but when I do `embark-export` after `consult-line` what I get is a buffer with `Embark Collect` major mode (not occur mode), as shown in the screenshot.
![image](https://user-images.githubusercontent.com/3024945/107336239-278d5580-6ab9-11eb-9336-83dc2913cd3a.png)
I just started Emacs then narrowed the scratch buffer with the filter of "visit", then `embark-export`.

Is this a wrong configuration on my side?

**Comment by iris-garcia** [comment]
Ok, so I did get the latest changes and now it works as expected I can see the `occur mode` in the exported buffer, sorry for that (I thought I had the latest version).

Closing the issue!

**Comment by oantolin** [comment]
I'm glad it works now! There are several possibilities: maybe you were running a version that was several days old, or you had not loaded the separate embark-consult package, or you had modified the embark-exporters-alist variable, etc.
