### ISSUE TITLE
embark + selectrum cmr bug

### ISSUE THREAD

**Issue by bdarcus** [oantolin/embark#183]
This is a follow-up to this conversation, and these two comments in particular:

https://github.com/oantolin/embark/issues/176#issuecomment-794500515
https://github.com/oantolin/embark/issues/176#issuecomment-794597585

If I understand those comments correctly, embark should correctly handle [my code](https://github.com/bdarcus/bibtex-actions/blob/main/bibtex-actions.el).

Behavior:

If I do `M-x bibtex-actions-insert-key`, select two candidates, and hit return, I get the expected result: two keys.

If I run the same command, but instead of hitting return, invoke `embark-act` and choose a different command (`bibtex-actions-insert-bibtex`) I get one result.

What I expect: two results.

EDIT: Also, this is with selectrum.

**Comment by oantolin** [comment]
I did see this in the other repo. I've thought about it a bit, but away from the computer so I haven't experimented in Emacs. I think it should work as is with default completion or icomplete (could you test, please?). You are using Selectrum, right? I think that the reason you only get one result with Selectrum is a bug in the Selectrum integration code in Embark, we just didn't think to cover the crm case.

**Comment by bdarcus** [comment]
Your hunch was correct. It works as expected in `icomplete-vertical`.

**Comment by oantolin** [comment]
OK, @bdarcus I think this should fix the issue for Selectrum.

@clemera, maybe you can help me see if I did this in the best way for
Selectrum. The issue is that when using `embark-act` during a
`completing-read-multiple` session, the target finder for default
completion picks up the entire multiple selection as a single string
(it's basically the minibuffer contents except that the last partially
entered candidate is replaced by the top completions), but the
Selectrum target finder I had only picked up the completion of the
last component of the multiselection. To match the behavior of the
default target finder I rewrote it this way:

```elisp
(defun embark-target-selectrum-selection ()
  "Target the currently selected item in Selectrum.
Return the category metadatum as the type of the target."
  (when (bound-and-true-p selectrum-active-p)
    (cons (selectrum--get-meta 'category)
          (if selectrum--is-crm-session
              (replace-regexp-in-string
               (concat "\\`.*" crm-separator "\\(.*\\)\\'")
               (selectrum-get-current-candidate)
               (minibuffer-contents)
               nil nil 1)
	    (selectrum-get-current-candidate)))))
```

Does that seem like a sensible way to do it?

**Comment by bdarcus** [comment]
Thanks!

**Comment by clemera** [comment]
Thanks for the notification, I think the old behavior is a better fit for the Selectrum UI so I would favor to revert this change. When using Selectrum the prompt shouldn't be considered automatically selected when using crm, I would assume you need to select the prompt before calling `embark-act` when you want to act on it.

**Comment by clemera** [comment]
Regarding the code itself in newer version of Selectrum `selectrum-is-active` is used instead of `selectrum-active-p` and to avoid depending on private functions you can replace `selectrum--get-meta` with `completion-metadata` + `completion-metadata-get`.

**Comment by bdarcus** [comment]
> When using Selectrum the prompt shouldn't be considered automatically selected when using crm, I would assume you need to select the prompt before calling `embark-act` when you want to act on it.

In this case, I did select the prompt, and it works as expected when running the default command.

When running through embark-act, however, it only selects one item.

Works fine in icomplete-vertical, so needs to be fixed somewhere.

**Comment by clemera** [comment]
@bdarcus Do you have recipe/example I can use for testing?

**Comment by clemera** [comment]
@bdarcus Do you have recipe/example I can use for testing? It seems to work for me as intended with something like `(completing-read-multiple "Test: " '("this" "with" "selectrum"))` (using the insert action for example).

**Comment by bdarcus** [comment]
The simple scenario I listed in the OP demonstrates it consistently, and @oantolin's change resolves it.

I use your new test scripts to test, and just added this to the end of the install.el file.

``` elisp
(load "~/Code/bibtex-actions/bibtex-actions.el")
(setq bibtex-completion-bibliography "~/org/bib/academic.bib")

(require 'embark)
(setf (alist-get 'bibtex embark-keymap-alist) 'bibtex-actions-map)
```

So:

- `M-x bibtex-actions-insert-key`
- select two items, using `&` as crm-separator
- `M-o` for `embark-act`, then select `bibtex-actions-insert-bibtex`

**Comment by clemera** [comment]
Do you have an example for plain crm which demonstrates the unwanted behavior? For example when doing:

```elisp
(defun check (target)
  (interactive "sTarget:")
  (message "Target: %S" target))

(let ((embark-overriding-keymap '(keymap (?o . check))))     
  (completing-read-multiple "Test: "
                            '("testing" "with" "selectrum")))
```

I can select the prompt and act on it and it will correctly show the current contents as the target.

**Comment by bdarcus** [comment]
> Do you have an example for plain crm which demonstrates the unwanted behavior?

I don't. I only just learned about crm last week :-)

@oantolin - do you have an idea of how to demonstrate this more simply?

**Comment by oantolin** [comment]
@clemera

> I think the old behavior is a better fit for the Selectrum UI so I would favor to revert this change. When using Selectrum the prompt shouldn't be considered automatically selected when using crm, I would assume you need to select the prompt before calling embark-act when you want to act on it.

My reasoning for the change is that I want `embark-act` to target whatever Selectrum considers selected at the moment. Now, how do you figure out what that is? I thought the best criterion would be to target whatever Selectrum returns when you press `RET` (of course the other criterion is what you suggest: ignore what happens you press `RET`, just use whatever Selectrum is highlighting, sort of "do what Selectrum *says*, not what it *does*").

In the crm case when you press `RET`, Selectrum acts on all the candidates listed in the minibuffer except the last (possibly incomplete) one which is replaced by the Selectrum selection.

> Regarding the code itself in newer version of Selectrum selectrum-is-active is used instead of selectrum-active-p and to avoid depending on private functions you can replace selectrum--get-meta with completion-metadata + completion-metadata-get.

Good points. I'll fix those independently of whether this change gets reverted or not.

@bdarcus

> In this case, I did select the prompt, and it works as expected when running the default command.

> When running through embark-act, however, it only selects one item.

In my tests of the old Embark--Selectrum integration code I find that @clemera is correct: selecting the prompt does let you act on all the chosen candidates. (Just to clear, selecting the prompt means using `<up>` to move the higlight to move to the minibuffer input line --I'd call this "selecting the input" rather than "selecting the prompt", since what I call the "prompt" is the stuff that appears on the same line where you type but _before_ what you type.)

Are you sure that didn't work for you?

**Comment by bdarcus** [comment]
> In my tests of the old Embark--Selectrum integration code I find that @clemera is correct: selecting the prompt does let you act on all the chosen candidates. (Just to clear, selecting the prompt means using `<up>` to move the higlight to move to the minibuffer input line --I'd call this "selecting the input" rather than "selecting the prompt", since what I call the "prompt" is the stuff that appears on the same line where you type but _before_ what you type.)
> 
> Are you sure that didn't work for you?

No, I'm not. It didn't even occur to me that would be required, given I'd already selected them.

This ultimately is related to, and I believe another argument in favor of, this issue:

https://github.com/raxod502/selectrum/issues/489

**Comment by clemera** [comment]
@oantolin 
> My reasoning for the change is that I want embark-act to target whatever Selectrum considers selected at the moment. Now, how do you figure out what that is?

In the ideal case you shouldn't need to figure out anything and trust `selectrum-get-current-candidate`, what the user sees as the selection should match the behavior so there is (hopefully) no confusion. 

> In the crm case when you press RET, Selectrum acts on all the candidates listed in the minibuffer except the last (possibly incomplete) one which is replaced by the Selectrum selection.

RET finishes the session the idea is to behave like a usual completing-read session with the difference that you can add more items using TAB. TAB is used to add one to the collected items and RET to finish the session using the already collected ones and the currently selected one.

**Comment by clemera** [comment]
> I'd call this "selecting the input" rather than "selecting the prompt", since what I call the "prompt" is the stuff that appears on the same line where you type but before what you type

I often use these as synonyms but should stop with that to match the used Emacs terminology :+1:

**Comment by bdarcus** [comment]
> RET finishes the session the idea is to behave like a usual completing-read session with the difference that you can add more items using TAB. TAB is used to add one to the collected items and RET to finish the session with the already collected ones plus the currently selected one.

What's so confusing to me about this situation, though, is in my mind, I have selected the candidates; I simply want to tell embark to run another command on them.

**Comment by clemera** [comment]
> What's so confusing to me about this situation, though, is in my mind, I have selected the candidates; I simply want to tell embark to run another command on them.

I agree that it isn't optimal that you have to select the prompt first for this use case, we once thought about selecting the prompt after inserting a candidate with TAB, this would also avoid this intermediate step in this use case and I don't see a downside here but to be consistent this behavior should be the same for other completions and for file completions this wouldn't be optimal.

**Comment by bdarcus** [comment]
> ... to be consistent this behavior should be the same for other completions and for file completions we arrived at the conclusion that it is better to keep the current behavior (see [here](https://github.com/raxod502/selectrum/pull/300)), though I have to reread that myself maybe we should reconsider it.

And, obviously, think about this as well when you do get to working on a POC that allows the "direct-select" approach.

If I can avoid the prompt entirely for multi-selection, this becomes a non-issue for me (though I suspect would remain confusing for others using the prompt for selection).

**Comment by clemera** [comment]
@oantolin Regardless of how we proceed with that I think it is better when we deal with this on the Selectrum side and embark keeps the old version. Just trust whatever `selectrum-get-current-candidate` returns this also avoids that you  might have to deal with more issues which are not really embark issues but should be handled by the Selectrum UI.

**Comment by hmelman** [comment]
> I would assume you need to select the prompt before calling `embark-act` when you want to act on it.

I do like the simplicity of such a statement, but I'll point out it isn't completely true.  Yes `embark-act` (generally) works on the highlighted item, but `embark-collect` and `embark-export` (also available via `embark-act`) work on all the candidates.  

FWIW, I did like the "different prompt selection scheme for files" described in the reference PR, but I've mostly gotten used to the current method, meaning I now make few mistakes doing it.  I think my previous preference for it was just because it's what I was to used from ivy.

I do agree that multiple candidates is slightly different case and could have it's own mechanism.  I don't think I have an opinion on it yet.  If it will require selecting the input to act on the selected candidates, then I think selectrum should have a key to select the input if point is far down in the candidate list (without including the currently highlighted candidate).  Does it have this?  An advantage of requiring you to select the input first is then `embark-act` could be used either way, on just the highlighted candidate, or if that's the input, on all the selected candidates.

**Comment by bdarcus** [comment]
> I do like the simplicity of such a statement, but I'll point out it isn't completely true. Yes `embark-act` (generally) works on the highlighted item, but `embark-collect` and `embark-export` (also available via `embark-act`) work on all the candidates.

Good point to raise those. Ideally we can end up in a place where this all works intuitively and consistently.

**Comment by clemera** [comment]
> I do like the simplicity of such a statement, but I'll point out it isn't completely true. Yes embark-act (generally) works on the highlighted item, but embark-collect and embark-export (also available via embark-act) work on all the candidates.

Your are right but these are included there for convenience though they are different commands, I remember there was some hesitation by @oantolin to add them there for this reason. 

>  If it will require selecting the input to act on the selected candidates, then I think selectrum should have a key to select the input if point is far down in the candidate list (without including the currently highlighted candidate). Does it have this? 

No, currently the shortest way to select it would be to jump to the first candidate using `M-<` and then use `C-p`.

> An advantage of requiring you to select the input first is then embark-act could be used either way, on just the highlighted candidate, or if that's the input, on all the selected candidates.

Yes and this is how it used to be, I think both options should be available.

**Comment by oantolin** [comment]
@clemera You say to trust `selectrum-get-current-candidate`, but Selectrum itself doesn't! When I press `RET` Selectrum doesn't always use `selectrum-get-current-candidate`. :)

I think what's going on is that there are simply two notions of the "current selection" in Selectrum. One is what `selectrum-get-current-candidate` returns, call that the highlight-selection; and the other is what gets used when you press `RET`, call it the RET-selection. In the non-crm case the highlight-selection and the RET-selection agree, but they differ in the crm case.

Which of those is it less confusing for `embark-act` to use? I think it might be the RET-selection:

- As @bdarcus says, it feels to the user like they did select the _n-1_ first candidates, why wouldn't those be included in the selection?

- In the vast majority of Selectrum usage only the RET-selection is relevant. Most of the time Selectrum is used implicitly through its overriding of `completing-read` and friends. Used this way the user never needs to know the concept of highlight-selection even exists, the user just choses one or more candidates and presses `RET` to use the RET-selection. I'd say the highlight-selection is sort of internal to Selectrum and the RET-selection is the external interface.

- Using the RET-selection agrees with what `embark-act` does for default completion and for Icomplete. I'd prefer to have the behavior of `embark-act` as independent of the completion UI as possible.

- I often explain the default action for `embark-act` by saying that the default action does the same thing as just pressing `RET` (except that maybe `embark-act` doesn't quit the minibuffer). If we want pressing `RET` to run the same thing as `embark-act RET`, then we need to use the RET-selection not the highlight-selection.

The only advantage i can think for having `embark-act` use the higlight-selection instead of the RET-selection is what @hmelman said:

> An advantage of requiring you to select the input first is then embark-act could be used either way, on just the highlighted candidate, or if that's the input, on all the selected candidates.

**Comment by oantolin** [comment]
For the record, I think that what @hmelman said here is sort of irrelevant:

> I do like the simplicity of such a statement, but I'll point out it isn't completely true. Yes `embark-act` (generally) works on the highlighted item, but `embark-collect` and `embark-export` (also available via `embark-act`) work on all the candidates.

We are just discussing what `embark-act` should act on. What `embark-collect-*` and `embark-export` use has always been different from what `embark-act` uses. And no change is being proposed to what `embark-collect-*` and `embark-export` use, just to what `embark-act` uses.

**Comment by oantolin** [comment]
@clemera Maybe a good option is to revert this change but also make `TAB` select the input in the crm case. I didn't carefully read the entire discussion you linked to about TAB selecting the input ("prompt" as you call it 😛) but I think it was all about non-crm behavior, right? Maybe in the crm case TAB selecting the input will feel more natural.

**Comment by oantolin** [comment]
If we don't revert this change I need to fix a bug in the crm case when the prompt is selected... 😆

**Comment by clemera** [comment]
> You say to trust selectrum-get-current-candidate, but Selectrum itself doesn't! When I press RET Selectrum doesn't always use selectrum-get-current-candidate. :)

@oantolin
I don't know which case you have in mind, but generally RET might do different things and internally we might use `selectrum--get-full` or such directly but for the purposes of `embark-act` it should use `selectrum-get-current-candidate` to get what is the currently selected candidate according to the UI.

> I think what's going on is that there are simply two notions of the "current selection" in Selectrum. One is what selectrum-get-current-candidate returns, call that the highlight-selection; and the other is what gets used when you press RET, call it the RET-selection.

I don't think of it as two types of selection, RET is the action to exit with the current state, there is only one visual selection and I think that is was `embark-act` should act on. 

> As @bdarcus says, it feels to the user like they did select the n-1 first candidates, why wouldn't those be included in the selection?

It might be a good idea to do that but then we should show the selection visually in Selectrum.

> I'd say the highlight-selection is sort of internal to Selectrum and the RET-selection is the external interface.

As mentioned above I don't think there should be a concept such as RET selection, the interface of Selectrum should be as simple as possible and the visual state should match users expectations.

**Comment by oantolin** [comment]
> I don't know which case you have in mind

I just meant the crm case, where what gets used when you press RET is _very_ different from `selectrum-get-current-candidate`.

> As mentioned above I don't think there should be a concept such as RET selection, the interface of Selectrum should be as simple as possible and the visual state should be the only source of truth.

Do you mean highlighting the first n-1 things on the input line in addition to highlighting what is currently higlighted? And having `selectrum-get-current-candidate` return a string with those n = (n-1)+1 things?

**Comment by clemera** [comment]
> I just meant the crm case, where what gets used when you press RET is very different from selectrum-get-current-candidate.

Yes, that is right but it feels very intuitive to me, maybe not for others? If you think of RET as accept the current state and exit I think it is less surprising then say exiting with the current input.

>Do you mean highlighting the first n-1 things on the input line in addition to highlighting what is currently higlighted? And having selectrum-get-current-candidate return a string with those n = (n-1)+1 things?

I was referring to selecting the prompt after adding a candidate with TAB as you mentioned above that might feel right for crm even if we don't use that behavior in general.

**Comment by clemera** [comment]
The following UI seems simple/good to me:

- RET accepts the current state and exits (behavior stays the same)
- TAB insert the current candidate and proceeds with completion (behavior stays the same)
- `embark-act` acts on the selection (we can change that after TAB the input is selected so you can easily act on the selected set when your are done and also submit it with RET right after inserting one with TAB).

**Comment by hmelman** [comment]
I just played with crm via `info-finder` (I'm using selectrum and embark from melpa yesterday).  My sense is this is exactly the same case as that alternative file selection PR.  What's surprising about selectrum is that it's more efficient.  If you select something via TAB, then another thing is already "highlighted" and is used when you hit RET.  

So in the PR case, you can complete directories with TAB but don't use TAB on the last thing you wanted (as you might with other completion systems) but use RET immediately.  It was the same with `info-finder`, I selected two with TAB and immediately a third was highlighted and using RET would use all three.  If I only wanted the two, I should have used RET instead of that second TAB.  If I selected two with TAB and used `embark-act` and `embark-save`, I got three items.  I think that's the right behavior for embark w/ selectrum, because it's consistent selectrum behavior.  If that selectrum PR is ever reinstated as an option, it should apply here too.  I think this is just a thing that trips up new users and it feels weird because it's not a common case.  At least in my case it didn't take too long to get retrained, others maybe be different.

> We are just discussing what embark-act should act on. What embark-collect-* and embark-export use has always been different from what embark-act uses. And no change is being proposed to what embark-collect-* and embark-export use, just to what embark-act uses.

@oantolin is right and I wasn't proposing changes to either of those commands or their bindings.  I was just pointing out that to a user (particularly a new one), what happens after you "invoke embark" (via `embark-act` I know there are other means too) is a little more complex (with good reason).

> > If it will require selecting the input to act on the selected candidates, then I think selectrum should have a key to select the input if point is far down in the candidate list (without including the currently highlighted candidate). Does it have this?

> No, currently the shortest way to select it would be to jump to the first candidate using M-< and then use C-p.

It may or may not be worth a keybinding for such a function.  It's probably more useful in the crm case since point could be far down the candidate list, in the directory completion case of the PR, point is usually at the top item and just C-p works.  It may not be worth a key.  In this case it's the "how do I undo hitting TAB one too many times when I've already selected a bunch of stuff" solution.  If nothing else, a note in the README could explain this common learning curve issue and that `M-< C-p` is the solution.

**Comment by clemera** [comment]
>  If I only wanted the two, I should have used RET instead of that second TAB. If I selected two with TAB and used embark-act and embark-save, I got three items. I think that's the right behavior for embark w/ selectrum, because it's consistent selectrum behavior. 

Okay somehow it did not click for me what the issue with the old `embark-target-selectrum-selection` is because it all just "felt right" to me because I'm so used to it, I guess that is the hard part about designing user interfaces :laughing:

**Comment by hmelman** [comment]
Yeah, I think its particularly hard with these packages because "completion" is used so often it really is purely muscle memory and these edge cases take a lot of words to describe and slow reading to comprehend. :)

**Comment by clemera** [comment]
I'm still undecided what would be best bheavior, I feel more comfortable having `embark-act` to act on the selection but as you describe the other behavior would be more in line what we do when exiting with RET. I have to experiment a bit and also think about how other solutions might come out of the general redesign of the crm UI.

**Comment by clemera** [comment]
@oantolin Maybe you meant that with the bug you mentioned above: With the current version you can't act on a single candidate (when no crm-separator is present yet).

**Comment by oantolin** [comment]
> @oantolin Maybe you meant that with the bug you mentioned above (though I doesn't sound like that): With the current version you can't act on a single candidate (when no crm-separator is present yet).

No, the bug is that I _always_ replace the last partially entered candidate with the selection, even if the selection is the input! So if you run, say `(completing-read-multiple "Buy: " '("eggs" "milk" "ham" "bread"))`, type `eggs,milk,b`  and then select the input and use `embark-act`, you might expect `embark-act` to recieve `eggs,milk,b` (or `maybe `eggs,milk,bread`), but instead it gets `eggs,milk,eggs,milk,b`, since it blindly replaces `b` with the selection `egg,milk,b`.

**Comment by oantolin** [comment]
> I was thinking of selecting the prompt after adding a candidate with TAB as you mentioned above that might feel right for crm even if we don't use that behavior in general.

I think I like that option, @clemera. Have Selectrum use "TAB inserts item _and_ selects the input" only for the crm case; and revert this change in Embark going back to just using `selectrum-get-current-candidate`. 

I don't think having TAB select the input in the crm case is inconvenient for Selectrum users. If they type more text the selection immediately move to the matching candidate. TAB does behave differently, since it just moves the selection to the first remaining candidate, but a second TAB inserts that. So, as far as I can tell the only difference between the current behavior and crm-TAB-selecting-the-input would be that sometimes users need to press TAB one more time.

**Comment by clemera** [comment]
I updated Selectrum to select the input line after candidate insertion for crm.

**Comment by oantolin** [comment]
Thanks, @clemera! I reverted the change I had made to Embark. I think it'll feel pretty natural to act on the whole multi-selection this way.

**Comment by oantolin** [comment]
Let us know what you think, @bdarcus.

**Comment by clemera** [comment]
>  I think it'll feel pretty natural to act on the whole multi-selection this way.

Yes, I think it was a good idea! It is also nice if you accidentally press TAB for the last candidate you want to add, now you can simply exit with RET afterwards, too.

**Comment by oantolin** [comment]
> Yes, I think it was a good idea! It is also nice if you accidentally press TAB for the last candidate you want to add, now you can simply exit with RET afterwards, too.

Oh, right! Before, in that situation, you'd have to delete the crm-separator  first and then press `RET`.

**Comment by bdarcus** [comment]
I use doom, and so ran `doom sync`, which updated selectrum, but not embark.

Maybe just some lag with melpa or something?

I'll report back when both updates are running.

**Comment by bdarcus** [comment]
Just a clarification:

If I run my command, I can select one candidate by hitting RET, but must first do TAB to do `embark-act`.

Is that expected?

**Comment by clemera** [comment]
It should work for single candidates using my earlier example I don't need to use TAB before:

```elisp
(defun check (target)
  (interactive "sCheck:")
  (message "%S" target))

(let ((embark-overriding-keymap '(keymap (?o . check))))     
  (completing-read-multiple "Test: "
                            '("testing" "with" "selectrum")))
```

**Comment by clemera** [comment]
Skimming through your code the problem might be that the handlers expect a list like returned from crm? Thinking about it it might make sense that `selectrum-get-current-candidate` returns a list like it would get returned by crm.

**Comment by oantolin** [comment]
> Skimming through your code the problem might be that the handlers expect a list like returned from crm? Thinking about it it might make sense that `selectrum-get-current-candidate` returns a list like it would get returned by crm.

This shouldn't be the problem: `embark-act` will get a string (crm-separated), inject it at the action's minibuffer prompt, and then the crm call in the action's `interactive` spec splits that to get a list, so the action's argument is correctly receives a list.

**Comment by clemera** [comment]
> This shouldn't be the problem: embark-act will get a string (crm-separated), inject it at the action's minibuffer prompt, and then the crm call in the action's interactive spec splits that to get a list, so the action's argument is correctly receives a list.

Thanks I was confused, embark should handle all the magic already :+1:

**Comment by oantolin** [comment]
I think @bdarcus may not have the version of Embark with the commit reverted. The reversion is on MELPA now. Maybe you can just update and try again, @bdarcus?

**Comment by bdarcus** [comment]
Will do.

**Comment by clemera** [comment]
This is another example why the injection approach embark uses has some nice practical advantages

**Comment by oantolin** [comment]
I tried bibtex-actions and here I was able to act on just one entry without pressing TAB first.

**Comment by bdarcus** [comment]
I thought you two might find this annexdote interesting, and to confirm the wisdom of this change.

The night before last I got my first bug report.

It took me awhile to realize it was actually this issue.

The user updated the packages, and is now happy.
