### ISSUE TITLE
FEATURE REQUEST: Automatically show embark-act menu commands upon invocation

### ISSUE THREAD

**Issue by rswgnu** [oantolin/embark#194]
I want a setting that automatically displays the active embark keymap whenever I invoke embark-act, so essentially what C-h does without the need to press that key.

I know about the which-key support which does something similar but would like to use regular completions instead so that they are potentially selectable with the mouse (I use Hyperbole's completion argument selection).

It would also be great to have a recipe that uses company-mode completion to show and select among possible actions or even a standard popup menu.

**Comment by oantolin** [comment]
> essentially what C-h does without the need to press that key.

If you want this you can set the variable `embark-prompter` to  `embark-completing-read-prompter`, which is listed as `Read action with completion` in the customize system.

**Comment by rswgnu** [comment]
Setting embark-prompter as you suggest is better as I can then press '?' to
see a list of completions after invoking embark-act.  However, it does not
display the list of completions/menu items until after I press '?'.  I want
it to appear right away after embark-act is called.  Thanks for your quick
responses.

**Comment by oantolin** [comment]
Ah, I see the issue. Since the `embark-completing-read-prompter` is meant for users of several completion frameworks, I think this is best solved by just adding advice that pops up the `*Completions*` buffer:

```elisp
(defun displaying-completions-automatically (fn &rest args)
  (minibuffer-with-setup-hook #'minibuffer-completion-help (apply fn args)))

(advice-add #'embark-completing-read-prompter
            :around #'displaying-completions-automatically)
```

Try that and let me know if meets your needs.

**Comment by oantolin** [comment]
You know, I think I might add advice like that to my personal configuration. (Except I'll use `embark-collect-completions` rather than `minibuffer-completion-help`.)

**Comment by rswgnu** [comment]
I will try it out later today and let you know.  I mostly have the Hyperbole completion issue solved as well, just a small issue to finish.

-- Bob

**Comment by rswgnu** [comment]
Yes, that works well.  Thanks.

I would consider making this the default so people get familiar with all of
their options when starting out and then can turn it off after they have
more experience, rather than the other way around.  For example, when I
first read about and then tried the package, I was very surprised to see
that there was no menu of actions that was displayed, only essentially key
bindings with completion.  UIs should be explicit by default and then less
explicit in expert mode.  See what others think.

**Comment by oantolin** [comment]
Well, in a sense, the completing-read prompter does present you a visible menu for most users! I think that most Embark users use some completion UI that automatically displays the completions. Probably Selectrum is the most popular one among Embark users, but some people use the built-in Icomplete ---and maybe a couple of people use `embark-collect-completions-after-delay`. If you use a completion UI like any of those, you do see the menu of actions automatically. 

People (like me) that stick to the default completion UI, where you need to request the completions, seem to be a minority now, and the default you suggest would only benefit this small minority of users. For anyone that uses a completion UI that does display completions by default, making `embark-completing-read-prompter` pop up the completions buffer would be super-annoying, which is why I wouldn't want it to be the default.

**Comment by rswgnu** [comment]
Fair enough.  Let’s talk about UIs then.  I use company-mode fairly extensively with popup frame completion.  Is there a company-embark interface that would trigger on embark-act execution?

Also, it seems like it would also be useful to have a normal popup menu if embark-act were invoked from a mouse click?

What are you thoughts on these?

I will have to look at selectrum, I haven’t yet.

-- Bob

**Comment by oantolin** [comment]
Both the company interface and a mouse popup are good ideas, and ideas that I probably never would have come up with myself, since I use neither company nor the mouse.

**Comment by oantolin** [comment]
By the way, Robert, have you tried this variant of the code I wrote above?

```elisp
(defun displaying-completions-automatically (fn &rest args)
  (minibuffer-with-setup-hook #'embark-collect-completions (apply fn args)))

(advice-add #'embark-completing-read-prompter
            :around #'displaying-completions-automatically)
```

I prefer it to the original version with `minibuffer-completion-help` because the Embark collect buffer automatically updates as you type text in the minibuffer. (You'll probably want to include at least one completion style that can match substrings to make this useful, for example you can add `substring` to `completion-styles`.)

**Comment by rswgnu** [comment]
Hi Omar:

Yes, I did test it out and it is nice.  It is similar to how company-mode
completion works but that can use a popup subframe at point that appears
while still completing and then disappears onces finished, so your window
configuration never changes.

**Comment by hmelman** [comment]
I'm not sure how these various work and look.  It would be great if the README or a wiki page showed these configuration options (including which-key) and an image of what they look like.

**Comment by oantolin** [comment]
@rswgnu The new `embark-verbose-indicator` is on by default, so now Embark does show what commands are available by default.

**Comment by rswgnu** [comment]
Great, thank you.
