### ISSUE TITLE
Dired export does not work with partial completion

### ISSUE THREAD

**Issue by minad** [oantolin/embark#198]
I thought that this worked at some point and dired could handle files originating from different locations. But it seems that it does not work anymore. I tested default completion, Selectrum and Vertico.

**Comment by oantolin** [comment]
It did use to work. :( Investigating...

**Comment by oantolin** [comment]
Odd, snapshot does work.

**Comment by oantolin** [comment]
The problem is `default-directory`. It's more complicated to guess the correct containing directory when using `partial-completion`.

**Comment by oantolin** [comment]
Argh, maybe I should change the protocol and have the candidate collectors return full candidates. Then in the dired exporter I can look for the longest common ancestor path and relativize the paths with respect to that.

**Comment by oantolin** [comment]
I decided instead to fix it by changing the `default-directory` computation to use the mythical "completion base position". Of course, this means computing all completions again, but since computing `default-directory` is not a frequent operation I think it's OK to take the performance hit (I don't notice it at all).

This should fix things for Vertico and Selectrum. It almost does too for default completion and icomplete: it fixes cases like `~/a/b` but still not cases like `~/path/~/starting/over/a/b`. I think I should probably just use `substitute-in-file-name` in the default completion minibuffer candidate collectors.

**Comment by oantolin** [comment]
Please test.

**Comment by minad** [comment]
Sounds good I will give it a test
