### ISSUE TITLE
Document the Embark calling convention in the README

### ISSUE THREAD

**Issue by minad** [oantolin/embark#235]
* For commands, the target is injected in the minibuffer
* The target is passed as first argument to unary functions

**Comment by minad** [comment]
The README contains these scattered sentences:

> you can use any command that reads from the minibuffer as an action and the target of the action will be inserted at the first minibuffer prompt. 

> You can customize what happens after the target is inserted at the minibuffer prompt of an action.

> You can customize what happens after the target is inserted at the minibuffer prompt of an action. There is a hook, embark-setup-hook, that is run by default after injecting the target into the minibuffer.

> By default, for most commands embark inserts the target of the action into the next minibuffer prompt and “presses RET” for you, accepting the target as is.

So it is not undocumented, but the function calling convention still is. I think it may be nice to have some section "How are actions called by Embark?" or "The Embark calling convention".

**Comment by hmelman** [comment]
Yes please.

**Comment by oantolin** [comment]
Yes, good idea. In general the manual seems to not be organized how people expect it to be. I've seen various comments about not having found things in there that are there (and, as you point out the non-command actions aren't there at all!).

**Comment by hmelman** [comment]
It's late here but I'll offer that looking at the README again, it is reasonably structured if you know what embark does.  But embark is an unusual emacs package in what it offers, there's no mode, it can be invoked at quite different times in the emacs infrastructure, it uses it's own terminology (eg target) etc.  It probably just needs a little more basic hand holding at the beginning and a few concrete examples of its different use cases.  It's quite remarkable that embark is flexible enough that experts of it are still finding powerful places to use it (e.g., as a M-. generalization).  If it have it right, I might include a sentence or two early on explaining that it started from being able to offer additional actions to consult commands and then got generalized.  That might help set context for people coming from other completion systems.

**Comment by oantolin** [comment]
> If it have it right, I might include a sentence or two early on explaining that it started from being able to offer additional actions to consult commands and then got generalized. That might help set context for people coming from other completion systems.

It's been a while, but I don't think that's the correct history. I think Embark is probably several months older than Consult. At any rate, I'm pretty sure _I_ didn't know about Consult, if it did exist, when I wrote the first version of Embark. The original motivation was to have something like Helm or Ivy actions, but for default completion (or Icomplete, I think maybe I was using Icomplete at the time and not yet just using default completion).

By the way, I thought Embark would be easy to understand because Helm and Ivy are so popular, but I've found that people that come to Embark didn't necessarily use either Helm or Ivy before, and that many users of them didn't actually use actions!

**Comment by minad** [comment]
Yes, Embark is older. I started with Consult without being really aware of Embark (I've seen it on the Selectrum README, but didn't use it). At that time I only wanted to collection of a few handy commands to augment Selectrum and didn't consider actions. It is good that both Embark and Consult are useful on their own, one does not have to use them together.

> ...didn't necessarily use either Helm or Ivy before, and that many users of them didn't actually use actions!

Indeed. This is a nice side effect of these decoupled packages. Since Embark is so focused on actions, the action feature cannot be missed by users - at least in the case where the user plugs the components together by hand in contrast to using an Emacs distribution. 

Probably in Ivy actions are more like an afterthought, but in Helm actions are very central from what I've understood? Wasn't the concept of "Anything" that anything is smashed together under a single `anything/helm` command and then you perform actions on the candidates?

**Comment by hmelman** [comment]
Thanks, that's interesting embark history.  So perhaps a sentence like, "The original motivation was to enable the use of multiple actions in completion systems other than ivy and helm and it grew a bit from there."

I was intrigued by the multi-action capability of helm and then ivy, but I rarely used them.  It's one of the reasons I was willing to try consult, that seemed like some bulk I could easily give up.  embark-collect-snapshot is my main use of embark and that's mostly the reason I see embark recommended, to enable ivy-occur like functionality in consult.  

Yes I think it's correct that actions were always pretty central in helm and added to ivy later to bring it closer to feature parity with helm.  For me, I just rarely start one command and want to perform a different action, instead I'd just start with the command that does that action.  I wonder if evil users get more use out of actions?

**Comment by minad** [comment]
@hmelman `embark-collect-*` was also a central functionality for me in the beginning. Note that one can instead invoke `minibuffer-completion-help` to get a buffer out of the completion system, but maybe not with the same sorting.

Actions are useful to me since they save keybindings and are like an ultimate dwim command at point. Click on something or give me a menu of possible options. The example of `bug-reference-mode` really shows that something like this is missing in Emacs. `bug-reference-mode` binds its `bug-reference-push-button` to `C-c RET` and mouse click. There are other modes which do something similar. But imo it does not make any sense at all that a mode binds a key for this. There are better solutions, in particular overlay keymaps or Embark!

@oantolin Btw, `embark-act-default` should be bound to some mouse event :D

**Comment by oantolin** [comment]
@hmelman 

> For me, I just rarely start one command and want to perform a different action, instead I'd just start with the command that does that action.

What about file management? I like that actions turn `find-file` into a mini file manager where you can delete, copy, or rename files, create directories, unzip an archive before opening one of its files, run `wc -l` on a file (for some reason I do this fairly often). Dired started feeling "heavy weight" or "for advanced usage" to me after I got used to using file actions in Helm (and later Ivy/Counsel). When I stopped using Ivy I made a prefix map with bindings for `copy-file`, `delete-file`, `make-directory`, etc.; but having to think ahead about which command I needed didn't really fit my brain. I wanted to see a list of the files first, narrow it down, and then choose the operation. I mean, I did eventually get used to running all those files commands, but once I wrote embark I never ran them directly again!

@minad I'll look into the mouse idea anyway. Maybe it's not so complicated.

**Comment by minad** [comment]
@oantolin

> I'll look into the mouse idea anyway. Maybe it's not so complicated.

Oh no, I think it is some kind of over kill. It will affect all target finders since one has to look for the event and then compute the point position etc. If you really want to have this, I would probably try to write some kind of `embark--event-point` function (mouse position or point) or even pass the "event point" to the target finder directly.

**Comment by hmelman** [comment]
@minad I have started playing with `bug-reference-mode` today.  I just got to the `C-c RET` binding and completely agree with you.  I'm also wondering why it doesn't just use an actual button rather than copying from button.el.  I'm not using Emacs 28 but I see last summer it got a feature to enable auto-config of bug-reference based on vc settings.  That's kinda neat but seems limiting to me.  Source files reference bugs in *other* packages all the time.  E.g., my emacs config files reference emacs bugs and consult bugs and it seems I want a local registry configured to apply that mapping in all files (and it would be great if source files used file-local variables to define their own uses since I install packages with the package manager and not git).

@oantolin I can see the mini file manager use case, but I haven't need it.  I have `dired-jump` bound to `C-x C-j` and quickly go into dired when I need to do something with the current file (and then return to where I was by killing the dired buffer).  I haven't ever felt the need to do that from the `find-file` prompt.  BTW I also have `C-x j` bound to my own command `reveal-in-finder` to open in the mac's file manager, I use that very rarely.

**Comment by minad** [comment]
@hmelman A button would not make sense for `bug-reference-mode` since you don't want to use RET to trigger the action? But maybe more code of button.el could be reused? 

> ...consult bugs...

I don't know what you are talking about ;)

The mini file manager, which @oantolin mentioned, is indeed a great use case, in particular in combination with Marginalia. I also like the Hyperbole-like button functionality of Embark now (bug-reference-mode, defining custom action buttons). Also context specific commands if regions are activated, there are many use cases for context sensitive keybindings. I think it is a powerful idea, but one can use it step by step if desired. It is also good for exposing/exploration, since you can trigger `embark-act` and check for the actions which make sense at the current point.

**Comment by hmelman** [comment]
> A button would not make sense for `bug-reference-mode` since you don't want to use RET to trigger the action? 

I think I mostly do want RET to trigger the action.  bug-reference could use it's own keymap if necessary.  The default one also adds button-next/previous bindings which I think could be useful in this context (I use similar functionality via `symbol-overlay` all the time now).

> > ...consult bugs...
> 
> I don't know what you are talking about ;)

I thought that might be confusing ;)

> The mini file manager, which @oantolin mentioned, is indeed a great use case, in particular in combination with Marginalia. 

I do love seeing heavy-annotations files though I don't really use them.  If I'm opening a file, I don't care about it's owner or size or permissions.  With consult-buffer I do look at modes and full paths to help me choose the right buffer (and would love to be able to filter on the mode).  But what's a concrete example of something you do with this mini file manager?  I could see wanting `copy-file` from `find-file`, but I just open the file and use `C-x C-w` to write (or rename) it where I want.

> I also like the Hyperbole-like button functionality of Embark now (bug-reference-mode, defining custom action buttons). 

I agree that's interesting.  I still haven't given hyperbole another try.  I agree that emacs could benefit from a standard binding to do some context specific action at point and that `M-RET` or `C-c RET` are viable choices.  I do really like that embark could be fulfilling this role.

(I also think emacs should standardize the meta arrow keys to move things around in relevant modes like org, markdown and now outline-minor-mode, but lost that battle on emacs-devel.)

> Also context specific commands if regions are activated, there are many use cases for context sensitive keybindings. 

A few months ago I updated the default action page on the embark wiki and specifically looked at the region commands since they seemed useful (eval, indent, comment, case changes).  But I haven't found myself using them over the standard bindings for these commands and quick access that transient-mark-mode brings to things like the case commands.  What specific ones do you use?  And if you've added more to the `embark-region-map` I'd be very interested in knowing what.

I would absolutely use region commands that sent region to various search engines like google, wikipedia, imdb, maps, etc.  but I have system-wide commands that do this on my mac (via the app Alfred) that work with the emacs macport.

> I think it is a powerful idea, but one can use it step by step if desired. It is also good for exposing/exploration, since you can trigger `embark-act` and check for the actions which make sense at the current point.

Yes I totally agree with this.  My original motivation for such features in the 90s was wanting to not just click on URLs to open them but also to easily copy them to the kill-ring to yank somewhere.  Similarly for email addresses and bug numbers.  Embark is definitely the best implementation of this I've seen thus far.

**Comment by oantolin** [comment]
The region actions I use are: `eval-region`, `transpose-regions`, `whitespace-cleanup-region`, `org-table-convert-region`, `rot13-region` and `apply-macro-to-region-lines`. The first five of those do not have default key bindings and the last one has one I find awkward. I use `apply-macro-to-region-lines` _way_ more now that it is in the embark region map ---and it's a good habit to get into because running a keyboard macro on each line is much, much faster with this command than by including a motion to the next line in the macro and repeating it.

From a quick glance at the region actions (a nicely formatted grid view of which I obtained, of course, by marking a region and then typing `C-; C-h C-; S` :wink:), I don't think any of the others are really that useful, since, as you mentioned, there are commands for most of those that act on the region when active.

**Comment by oantolin** [comment]
I think I don't have very convincing examples of using `find-file` as a mini file manager. Certainly if you are in the habit of using `dired-jump` for a quick file operation and then killing the dired buffer, using `find-file` + embark is about the same number of keystrokes and you lose some of the power of dired. I think I just like the immediacy of the minibuffer for a quick file operation: it feels like less of a context switch than opening dired.

The result for me is that I don't open dired for basic single-file operations any more. I still use dired for acting on collections of files, but I abandoned my old work flow to focus on a subset of files: I'd open dired, mark files with a regexp, toggle the marked files and then kill them. I now find it much more convenient to use `find-file` and orderless to narrow to the files I want and then use `embark-export`. Narrowing with orderless is much more fun than marking files in dired.

**Comment by hmelman** [comment]
Thanks for both of those answers.  I have eval-region on `C-c r` and will try using it from embark.  The others I don't use much or didn't know about.  `whitespace-cleanup-region` is perhaps useful to me but it seems I'll have to spend some time configuring `whitespce-style` in different modes.  I use macros a lot and include motion in them; I've heard about `apply-macro-to-region-lines` but didn't see the need, I'll give it a try.

On your `find-file` answer I was perfectly willing to chalk up your first paragraph as just differences in preferences, an emacs staple :)  But the second paragraph I found very interesting and I hadn't considered.  Mostly I thought of using the embark file commands on individual files, but the notion of using narrowing in completion instead of dired marking is compelling and wasn't an obvious use case to me (and I still have to try orderless).  It's instances like this where I find actually asking for specifics, often enlightening. :)

So I used `find-file`, narrowed some files down (using selectrum) and then did `embark-export` (`s-; E` for me).  I ended up with an embark collect buffer, the same as when I do `embark-collect-snapshot`.  Shouldn't the export have opened a `dired` buffer?  Also I just now learned about `embark-collect-direct-action-minor-mode` but it doesn't seem to be working for me.  If I enable it here, `d` doesn't get bound to `delete-file`, shouldn't it?  And this minor mode should be mentioned in the README. :)

**Comment by oantolin** [comment]
> Shouldn't the export have opened a `dired` buffer?

Yes, it should have!

> Also I just now learned about embark-collect-direct-action-minor-mode but it doesn't seem to be working for me. If I enable it here, d doesn't get bound to delete-file, shouldn't it?

Again, yes it should. I wonder what's going on in your configuration.

Mmh. It seems like somehow embark either (1) didn't know you were dealing with files or (2) didn't know what to do with files. Both seem unlikely: for (1), `find-file` definitely reports the `file` completion category; and for (2) the default configuration includes file actions and an exporter.

You could check to make sure `(file . embark-file-map)` is present in `embark-keymap-alist`; and that `(file . embark-export-dired)` is present in `embark-exporters-alist`. You could also check whether you get offered file actions from `find-file`.

**Comment by hmelman** [comment]
I do get offered embarks file actions from find-file.  Those values are present.

embark-keymap-alist
((hrm-note . hrm-notes-map) (file . embark-file-map) (environment-variables . embark-file-map) (url . embark-url-map) (buffer . embark-buffer-map) (identifier . embark-identifier-map) (symbol . embark-symbol-map) (command . embark-command-map) (variable . embark-variable-map) (minor-mode . embark-command-map) (unicode-name . embark-unicode-name-map) (package . embark-package-map) (bookmark . embark-bookmark-map) (region . embark-region-map))

embark-exporters-alist
((consult-grep . embark-consult-export-grep) (consult-location . embark-consult-export-occur) (hrm-note . embark-export-dired) (buffer . embark-export-ibuffer) (file . embark-export-dired) (package . embark-export-list-packages) (bookmark . embark-export-bookmarks) (t . embark-collect-snapshot))

**Comment by oantolin** [comment]
This is bizarre! Do your hrm-notes export correctly to a dired buffer?

**Comment by hmelman** [comment]
Yes.  Also buffers go to ibuffer.

**Comment by hmelman** [comment]
My embark config:

``` elisp
(require 'embark-consult)   ; this requires both embark and consult

(global-set-key (kbd "s-;") 'embark-act) ; was s-/, C-; is used for flyspell
(global-set-key (kbd "H-/") 'embark-default-action) ; I Feel Lucky or on M-.
(global-set-key (kbd "C-h B") 'embark-bindings)
(define-key selectrum-minibuffer-map (kbd "C-o") #'embark-collect-snapshot)
;; FYI, embark-live-occur is unnecessary with selectrum
(define-key embark-general-map (kbd "M") #'marginalia-cycle)
(define-key embark-collect-mode-map (kbd "s-y") #'consult-preview-at-point)
;; Not sure if this is viable with selectrum:
;; Hook embark-collect-completions-after-delay or embark-collect-completions-after-input to minibuffer-setup.
;; or bind embark-collect-completions to a key


(setq prefix-help-command #'embark-prefix-help-command)

;; Use which-key to show embark keymaps immediately
(setq embark-action-indicator
      (lambda (map &optional _target)
        (which-key--show-keymap "Embark" map nil nil 'no-paging)
        #'which-key--hide-popup-ignore-command)
      embark-become-indicator embark-action-indicator)

;;;; Ideas from https://github.com/oantolin/embark/wiki/Additional-Configuration
;; This refreshes a candidate list in selectrum in case an embark action has changed it
(defun refresh-selectrum ()
  (setq selectrum--previous-input-string nil))
(add-hook 'embark-pre-action-hook #'refresh-selectrum)
(add-hook 'embark-post-action-hook #'embark-collect--update-linked) ; same for embark live occur buffers
```

**Comment by oantolin** [comment]
I couldn't reproduce the problem on Emacs 28. I prepended this to your config and loaded it in `emacs -Q`:

```elisp
(package-initialize)
(require 'selectrum)
(selectrum-mode)
(require 'which-key)
```

**Comment by hmelman** [comment]
Ok, this is fun.  It works find (goes to dired) if my input is "hrm-" or "hrm- el" but it fails as described above if the input is "hrm- el$"  I'm briefly stepping through with edebug and saw this was being recognized as an environment variable.

**Comment by oantolin** [comment]
Oh! You ran across a little known feature: the built-in file completion table supports interpolating environment variables. So a path like `~/$VAR/file1.txt` will refer to the directory stored in environment variable `VAR`. Plus when you type the `$` you switch from file name completion to environment variable name completion. I think Selectrum only does the `$` completion if the `$` comes right after a `/`, which is why you probably hadn't noticed it. More "Emacs API compliant" completion UIs (I mean Vertico, default completion, icomplete, embark-collect-{live,completions}) will enter variable name completion also for your `el$` case, making it obvious what's going on.

I think you can probably use `\'` instead of `$`, or add another space at the end: `el$ `.

By the way, years ago I actually tried using this environment variable feature as a way to define "bookmarks" for directories that I could use from both Emacs and the shell. I had `ORG = ~/Dropbox/OrgNotes`, for example. Nowadays I don't use a shell anymore so I just use Emacs bookmarks.

**Comment by oantolin** [comment]
That's a quick way to get a nice display of all your environment variables and their values by the way: run `find-file`, type `$`, do `embark-collect-snapshot`. 😄

**Comment by hmelman** [comment]
So both your workarounds "hrm- el$ " and "hrm- el\\'" do yield dired buffers, but they are rooted at the top of the my drive, `/:` (I'm on a mac) and not the selected files.

**Comment by hmelman** [comment]
So the emacs manual say the way to include a $ is to type $$ which works.  And there doesn't seem to be a configuration option to disable env var expansion in file names.  So now my problem is just getting the resulting dired buffer to contain the selected files when doing this.

**Comment by oantolin** [comment]
Mmh. Curious. What were you using before activating orderless? Prescient? Or just Selectrum with the built-in completion styles?

**Comment by hmelman** [comment]
selectrum with prescient

**Comment by oantolin** [comment]
Maybe this will be the day I finally install Prescient, then.

**Comment by hmelman** [comment]
OFF TOPIC: Hints on orderless config are welcome :)  (I'm reading the README now) One thing that was frustrating me with selectrum/prescient (which otherwise worked pretty well for me) is sorting of elisp files.  In my personal config directory (~/elisp/) my .el files were sorted above .elc versions which is great.  But in the emacs distribution directories .elc files were sorted above .el.gz which was annoying.

**Comment by oantolin** [comment]
I can reproduce the problem! It was prescient! (I first tried selectrum with built-in completion styles and things seemed to work as expect, but of course, the built-in style don't include regexp matching.) Will debug now.

**Comment by oantolin** [comment]
Seems to be that the default-directory guessing isn't working under prescient...

**Comment by hmelman** [comment]
Sorry, I can't help much here.  The way that selectrum, prescient, and orderless combine is still kind of a mystery to me (one of the downsides of decoupled projects).  Happy to test anything or debug with a little guidance.

**Comment by oantolin** [comment]
Oh, don't worry: now that I finally installed prescient I can debug this myself (then I'll probably uninstall prescient until the next bug report ---that's what I do with which-key, for example 😛).

**Comment by minad** [comment]
I recommend to use Orderless only and rely on the default sorting by history position (recency) as offered by Vertico and Emacs 28 default completion ootb. Selectrum also sorts by recency ootb, but the support for files is not yet implemented (https://github.com/raxod502/selectrum/issues/502).

**Comment by oantolin** [comment]
I think I fixed the problem with prescient. But of course, I also recommend orderless. 😛

**Comment by minad** [comment]
I must say I am getting annoyed by Prescient. Is https://github.com/oantolin/embark/commit/ef609bf15368a68c4eb3c46fd8cc1bb623b6b83e a reasonable thing to do? Note that my affe package also does not work with Prescient, since it would require a Prescient-specific workaround. Because of Prescient I need this filter advice in Consult (https://github.com/minad/consult/blob/ae905501bcdb8fdda0d10a0846d575fd2a38e6d7/consult-selectrum.el#L37-L53). I am considering to print a warning in case a non-completion-style filter is detected in Selectrum. And maybe even drop support for non-completion style filters later, i.e., dropping Prescient filtering support as long as Prescient does not provide a completion style (https://github.com/raxod502/prescient.el/issues/89).

**Comment by oantolin** [comment]
>  Is ef609bf a reasonable thing to do?

I think so. It also helps in case there are genuinely no matches, like `~/a/real/directory/non-exisisting-file`. Before the commit, the default-directory was guessed as `~/a/real/directory/non-exisisting-file` and now or is guessed as `~/a/real/directory`.

**Comment by hmelman** [comment]
I can confirm the fix :)  Thanks.  Following up on this:

> One thing that was frustrating me with selectrum/prescient (which otherwise worked pretty well for me) is sorting of elisp files. In my personal config directory (~/elisp/) my .el files were sorted above .elc versions which is great. But in the emacs distribution directories .elc files were sorted above .el.gz which was annoying.

Any suggestions on where to fix this?  I looked at emacs completion and find-file options and didn't find a way to prefer one over the  other or to ignore .elc files in find-file (which I kinda feel there must be).  I rarely want to open a .elc so I guess I'd be ok with a solution that removed them from the completion table, but I'd rather sort them below the others.   

Currently I:
```elisp
(setq prescient-sort-length-enable nil)
(setq prescient-sort-full-matches-first t)
```
but changing these values didn't help much.  Relying on length of ".el" vs ".elc" vs ".el.gz" isn't a robust solution.  If its sorting then I guess that prescient and perhaps selectrum and orderless doesn't get involved at all right?

**Comment by minad** [comment]
You can ignore files with completion-ignored-extensions. This works at least in Vertico+Orderless. Selectrum does not yet support this option afaik.

**Comment by hmelman** [comment]
Thanks, the advice I found in [Selectrum issue #17](https://github.com/raxod502/selectrum/issues/172) helped.

**Comment by minad** [comment]
See https://github.com/oantolin/embark/wiki/How-does-Embark-call-actions%3F
