### ISSUE TITLE
What does <region> mean? Region calling convention?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#247]
The region commands are a bit special since they use yet another calling convention - they don't rely on minibuffer injection but rely on the target at point. The same applies to potential sexp and defun target finders.

**Comment by minad** [comment]
I also wonder what the best approach is to implement sexp commands at point, where the point is either before the sexp or after the sexp - ideally without replicating every command :)

**Comment by oantolin** [comment]
The commands bounds in `embark-region-map` don't need anything injected at the minibuffer prompt (and most don't even use the minibuffer). So I needed to signal that nothing should be injected (for the few that maybe do use the minibuffer). An empty string would work since it is harmless to inject one. That felt a little hacky, so I decided to go with `nil` instead (the injection code only injects if the target is a string). But then I realized that if I used the _symbol_ `<region>`, the message in the echo area was nicer: "Act on <region>", rather than "Act on ''" (for the empty string) or "Act on 'nil'".

So I think technically it's not really a different calling convention. 😛 It still goes through "if the target is a string, then inject it at the first minibuffer prompt".

For the rare case were you want to do something to the contents of the region, the `embark-act-on-region-contents` command reruns `embark-act` with the target finders locally set to just return (and attempt to calssify) the region contents.

**Comment by minad** [comment]
Makes sense, thanks for the details. I had missed that only strings are injected - good to know!

Any ideas about how we should go with the sexps/defuns at point? Nothing is to be injected in these cases, but creating some symbol for nicer action indicator messages is a bit ugly.

**Comment by oantolin** [comment]
Well, ugly indicator messages are ugly too. I guess we could just use `nil` and have the indicator be `Act on ... something, not quite sure what" in that case. 😛

**Comment by minad** [comment]
Using `<defun>` and `<sexp>` symbols will of course work too. What I meant is this - what could we do if we want a more specific indicator message, e.g., `Act on (defun foo)` for example?

**Comment by oantolin** [comment]
Ah, I see. Well, we could certainly make a symbol with that name. 😬 Or maybe the calling convention could also refrain from injecting string with a `no-inject` property...

**Comment by oantolin** [comment]
Wait, I'm an idiot, we can use the list `'(defun foo)`, that's not a string either.

**Comment by minad** [comment]
Haha, okay right. We can use any other object which will printed nicely but won't be injected magically.
