### ISSUE TITLE
Using `embark-export` buffers as "thing managers" doesn't work for `file` and `bookmark` buffers

### ISSUE THREAD

**Issue by iyefrat** [oantolin/embark#254]
I really like the following workflow with `consult-grep`:
+ I want to look around all instances of `foo` in some project
+ I do `consult-grep RET foo [embark-export]`
+ I now can use the exported buffer as a way to quickly navigate between all `foo` instances, since the buffers get opened in the other window

This is in a way similar to the "thing manager" workflow discussed in the readme, with the added benefit of being able to keep the buffer around for as long as you want. This works for `package` category buffers as well. I'd like to use this type of thing for `projectile-find-file` or `bookmark-jump` too, but the exported buffers there don't behave as well as I'd like them to.

The exported `projectile-find-file` buffer is just a regular `dired` buffer, which means that it opens the files in the same window, instead of in the other window, which limits it's usefulness as a "thing manager" (i.e., a temporary and pointed `treemacs` type thing).

This is the same behavior for `bookmark-jump`, where it opens the bookmark buffer in the same window as the `embark-export` buffer, instead of in the other one.

What are your thoughts on the subject?

**Comment by oantolin** [comment]
Mmh. In a sense there isn't really anything Embark should do about this, since after you run embark-export, Embark isn't involved anymore: then you are simply using dired or the bookmark list buffer. Both those buffers have `o` bound to a command that visits the file or bookmark in another window, so you could use that.

I guess you could also set up things so that in these embark export buffers `RET` is rebound to the command that visits things in another window. This could be done by advising the respective export functions:

```elisp
(define-minor-mode dired-other-window-mode
  "A minor mode for dired to have RET visit files in another window."
  :keymap '(keymap (13 . dired-find-file-other-window)
                   (?o . dired-find-file)))

(advice-add 'embark-export-dired :after #'dired-other-window-mode)
```

The analogous thing for bookmarks is left as an exercise to the reader. 😛

**Comment by oantolin** [comment]
I think I'll close this, since it's really a question about dired and bookmark-menu-mode, not about Embark. I hope the solution indicated above is good enough, too.

**Comment by iyefrat** [comment]
@oantolin Ah, that basically solves my issue. Thanks!
