### ISSUE TITLE
Q: how to use same actions in buffer and minibuffer with multiple selections?

### ISSUE THREAD

**Issue by bdarcus** [oantolin/embark#256]
We recently merged embark at-point support:

https://github.com/bdarcus/bibtex-actions/pull/143

But it has a limitation: one has to choose whether to use `embark-dwim` or `embark-act` at point.

https://github.com/bdarcus/bibtex-actions/issues/164

I really would rather not have that limitation.

I want to have two keymaps, where one has a subset of the same commands in the other, available at-point.

Is there any way to do this?

Solutions we rejected:

1. adding a parallel set of non-interactive functions for at-point
2. in general, using different function in buffer and in minibuffer

A solution I am wondering about, but not sure if it's even possible:

- removing the interactive commands and only using non-interactive functions; https://github.com/bdarcus/bibtex-actions/issues/170

**Comment by minad** [comment]
I am a bit confused by the `bibtex-actions-at-point` you added. Why is this function even needed? Ideally bibtex-actions would register its bibtex keymap with Embark and its bibtex target finder. Then you will get Embark actions at point via embark-act/embark-dwim without a separate `bibtex-actions-at-point` command, which requires a separate keybinding.

**Comment by oantolin** [comment]
I was going to ask the same thing as @minad.

**Comment by bdarcus** [comment]
TBH, I don't know. I didn't write that code, and (long story) merged it before I had time to fully understand it.

It could be because there was some value in wrapping the corresponding bibtex-completion-at-point function?

cc @ilupin (the author)

In any case, I don't have a problem removing it if that helps gets this working correctly :-)

**Comment by bdarcus** [comment]
OK, I opened a branch/PR that starts with where I think @ilupin ran into problems that resulted in the additional code.

https://github.com/bdarcus/bibtex-actions/pull/171

Apologies for the spurious CI flags.

Is there a way to fix the state it's in there, where `embark-act` at-point will not pass the keys to the commands and run them?

**Comment by bdarcus** [comment]
I dunno; reading this comment from Omar again, it sounds again like this is just not possible.

https://github.com/bdarcus/bibtex-actions/pull/143#issuecomment-860988893

... and that the only way to get the functionality across buffer and minibuffer is to use two different sets of functions that do the exact same thing; one set interactive, and the other not.  

- bibtex-actions: minibuffer
- bibtex-completions: buffer

This is what @ilupin had in an earlier iteration of that PR branch.

Which is just odd in general, and in particular from a UX perspective.

IUC, however, this limitation can't really be fixed, because of the way Embark does its magic.

But then maybe we can hide that discrepancy behind simple menu descriptions, which can be consistent.

But doing that introduces menu inconsistencies between those descriptions, and the general embark commands (which would be less of an issue if submenus worked).

So then maybe we should include the general Embark map, or a subset of it, with descriptions.

That's what I'm concluding ATM. Does that make sense?

**Comment by ilupin** [comment]
> I am a bit confused by the `bibtex-actions-at-point` you added. Why is this function even needed? 

`bibtex-actions-at-point` is used as an entrypoint for accessing bibtex entries. It uses embark to provide multiple actions for citation keys at point, and falls back to `bibtex-actions-read` if no key is found.

> Ideally bibtex-actions would register its bibtex keymap with Embark and its bibtex target finder. Then you will get Embark actions at point via embark-act/embark-dwim without a separate `bibtex-actions-at-point` command, which requires a separate keybinding.

> I was going to ask the same thing as @minad.

We cannot find a way to make `bibtex-actions-*` (or `bibtex-completion-*`) work as embark actions in both minibuffer and regular buffers.

`bibtex-completion-*` are functions from upstream package, and they cannot be directly used as embark actions in the minibuffer. `bibtex-actions-*`, wrappers of `bibtex-completion-*`, works in the minibuffer, but they don't work in regular buffers because embark doesn't pass the target at point (i.e. citation keys) to them.

Maybe we should rewrite `bibtex-actions-*` to make them compatible with embark, but it is more simple to force embark pass the target to `bibtex-actions-*` when needed, e.g. inside `bibtex-actions-at-point`.

**Comment by minad** [comment]
@ilupin 

> bibtex-completion-* are functions from upstream package, and they cannot be directly used as embark actions in the minibuffer. bibtex-actions-*, wrappers of bibtex-completion-*, works in the minibuffer, but they don't work in regular buffers because embark doesn't pass the target at point (i.e. citation keys) to them.

This does not sound right. I am sure you can make `embark-actions-*` functions work at point and in the minibuffer such that Embark passes the target to the function in both cases. If this is not possible something is wrong with Embark. You should not use the `embark-collections-*` functions at all as actions here, they are purely for the backend.

I will try to write a quick snippet in a minute to check that you can reuse actions at point/in the minibuffer. That is the whole point of Embark that you can reuse these things.

> bibtex-actions-at-point is used as an entrypoint for accessing bibtex entries. It uses embark to provide multiple actions for citation keys at point, and falls back to bibtex-actions-read if no key is found.

Of course you can write such a function which tries Embark first and otherwise falls back to `bibtex-actions-read`. This is very similar to how `xref-find-definitions` works for example. It checks at point and otherwise it falls back to `completing-read`. But if you want this behavior you don't really need Embark. I assume you also want to have the action menu which Embark offers?

I would not provide such a command, which tries Embark first and then falls back to `bibtex-actions-read`. This misses somehow the point of Embark since:

1. This `bibtex-actions-at-point` command needs an extra keybinding (instead of just reusing the `embark-act` binding)
2. Or you only bind `bibtex-action-at-point` instead of `embark-act` to the Embark key but this singles out bibtex objects as a special default target. I think such a special function should be written on the level of the user configuration. I am using for example `dm/embark-dwim`, which falls back to `xref-find-defintions` by default, since I am overwriting the `M-.` keybinding. But after having used this for a while it starts to feel odd. I would rather not open the `xref-find-definitions` completion UI but prefer the message "No target found" if there is no target at point.

~~~ elisp
  (defun dm/embark-dwim (&optional arg)
    (interactive "P")
    (if (or arg (not (embark--target)))
        (call-interactively #'xref-find-definitions)
      (embark-dwim)))
~~~

**Comment by minad** [comment]
Okay, I understood now the problem you are facing - the citation key target finder returns multiple citation keys at point. Unfortunately this is not yet supported by Embark. Embark only knows how to act on single string candidates (https://github.com/oantolin/embark/issues/166). If your target finder returns a single key, it should work for now. Since you are using CRM, your target finder could also return the candidates as a single string separated by `crm-separator`. But then you must ensure that every action you are using can handle these `crm-separator` concatenated candidates.

~~~ elisp
(defun bibtex-actions-citation-key-at-point ()
  "Return citation keys at point as a list for `embark'."
  (when-let ((key (or (bibtex-actions-get-key-org-cite)
                      (bibtex-completion-key-at-point))))
    (cons 'citation-key (if (listp key) key (list key))))) ;; returns multiple keys, should return a string instead
~~~

Furthermore there is the issue that Embark target in the minibuffer does not take the selected items into account and only returns the currently highlighted candidate.

I think in order to solve this properly Embark should get proper support for multiple candidates:

1. Embark target finders should be allowed to return lists. Each element of the list is a candidate. In particular Embark should add a target finder which works with `completing-read-multiple` and returns a list of all the selected candidates.
2. Embark should act on such list target candidates one by one in a loop, if the action is a single-action (all current actions are single actions!).
3. Furthermore there should be the notion of a multi-action. If an action uses `completing-read-multiple`, Embark should inject all candidates at once separated by `crm-separator`. Maybe it is possible to auto-detect `completing-read-multiple` in the Embark target injector.

Unfortunately `embark--act` (https://github.com/oantolin/embark/blob/acbe1cba548832d295449da348719f69b9685c6f/embark.el#L798-L863) is already pretty complicated, so I am not sure how easy it would be to implement this.

**Comment by bdarcus** [comment]
Thank you for confirming this @minad!

So the longer term Embark enhancements you suggest are consistent with where we were ending up with the "simple-crm" discussion. That's good.

I guess my wonder is about the best short-term approach.

On this:

> Since you are using CRM, your target finder could also return the candidates as a single string separated by crm-separator.

... there's not really any problem.with doing this as a stopgap; right?

As in, this is a reasonable stop gap that will at least get things working as they should from a user POV, and then if and when Embark is enhanced for better multiple support, we can then simplify that target finder?

The other alternative is to only work on an individual key, but that would mean more limited functionality now.

FWIW, it's my highest priority to get org-cite support (just mainlined this morning) working as well as possible. There the target finder is really easy and flexible, given org-element.

**Comment by minad** [comment]
> So the longer term Embark enhancements you suggest are consistent with where we were ending up with the "simple-crm" discussion. That's good.

Yes. But of course someone has to implement this in Embark :)

> As in, this is a reasonable stop gap that will at least get things working as they should from a user POV, and then if and when Embark is enhanced for better multiple support, we can then simplify that target finder?

Yes, this would work as a stop gap.

> The other alternative is to only work on an individual key, but that would mean more limited functionality now.

This would have been my first step, since Embark is currently entrenched to only handle single candidates. I don't know if multiple citations are actually that useful. Usually I want to open a single reference etc.

Even when the org-cite/latex syntax supports multiple citations as one `\cite{ref1,ref2,ref3}`, you could still only target the exact `refn` where the cursor is located.

**Comment by bdarcus** [comment]
> This would have been my first step, since Embark is currently entrenched to only handle single candidates. I don't know if multiple citations are actually that useful.

That's a good point.

I think only-keys but everything working correctly is more important than multi.

If I can't get the CRM-string approach working, I will probably do that.

**Comment by bdarcus** [comment]
> If I can't get the CRM-string approach working, I will probably do that.

So this doesn't appear to work (note I tried it also with the crm-separator I am using in bibtex-actions-read, &, but with the same result).

``` elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  regexp-quote(nil)
  bibtex-completion-get-entry1(nil)
  bibtex-completion-get-entry(nil)
  bibtex-completion-open-url-or-doi((nil))
  bibtex-completion-open-pdf((nil) bibtex-completion-open-url-or-doi)
  bibtex-completion-open-any((nil))
  bibtex-actions-open((nil))
  funcall-interactively(bibtex-actions-open (nil))
  command-execute(bibtex-actions-open)
  #f(compiled-function () #<bytecode 0x11e8052d3efee9f9>)()
  embark--act(bibtex-actions-open "low2001,mcneill2011" t)
  embark-act(nil)
  funcall-interactively(embark-act nil)
  command-execute(embark-act)
```

**Comment by bdarcus** [comment]
I experimented with modifying my code to only select one key (if there are more than one, just take the car), but that doesn't work either, whether I pass a string, or a list.

**Comment by minad** [comment]
This simple snippet works as expected with default `completing-read-multiple` and `consult-completing-read-multiple`.

~~~ elisp
(defun items-at-point ()
  (cons 'items "item1&item2&item3"))

(defun items-select (items)
  (interactive
   (list
    (let ((crm-separator "[ \t]*&[ \t]*"))
      (completing-read-multiple "Items: " '(first second third)))))
  (message "Selected %S" items))

(defvar items-map
  (let ((map (make-sparse-keymap)))
    (define-key map "\r" #'items-select)
    map))

(add-to-list 'embark-target-finders #'items-at-point)
(add-to-list 'embark-keymap-alist '(items . items-map))
~~~

**Comment by oantolin** [comment]
Sorry, I haven't been following the extensive discussion here, but let me quickly point out something (which you maybe clarified already, and I apologize if you did):

> Embark only knows how to act on single string candidates.

That's not exactly true. Target finders can return any type at all, including lists. There are two types of actions: commands and non-command functions (which I'll just call "functions" for brevity). What embark-act does depends on the type of action and the type of target:

- Action is a command, target is a string: the action is run interactively and the target is injected at the fist minibuffer prompt.
- Action is a command, target is not a string: the action is run interactively, the target is ignored.
- Action is a function, target is anything at all: the action is called (non-ineractively) with the target as argument.

If I understand correctly there are the bibtex-completions *functions* and for each one a corresponding *command* in bibtex-actions.  If that's the case, then the *functions* in bibtex-completions can be used directly as actions if you write a target finder that returns a list of bibliography keys.

So for just actions at point in non-minibuffers, all that's needed are a target finder returning a list of references and a keymap with the bibtex-completions *functions* in it. You would run these actions with the `embark-act` and `embark-dwim` commands.

If you wanted a single-entry point style minibuffer interface, like that of helm-bibtex and ivy-bibtex, you could in fact dispense with the *commands* in bibtex-actions and just reuse the hypothetical keymap from the previous paragraph. You would need to write one new command say `bibtex-actions-dashboard` that prompted for a multiple selections of bibliography items and you would need a target finder that detects if you are running `bibtex-actions-dashboard` and returns a the list of references corresponding to the selected items.

The *commads* currently in bibtex-actions are there to present a multiple-entry point UI for the minibuffer functionality, if multiple entry points are not required, the *functions* from bibtex-completions can be used as actions directly.

**Comment by minad** [comment]
Yes, you are right. One can write a target finder returning a *list* in combination with an action *function*. And as in my https://github.com/oantolin/embark/issues/256#issuecomment-877521614, one can write a target finder returning a crm-ified *string* in combination with an action crm *command*.

But I wouldn't call this good semantics! There is no bridge between targets/actions for single candidates and targets/actions on multiple candidates.

**Comment by oantolin** [comment]
How about adding one case to `embark-act`?

- Action is a command, target is a list of strings: run action interactively, join the elements of the target with some `embark-crm-separator` string, and inject that at the first minibuffer prompt.

Or, more generally, adding a defcustom `embark-stringifier-alist`, and replace all the "action is a command" cases with this single case: if the action is a command, lookup the target type in `embark-stringifier-alist`, funcall the resulting stringifier on the target and, if the result is a string, inject that at the first minibuffer prompt.

**Comment by minad** [comment]
> Action is a command, target is a list of strings: run action interactively, join the elements of the target with some embark-crm-separator string, and inject that at the first minibuffer prompt.

I don't think this is very useful, since there are nearly no crm-commands. I think it would be much better to treat actions as taking a single argument and call them in a loop on each target in the multi target list.

crm-targets can be implemented via a special target finder as in https://github.com/oantolin/embark/issues/256#issuecomment-877521614. One could still add an `embark-stringifier-alist`, where crm commands can be registered such that they get the crm-ified string injected. But I would actually prefer to have this auto-detected. You can check for crm-completion-table for example at injection time. If it is a crm command, inject all targets crmified at once, otherwise do the loop.

**Comment by oantolin** [comment]
> I don't think this is very useful, since there are nearly no crm-commands.

This is true.

The one thing I don't like about running actions in a loop on each element of a target that is a list, is that it wouldn't work for some of these bibtex actions.

Maybe we could check if the action has an `embark-multiaction` property and in that case pass the list as a single argument. Without the property, run it in a loop.

**Comment by minad** [comment]
There is still the question what to do about *function actions*. These don't allow auto-detection. So I would say, always treat them as single target actions. Note that it will still be possible to write special target finders, which return a *single target*, which is actually a list, as you described above. One should distinguish target finders returning a *list of targets* and a *single target*.

Let's say we define that target finders are always allowed to return a list, instead of the current `cons`:

* `(type "string")` - Single string target, either injected to commands or passed as argument to functions
* `(type whatever)` - Single whatever target, not injected to commands, passed as argument to functions
* `(type "string1" "string2" ...)` - Multi string target, injected one by one to commands in a loop or passed one by one to functions in a loop
* `(type whatever1 whatever2 ...)` - Multi whatever target, not injected to commands, passed as argument to functions one by one in a loop

> The one thing I don't like about running actions in a loop on each element of a target that is a list, is that it wouldn't work for some of these bibtex actions.

Yes, this is right. For this one has to introduce some property or some `embark-*-alist` configuration variable. Btw, I wonder if the Embark configuration variables are a bit getting out of hand. Maybe one can introduce a single `embark-command-config` variable, which is an alist of plists. `(setq embark-command-config '((my-command :allow-edit t :skip-edit nil :can-handle-list t ...))`. `can-handle-list` would mean that the target list can be passed at once as argument or passed at once crm-ified if it is a command.

**Comment by bdarcus** [comment]
Let me just weigh in on bibtex-actions, since I'm not following everything here.

> If I understand correctly there are the bibtex-completions _functions_ and for each one a corresponding _command_ in bibtex-actions. 

Correct.

> If that's the case, then the _functions_ in bibtex-completions can be used directly as actions if you write a target finder that returns a list of bibliography keys.

> So for just actions at point in non-minibuffers, all that's needed are a target finder returning a list of references and a keymap with the bibtex-completions _functions_ in it. You would run these actions with the `embark-act` and `embark-dwim` commands.

You mean like this?

https://github.com/bdarcus/bibtex-actions/pull/171/commits/ff14d82237627f54fbfe2dd4df393c4ce5220b26

It just seems non-intuitive to me, given that the commands and functions do the same thing.

But that commit hides that from the menus by using descriptions in place of the function and command names.

Is that the approach you recommend, then?

> If you wanted a single-entry point style minibuffer interface, like that of helm-bibtex and ivy-bibtex, you could in fact dispense with the _commands_ in bibtex-actions and just reuse the hypothetical keymap from the previous paragraph. You would need to write one new command say `bibtex-actions-dashboard` that prompted for a multiple selections of bibliography items and you would need a target finder that detects if you are running `bibtex-actions-dashboard` and returns a the list of references corresponding to the selected items (this target finder could be written more generally to work with something like consult-crm).

I only understand that at a high-level. Do you think I should seriously consider this, or just go without your option above?

If yes, do you have an example somewhere of what you mean?

> The _commads_ currently in bibtex-actions are there to present a multiple-entry point UI for the minibuffer functionality, if multiple entry points are not required, the _functions_ from bibtex-completions can be used as actions directly.

**Comment by bdarcus** [comment]
FYI, seems that @ilupin figured it out:

https://github.com/bdarcus/bibtex-actions/pull/171/commits/7d255f4111c165fd28fd3839ee4a98ca112c6fdb
