### ISSUE TITLE
How to create a keymap for a custom function

### ISSUE THREAD

**Issue by thy6** [oantolin/embark#26]
Please help me understand how to setup embark for custom functions. For example, I get "unknown embark action" when I try something like this:

    (let ((embark-custom-map))
      (embark-keymap
       '(("t" . my-embark))
       embark-custom-map)
      (completing-read "prompt: " '("red" "green" "blue")))
    
    (defun my-embark ()
      (interactive)
      (message "You chose %s" (embark-target)))

So that's definitely not the correct way, but then what is the right way for creating embark keymaps for custom functions?

**Comment by oantolin** [comment]
Anothe thing I haven't documented very well, sorry. In my defense, `embark` is still in pretty active development.

You almost have it right, you need to tell embark what "type" of completion you are doing and to register your custom keymap as the keymap to use for that type. I'll do it, as you did, in a let binding, so that configuration isn't permament:

```elisp
(let ((embark--type 'my-custom-type)
      (embark-custom-keymap (embark-keymap
                             '(("t" . my-embark))
                             embark-general-map))
      (embark-keymap-alist
       (cons '(my-custom-type . embark-custom-keymap)
             embark-keymap-alist)))
  (completing-read "prompt: " '("red" "green" "blue")))

(defun my-embark ()
  (interactive)
  (message "You chose %s" (embark-target)))
```

The completion type is arbitrarily chosen to be the symbol `my-custom-type`, and the `let` form adds the pair `(my-custom-type . embark-custom-keymap)` to `embark-keymap-alist`, which is what embark consults to figure out which keymap to offer you.

Notice also that in your code you used `embark-keymap` slightly incorrectly. The last argument is the desired parent keymap, and the return value is the constructed keymap. In your code you throw away the keymap (!), and specified that the null variable `embark-custom-map` should be the parent (which isn't very useful). You'll usually want `embark-general-map` as the parent so you get `C-g`, `C-h`, `C-u` and the general actions `i` and `w`. And in my code you can see that the returned keymap is assigned to `embark-custom-map` instead of discarded.

I have to say, although it works, I'm not terribly happy with the code I wrote above. I'd say embark doesn't support this use-case (one-off commands with their own ad hoc action lists) very elegantly. Maybe I should think about adding way to directly say "trust me, I want *this* keymap", without having to make up a phony type and all. Of course this is Lisp and you can easily fix anything without waiting for me! You can hide that ugly code behind this macro:

```elisp

(defmacro with-embark-actions (actions &rest body)
  (declare (indent 1))
  (let ((type (make-symbol "type"))
        (keymap (make-symbol "keymap")))
    `(let ((embark--type ',type)
           (,keymap (embark-keymap '(,@actions) embark-general-map))
           (embark-keymap-alist
            (cons '(,type . ,keymap) embark-keymap-alist)))
       ,@body)))
```

And now your example looks pretty:

```elisp

(defun my-embark ()
  (interactive)
  (message "You chose %s" (embark-target)))

(with-embark-actions (("t" . my-embark))
  (completing-read "prompt: " '("red" "green" "blue")))
```

**Comment by thy6** [comment]
Thank you so much for the amazing response! `embark-with-actions` is a great addition.
