### ISSUE TITLE
Generalize embark-quit-after-action to a list, unify embark-allow-edit as a single alist?

### ISSUE THREAD

**Issue by minad** [oantolin/embark#343]
See https://github.com/oantolin/embark/issues/340#issuecomment-897698870

**Comment by oantolin** [comment]
Both the question of which actions should quit and which should allow editing of the target seem to face the same configuration problem and we should solve them the same way. The problem is that we want a lot of flexibility which make things a list complicated. For allowing editing we have:

- `embark-allow-edit-default`, a boolean
- `embark-skip-edit-commands`, the list of commands for which editing should not occur even if `embark-allow-edit-default` is `t`
- `embark-allow-edit-commands`, the list of command for which editing should be allowed even if `embark-allow-edit-default` is `nil`.

We could do the same for quitting vs non-quitting, keep the boolean we have now, and add lists `embark-quitting-commands`, `embark-continuing-commands`.

But maybe this is overly complicated and some simpler system would be satisfactory? I don't know. I definitely prefer almost no actions to quit the minibufffer and some people prefer almost all actions to quit it.

**Comment by minad** [comment]
Good idea to first find a general pattern which will we use throughout Embark. I am not a fan of using three variables in these scenarios since it feels like an excessive proliferation of configuration variables. Ideally we capture everything in a single alist.

~~~ elisp
(defvar embark-quit-action-alist
   '((command . t) ;; quit
     (command . nil) ;; do not quit
     (t . t))) ;; default behavior
~~~

~~~ elisp
(defvar embark-edit-action-alist
   '((command . t) ;; allow edit
     (command . nil) ;; do not allow edit
     (t . t))) ;; default behavior
~~~

**Comment by minad** [comment]
What about using the single alists? https://github.com/oantolin/embark/issues/343#issuecomment-897813572. It is slightly less convenient than plain lists, but not much given setf. I think this is the solution I would like to see. It is also convenient in the customize interface with `(repeat choice...)`.

**Comment by oantolin** [comment]
Another option is to use the property list of the symbol naming the action. We could keep a single boolean variable for the default, `embark-allow-edit`, and check whether the action symbol has a property `embark-allow-edit` with value `t` or `nil`.

One issue with that is that having the property with value `nil` would mean "do not allow editing even if `embark-allow-edit` is `t`", but not having the property at all would mean "use `embark-allow-edit`. It's not very lispy to have an absence of the property mean something different from not having the property. To avoid this problem the values for the property could be `yes` and `no` (ugh) or `t` and `no` (maybe even worse).

**Comment by oantolin** [comment]
Yeah, simple alists are probably the best choice so far.

**Comment by oantolin** [comment]
Oh, the simple alists also has the problem that being associated to `nil` is different from not being a key at all!

**Comment by minad** [comment]
> Another option is to use the property list of the symbol naming the action. We could keep a single boolean variable for the default, embark-allow-edit, and check whether the action symbol has a property embark-allow-edit with value t or nil.

I am still very much against using symbol property lists. I dislike having configuration scattered around. It is not good for the customization UI and it is not good discoverability. There are only very few scenarios where I think properties on symbols are a good idea, e.g., when due to lazy loading a variable cannot be used or when you want to make sure that the configuration list is not overwritten accidentally.

> Oh, the simple alists also has the problem that being associated to nil is different from not being a key at all!

Right, this is a problem with alists. Either we use yes/no or we don't use alists naively but check if the key is present. Would this be confusing? In order to delete a key one has to use `assq-delete-all`.

**Comment by oantolin** [comment]
Let's scrap the symbol property list idea, I don't really like it either. I just mentioned it for completeness.

As for the `nil` issue, it is of course easy to distinguish between "associated to `nil`" and "key not present" using `assq`, but `alist-get` doesn't distinguish the two cases which makes me think it's probably a little surprising to distinguish them...

**Comment by minad** [comment]
> As for the nil issue, it is of course easy to distinguish between "associated to nil" and "key not present" using assq, but alist-get doesn't distinguish the two cases which makes me think it's probably a little surprising to distinguish them...

This is not entirely correct. `alist-get` respects nil values, for example `(alist-get 'key some-alist 'default)` will return nil if the value of `key` is nil and not `default`. I think it is okay to go with this approach. The only problem is really when you want to delete a key, then you have to use `assq-delete-all`.

**Comment by jdtsmith** [comment]
I'm missing how either the plist or alist specifies "do not quit, and also continue acting", vs. simply "do not quit".  `n`,  `p`, `u`, etc. will be in the 1st category.  Whereas `make-directory` would (for me) be in the 2nd.  Or is the idea that buffer-only actions like `n`/`p`/`u` will suffer no such ambiguity (i.e. you will always continue "acting")?

**Comment by minad** [comment]
@jdtsmith You are right that the distinction should be addressed properly.

We have to distinguish buffer/minibuffer.

* Buffer: no repeat, repeat
* Minibuffer: quit, continue, repeat

 If we encode all this in a single alist embark-continue-action-alist we could use three values (quit=nil, continue=t, 'repeat). If we use only special symbols ('quit, 'continue, 'repeat) nil in the alist wouldn't be an issue ;)

**Comment by oantolin** [comment]
I propose not allowing for repeating actions in the minibuffer.

Then there are two separate questions for each given action:

- if called from the minibuffer should it quit or not?
- if called from outside the minibuffer should it repeat (i.e. keep `embark-act` running) or not?

And the two questions have one big difference:

- for quitting the minibuffer the _default_ should be configurable, that is, some people will want most actions to quit (and to list some exceptions), some people will want most actions to not-quit (and to list some exceptions).

- but for repeating, I think the default of _not_ repeating works well for everyone, and we just need to keep one list of exceptions.

So for repeating (which, again, I propose to only use for non-minibuffer actions) a list like the current `embark-repeat-commands` is enough.

For quitting the minibuffer we do need a more complex configuration, like the ones proposed here.

**Comment by minad** [comment]
@oantolin I agree that repeating in the minibuffer is probably not needed. However we currently don't enforce that restriction. Repeating in the minibuffer is allowed as of now, isn't it?

**Comment by oantolin** [comment]
No, the details of how `exit-minibuffer` interacts with the command loop mean that repeating actions in the minibuffer don't actually work right now!

**Comment by oantolin** [comment]
I mean, it is allowed, it just doesn't work.

**Comment by minad** [comment]
Really? If you set embark-quit-after-action=nil but default repeating doesn't work in the minibuffer?

Regarding the default: With the quit, continue, repeat alist values I described above it would still be possible to specify a default via the key t. I also agree that repeat by default is not a good idea, but if the lists are unified it would be allowed automatically.

**Comment by oantolin** [comment]
Really, it doesn't work. I'm not sure exactly why.

I'm not sure a single choice between "quit, continue, repeat" is expressive enough. Maybe you need to be able to decide the quitting issue separately from the repeating issue for each action, which is 4 combinations, not 3. Since the choices are orthogonal, I think probably separate configuration variables for quitting and for repeating is better.

**Comment by minad** [comment]
Okay, thanks! Why is repeating orthogonal to quitting? What is the meaning of quit+repeat? Outside the minibuffer it is the same as repeat obviously, but inside the minibuffer? Quit the minibuffer and then repeat outside the minibuffer? I could imagine only very special scenarios where one would want this, e.g. take the target in the minibuffer, insert it in the buffer and then repeat on it. It looks as if you would never want this, leaving us with the three alternatives.

**Comment by minad** [comment]
Or does it mean quit the minibuffer, restart and act again in the minibuffer? Note that we also have embark--restart now complicating the picture.

Overall I agree with you that it is better to not combine everything into one configuration variable to configure special behaviors separately. I only wonder about the semantics of some of the combinations, e.g., quit+repeat.

**Comment by oantolin** [comment]
> Why is repeating orthogonal to quitting?

I just meant (under my proposal to not use repeating for minibuffer actions) that repeating is about when an action is called from outside the minibuffer, and quitting is about when it is called from the minibuffer. So for each action you ask two questions:

- If this action is called from outside the minibuffer do I want it to repeat or not?
- If this same action is called from the minibuffer do I want it to quit the minibuffer or not?

You can decide repeating for the normal buffer case independently from quitting in the minibuffer case.

> What is the meaning of quit+repeat?

Just to be clear, that would mean: "if called from the minibuffer then quit, but if called from a regular buffer then repeat".

**Comment by minad** [comment]
> You can decide repeating for the normal buffer case independently from quitting in the minibuffer case.

Right. This justifies the orthogonality. I assumed that you would want the same or similar behavior in both contexts, which is probably a wrong way to look at it. I still believe that there are no actions which you should quit the minibuffer and repeat in a normal buffer, but maybe this is only because there are so few actions one wants to repeat.

**Comment by oantolin** [comment]
> I still believe that there are no actions which should quit the minibuffer and repeat in a normal buffer.

Ah, sorry, looks like I had misunderstood you. That is a good question, I can't think of any examples off the top of my head.

**Comment by oantolin** [comment]
The other combinations seem fine, right?

- non-repeating, non-quitting: `make-directory`
- repeating, non-quitting: something like `next-buffer` or "next saved window configuration" (both of which ignore the target)
- non-repeating, quitting: probably most actions (for people who like minibuffer-quitting).

**Comment by minad** [comment]
Yes, the other combinations make sense to me.

**Comment by jdtsmith** [comment]
> repeating, non-quitting

`n`,`p`, and `u` are the classic cases.  Or are we talking mini-buffer only?  BTW, I presume corfu = minibuffer? 

I think users would really appreciate putting sensible defaults in place.  For example, if you are in the minibuffer, you probably do NOT want to quit on make-directory, or chmod, or rename-file (none of which require repeating).

**Comment by minad** [comment]
>  Or are we talking mini-buffer only? BTW, I presume corfu = minibuffer?

Quitting only makes sense in the minibuffer. Yes, we can assume corfu=minibuffer. But let's keep Corfu out of the discussion for now since it is not yet supported by Embark.

> I think users would really appreciate putting sensible defaults in place. For example, if you are in the minibuffer, you probably do NOT want to quit on make-directory, or chmod, or rename-file (none of which require repeating).

Now that you proposed these commands, I am not even sure I want the generalization of `embark-quit-after-action` to an alist. I am setting `embark-quit-after-action=nil`, since I *never* want to quit. I suggest you also give this setting a try! Never quitting has many advantages, since it keeps the narrowed completion list intact. Quitting is easy, just press C-g or C-u before invoking the action. 
Restoring the state after not-quit actions is easy in comparison to quitting where one has to start all over again. Therefore I don't even mind that no per-command override feature exists, which allows me to configure commands to always quit.

(If we decide to *not generalize* `embark-quit-after-action`, then the question is why is repeating so much different that it deserves to be configured as a list. Why is repeating not a single flag like `embark-quit-after-action` such that we always stay in the action context? Repeating is a much stronger behavior than quitting/non-quitting and it is much more obvious for which commands repeating makes sense and for which it doesn't.)

**Comment by oantolin** [comment]
You know, I think you're right about allowing edit, @minad. We should remove `embark-allow-edit-default`, remove `embark-skip-edit-commands` and keep only `embark-allow-edit-commands` (and rename it to `embark-allow-edit-actions`).

**Comment by oantolin** [comment]
I second the suggestion to give `embark-quit-after-action=nil` a shot, @jdtsmith. You may find you prefer it.

**Comment by minad** [comment]
What do you think about the additional safety feature?

> As a safety precaution we should add a feature which checks if the action is present in the action keymap. If it is not present always request confirmation and enable editing!

We could of course guard this behind a feature flag, embark-edit-action-if-not-present? The idea is that actions which landed in the default keymaps are safe to use and the dangerous ones are protected by `embark-edit-actions` (I would call it like this without the `allow`).

**Comment by oantolin** [comment]
I'd have to think about it. It sounds perfectly fine, of course, I just wonder if it is necessary.

**Comment by minad** [comment]
> I'd have to think about it. It sounds perfectly fine, of course, I just wonder if it is necessary.

Probably not. It is more of defense to justify the removal of `embark-allow-edit-default`. ;)

**Comment by oantolin** [comment]
I think it's probably fine to remove `embark-allow-edit-default` without the safety feature (which can of course be added later if it is problematic).

**Comment by jdtsmith** [comment]
OK you've convinced me to try it; maybe never-quittting is in fact what I want.  And if so, maybe it's what all users would want?  Since it wasn't the default, I assumed it was somehow a less desirable/more finicky experience.  But I'm not sure which actions I'd actually want to quit after thinking about it.  Maybe export for example.  And become is obvious (but it's more like a "restart").  

Also, I still cannot really understand the point of edit with completion.  Since you can either select a candidate or select "the prompt" and enter _anything_, why would you ever need a further round of completion-tied "editing" (which is more like "completion again")?  If you just need safety, then a `y-or-no-p` is more apropos!  If you are tasked with entering a shell command to go with your chosen file, how will file completion help you?

**Comment by minad** [comment]
> OK you've convinced me to try it; maybe never-quittting is in fact what I want. And if so, maybe it's what all users would want? Since it wasn't the default, I assumed it was somehow a less desirable/more finicky experience. But I'm not sure which actions I'd actually want to quit after thinking about it. Maybe export for example. And become is obvious (but it's more like a "restart").

I also don't understand why Omar choose quitting as default. :laughing: 

>  If you just need safety, then a y-or-no-p is more apropos! If you are tasked with entering a shell command to go with your chosen file, how will file completion help you?

The allow editing feature just disables the automatic pressing of RET after injecting the target into the minibuffer. Take a look at the Embark calling convention section in the README. It is reasonable to provide this feature. Adding a yes/no confirmation in comparison would be very much ad-hoc!

**Comment by minad** [comment]
Since there seems to be agreement here, I close this issue. See #344 :)

**Comment by oantolin** [comment]
@minad said:

> I also don't understand why Omar choose quitting as default. 😆

@clemera talked me into it! _I_ set it to `nil` in my personal configuration.

@jdtsmith said:

> Also, I still cannot really understand the point of edit with completion.

As @minad said, all that allowing editing does is _not_ press RET for you. So you get completion or you don't depending on whether the action you ran has completion at that prompt or not. Embark does not modify the action command's prompting behavior.

The vast majority of the actions bound in Embark's keymaps are built-in Emacs commands and they mostly have completion. Why does `make-directory` prompt you for a hopefully non-existing name with completion? Isn't completion for things that already exist? I think it's still a good idea to have completion in `make-directory` for navigation, but if you disagree it's easy to write a version of `make-directory` without completion.

For examples of built-in commands were you don't get completion consider `shell-command` or `eval-expression`. For both of those it's a good idea to allow editing, otherwise you wouldn't be able to type the shell command you want run on your file target or the expression you want evaluated involving your function target. Those don't have completion (but you can use completion-at-point at the eval-expression prompt even though the prompt as a whole is not in a completion session, for example).

I hope that explains why you sometimes get completion when editing is allowed. Now, you might ask: why allow editing instead of using `y-or-n-p`? And the answer is simply power and flexibility. It's better to let the user change the target than just accept or decline.
