### ISSUE TITLE
selecting sentence & paragraph; marking target as region for certain commands

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/embark#347]
In text modes, it would be wonderful if repeated embark-act application toggled word/sentence/paragraph selection (and/or if `u` increased the scope in that manner).

**Comment by oantolin** [comment]
Are there some good actions for sentences and paragraphs? I guess beyond saving on the kill-ring, which is always useful, we could have killing and transposing. For paragraphs, filling, indent-rigidly.

By the way, I just noticed that the defun target in markdown mode and org mode is a little wonky. It seems to want to select an entire section including it's heading, but not always. And it's odd, because `C-M-h` seems to mark a paragraph...

Maybe the defun target finder should only be active in modes that derive from `prog-mode`.

**Comment by minad** [comment]
> Maybe the defun target finder should only be active in modes that derive from prog-mode.

I think we had it like this originally?

Probably it makes sense to have special text mode target finders (sentence, paragraph) and the defun finder should only be active in prog-modes or code blocks (org, markdown etc).

**Comment by jdtsmith** [comment]
Fill, count words, cleanup blanks, all the region stuff seems interesting.  If it's a short sentence you may want to consult grep for it.  

BTW I'm often wishing some commands would treat the target as a (temporarily) active region, since it is/will be so easy to "select" something interesting with embark.  For example, there is no "mark sentence" that I know of.  Maybe pushing it too far?

**Comment by hmelman** [comment]
> Maybe the defun target finder should only be active in modes that derive from prog-mode.

FWIW, [the meaning of a defun in markdown-mode is deliberate](https://github.com/jrblevin/markdown-mode/issues/191).  

My first thought was that if marking a defun is broken in some mode, that's the fault of the mode and embark shouldn't be altering it's functionality because of that.  Then I thought that having two different configs for prog and text modes was pretty reasonable since they'd break along symbol/expression/block/defun and word/sentence/paragraph/page lines.  But FWIW, `expand-region` defines different expansion lists for lots of modes, (see the bottom of `expand-region.el`). This probably isn't needed for embark (yet), but having some means for a user to do so for a mode when they've written a custom target would be good.

> BTW I'm often wishing some commands would treat the target as a (temporarily) active region, since it is/will be so easy to "select" something interesting with embark. For example, there is no "mark sentence" that I know of. Maybe pushing it too far?

I was going to ask if something like this was possible. I know that some target maps bind SPC to the relevant mark command.  If there was a presumed region or perhaps a generic `embark-mark-target` command, that would make it easy to apply various region commands to a target.  This would enable an `ispell-sentence` when there's only an `ispell-region` command.  Perhaps a user option to have `embark-mark-target` also change the current embark target to region automatically to give quick access to the region commands.

**Comment by oantolin** [comment]
For any commands you would like to treat the target as region you can add a pre-action hook that marks the target:

```elisp
(cl-defun embark--mark-target (&key bounds &allow-other-keys)
  (when bounds
    (set-mark (car bounds))
    (goto-char (cdr bounds))))

(push #'embark--mark-target (alist-get 'kill-region embark-pre-action-hooks))
```

I'm thinking of adding `embark--mark-target` to Embark itself, because it seems generally useful. In the code above I configured `kill-region` to use it, so that you can kill any at-point target with the standard `C-w` keybinding. (I think I might like this even better than `k` for `kill-sexp` in the action map for s-expressions.)

**Comment by jdtsmith** [comment]
Generally re-using key commands that you already know seems better than learning a new embark one for use only when embarking.  For example, I usually use my binding for `consult-line` in preference to the embark one, and am glad that "it just works".

**Comment by oantolin** [comment]
Yeah, I started out doing that too with `consult-line`, but I think I do use the `C l` binding now. My binding for `embark-act` is `C-;` and my binding for `consult-line` is `M-g l`. I think it's just easier for me to go from `C-;` to no modifiers than to a `M-` binding. Probably if the modifiers in my key bindings for `embark-act` and `consult-line` agreed I wouldn't use the modifierless `C l` binding.

> For example, there is no "mark sentence" that I know of.

Oh, by the way, @jdtsmith, there _is_ a built-in `mark-end-of-sentence` command, which marks from point to the end of the sentence. (That's also the behavior of `mark-word`, I wonder why the naming scheme differs.) It has no binding by default. I use `M-E` (with an uppercase `E`). Other commands useful for prose that have no default bindings (together with the bindings I use personally): `transpose-sentences` (`M-T`), `kill-paragraph` (`M-K`), transpose-paragraphs (`C-x M-t`).

**Comment by oantolin** [comment]
So, which region commands is one likely to want to use on an embark target that isn't already a region? I don't want to preconfigure every possible region command to run `embark--mark-target` as a pre-action hook, only the most useful ones. (And of course people can do this for any other region commands they want to run on non-region targets.)

I was thinking:

- We definitely want:  `kill-region`, `kill-ring-save`, `indent-region`, `narrow-to-region`.
- Maybe: `whitespace-cleanup-region`, `apply-macro-to-region-lines`.
- Even less sure: `write-region`, `append-to-file`.
- When we have sentence and paragraph targets: `ispell-region`, `count-words-region`, `fill-region`.

Is there any other region command you are likely to want to run on a non-region target?

**Comment by oantolin** [comment]
I decided to add all of those (except the prose ones, which I'll add later). 0de5038bfacf96ac18b464bd7c40e1780552a88f

**Comment by jdtsmith** [comment]
Thanks!  Consult-line gets a lot of use for me so I also bind to `super`:

```elisp
   ("M-s l" . consult-line)
   ("s-l"   . consult-line)
   ("s-L" . (lambda () (interactive) ; same mode buffers line
		(consult-line-multi `(:mode ,major-mode))))
   ("M-s-L"   . consult-line-multi) ; all buffers line
```

We've talked about a transient frontend package that lets you consult-line(-multi) with various configured parameters.

**Comment by jdtsmith** [comment]
> So, which region commands is one likely to want to use on an embark target that isn't already a region? I don't want to preconfigure every possible region command to run `embark--mark-target` as a pre-action hook, only the most useful ones. (And of course people can do this for any other region commands they want to run on non-region targets.)
> 
> I was thinking:
> 
> * We definitely want:  `kill-region`, `kill-ring-save`, `indent-region`, `narrow-to-region`.
> * Maybe: `whitespace-cleanup-region`, `apply-macro-to-region-lines`, `indent-rigidly`.
> * Even less sure: `write-region`, `append-to-file`.
> * When we have sentence and paragraph targets: `ispell-region`, `count-words-region`, `fill-region`.
> 
> Is there any other region command you are likely to want to run on a non-region target?

Will it work for other commands which eventually call the specified embark-able region commands?  I have `unfill-region` and `unfill-paragraph` that get plenty of use.

**Comment by oantolin** [comment]
No, you'd directly need to `(push #'embark--mark-target (alist-get 'unfill-region embark-pre-action-hooks))` and same for `unfill-paragraph` and any other command you want to recieve the treatment.

Which hooks get run are looked up by action name, so the command needs to directly appear as a key in the alist `embark-pre-action-hooks`.

**Comment by jdtsmith** [comment]
Understood.  Perhaps `delete-backward-char` and `delete-backward-char-untabify` should be added as they delete region if transient-mark-mode is active.

**Comment by jdtsmith** [comment]
Also perhaps case conversion:

```
C-x C-l Convert region to lower case (downcase-region).
C-x C-u Convert region to upper case (upcase-region).
```

**Comment by oantolin** [comment]
> We've talked about a transient frontend package that lets you consult-line(-multi) with various configured parameters.

I'm hoping to see more transient UIs pop up now that it is in core Emacs. I suspect people will abuse transient for my taste, and use it for things you don't really need it, but for some cases it is really great. The `consult-*grep` commands could definitely use it, as could `consult-line-multi` for buffer selection. I don't think I see much point to `consult-line` having a transient interface, but I could be missing something.

**Comment by oantolin** [comment]
> Also perhaps case conversion

I thought of those, but do you really want to put an entire string or defun in all caps that often? Although maybe that's the wrong question, maybe I should be thinking instead: "if an embark user uses a case command as an action, what do they expect to happen?" And I should configure these so they just work if someone decides to try them. OK, I think I talked myself into it. :D

**Comment by oantolin** [comment]
> Understood. Perhaps `delete-backward-char` and `delete-backward-char-untabify` should be added as they delete region if transient-mark-mode is active.

Oh, and those just delete without saving on the kill-ring right? That's good to have.

**Comment by minad** [comment]
The mark and kill generalization for commands with bounds is a great idea. Didn't think of this when we added highlighting.

Are some specific mark/kill commands made obsolete by the general ones?

**Comment by jdtsmith** [comment]
> > We've talked about a transient frontend package that lets you consult-line(-multi) with various configured parameters.
> 
> I'm hoping to see more transient UIs pop up now that it is in core Emacs. I suspect people will abuse transient for my taste, and use it for things you don't really need it, but for some cases it is really great. The `consult-*grep` commands could definitely use it, as could `consult-line-multi` for buffer selection. I don't think I see much point to `consult-line` having a transient interface, but I could be missing something.

Exactly, for all those buffer-selecting optional arguments.  A good interface I think is "map any prefix argument into a transient", which has good mnemonics.   I do hope the transient docs get improved and some rich examples start appearing; the current docs are detailed but hard to put into actual practice.

**Comment by minad** [comment]
@jdtsmith I would love to see a consult-transient.el package in the consult repository, which adds transient interfaces to consult-x-multi and the consult-grep family of async commands. See also the consult wishlist and https://github.com/minad/consult/pull/170 as a starting point.

**Comment by jdtsmith** [comment]
>  "if an embark user uses a case command as an action, what do they expect to happen?" 

Is this a good argument to just temporarily mark the region for _all_ commands (past present and future) which conclude an embark invocation?  Or is that asking for trouble?

**Comment by minad** [comment]
@jdtsmith Yes, I think marking always is asking for trouble. I would prefer if Embark does not modify anything on its own without an explicit request.

**Comment by minad** [comment]
I wonder where the distinction between region and target should be now.

* Remove all specialized mark/kill/narrow commands from the target maps given general commands with embark--mark-target.
* Consider adding the region map under a prefix key "R" to the general map if not in the minibuffer. For every of these "R" commands the region should be marked automatically before executing the action. This goes in the same direction as the idea by @jdtsmith regarding always marking.

**Comment by oantolin** [comment]
@minad said:

> Are some specific mark/kill commands made obsolete by the generic commands?

I'd say the `kill-sexp` command for expressions is made obsolete by `kill-region`. I want to do one of two things:

- completely remove the binding of `k` to `kill-sexp`, and people can use `C-w`; or
- bind `k` to `kill-region` instead, this would help for a perhaps obscure reason: the defun maps inherits from the expression map and in some programming modes not every defun is a sexp ---for example, currently `k` will correctly kill a python defun but not a C defun.

Basically: we should now use `kill-region` instead of `kill-sexp` as it works in more cases, and optionally we can remove the `k` binding and have people use `C-w`. I think maybe binding `k` to `kill-region` might be worth it for the indicators, but I'm sure my fingers will turn to `C-w` as they are used to.

As for marking commands, we currently have two: `mark-sexp` and `mark-defun`. We could replace them with a single marking command which works on all targets. That command could be bound in the expression map or even in the general map.

Or, we could remove all marking commands on the grounds that instead of marking a target and then using some command that uses the region, people should just skip the marking and use that command directly as an action.

**Comment by oantolin** [comment]
Oh, we were writing at the same time, @minad. Putting the region commands under a prefix is an interesting idea.

**Comment by minad** [comment]
The idea is basically to unify regions and targets. Marking could still be available as an action, but it will be mostly unnecessary. You can always act directly. In order to avoid too much shadowing I would use the R prefix. Only for the region target itself the region map is directly the top-level map.

**Comment by oantolin** [comment]
If we want a general mark action, I'd reuse the `mark` function, just for it's name. 😛 

```elisp
(push #'embark--mark-target (alist-get 'mark embark-pre-action-hooks))
(define-key embark-general-map " " #'mark)
```

**Comment by oantolin** [comment]
It might be useful to have `mark` as an action, for some random region command that isn't configured to use `embark--mark-target` as a pre-action hook.

**Comment by minad** [comment]
Yes and just to have a bridge to the outside of Embark.

**Comment by oantolin** [comment]
> Maybe even consider adding the region map under a prefix key "R" to the general map if not in the minibuffer.

We don't really have a clean way of going the "if not in the minibuffer" part. I could special case the following: if the target has bounds and the keymap has `R` unbound, bind it to the region map... And the same for binding `SPC` to `mark`.

Or, we could just have `R` bound in the general map and try to ignore it when acting from the minibuffer.

**Comment by minad** [comment]
I think special casing this is justified because regions are a fundamental thing in Emacs and because the targets come with bounds. Usually I am not a fan of special cases, but there are exceptions :)

The region map R could be made available if the target has bounds.

We should reconsider embark--mark-target however. Can we make this an :always hook instead which looks into the region map in order to avoid duplicating every command in the hook list and the region map?

**Comment by oantolin** [comment]
> The region map R could be made available if the target has bounds.

OK, special casing it is.

> Can we make this an :always hook instead which looks into the region map in order to avoid duplicating every command in the hook list and the region map?

Sure. The only reason I hadn't done it that way because I was only putting `embark--mark-target` on a few commands.

**Comment by minad** [comment]
> Sure. The only reason I hadn't done it that way because I was only putting embark--mark-target on a few commands.

Yes, understood. But you added quite a few so I thought the generalization is a good idea :)

**Comment by oantolin** [comment]
Well... There are some other options for `R`:

- not have it all, people can use the `mark` action and run `embark--act` again.
- bind `R` to a mark action that is repeatable, so you can immediately choose a region action.

The problem with the second approach is that for repeatable actions the cycle always starts at the same target if possible, and we'd want it to start at the region target.

**Comment by minad** [comment]
Okay running mark and repeat sounds more elegant! Let's do that instead. I think this avoid all special casing and we can remove embark--mark-target again for most commands.

**Comment by minad** [comment]
We should fix repeat such that it starts with the region target in that case. This is all special casing that is needed.

**Comment by oantolin** [comment]
How about if `(use-region-p)` then start cycling at `region`, otherwise start it at current type?

**Comment by minad** [comment]
I like how repeating is more valuable than I had expected. I am glad I pushed this ;)

**Comment by oantolin** [comment]
So I think then I'd keep the `embark--mark-target` function as is, but remove some of the actions that have it configured as a pre-action hook. Maybe keep only `C-w` and `M-w`? Well, those and any region commands we decide are worth binding in some non-region map. Some actions might be frequent enough on some type of target to be worth not going through `R`

For example, we should probably replace `indent-pp-sexp` with `indent-region` in the expression map since it works in all programming modes. And if we do, then `indent-region` should also use `embark--mark-target`.

Do we need separate repeating and non-repeating mark commands? Or is the repeating one enough because people can just cancel embark-act (with `RET` 😄) after marking.

**Comment by minad** [comment]
Even with the mark repeat idea, I would still keep embark--mark-target such that M-w C-w and other region commands can be used directly.

**Comment by minad** [comment]
> Do we need separate repeating and non-repeating mark commands? Or is the repeating one enough because people can just cancel embark-act (with RET 😄) after marking.

I thought about the exact same question and I am undecided 🤷

**Comment by oantolin** [comment]
Let's try just the repeating `mark`, and add a non-repeating one later if necessary. I think I'll use `SPC` instead of `R` for it.

**Comment by minad** [comment]
Yes SPC is much better. I only proposed R for the region prefix map.

**Comment by oantolin** [comment]
OK, done: b20de98c55833e0af38d82f8e698ec9f49157278

This binds `SPC` to `mark` everywhere including the minibuffer, but if that is bothersome we can special-case unbinding it there.

**Comment by oantolin** [comment]
I guess this issue got a highjacked by using targets as regions. That part seems mostly finished, and I will add sentence and paragraphs targets tonight (I have to go out right now). I do have one further question: what actions differ from sentences to paragraphs? I think they should share almost all of them, except transpose-{sentences,paragraphs}.

**Comment by minad** [comment]
Did it really get hijacked given the title "marking target as region for certain commands"? It is probably a good idea to create separate issues for separate ideas 😬

**Comment by oantolin** [comment]
The title was changed after the high-jacking! 😆

**Comment by jdtsmith** [comment]
RE mixing issues: apologies, this thought sort of came out of nowhere.  

I'm definitely in favor of "just act directly" for the most useful region-based commands.  Similar to how I can "just act directly" and drop right into consult-line, etc.  With all of this mark and repeat business, I'm actually a bit worried about an inconsistent experience: if you get used to `C-w` working on a target "directly", why wouldn't other such commands just work?   Then you have to remember to reach for a SPC to mark them first?  Would the region highlight change when you are targeting + marking (vs. just targeting)?

**Comment by jdtsmith** [comment]
On the other hand, if you worry about embark "stealing the mark" without having been asked to do so, SPC makes more sense (esp. if the highlight face changes to indicate it).  I guess a short user configurable list of commands which can "act directly on targets as if they were regions" might be a good compromise.

**Comment by minad** [comment]
Now we have a mix of both approaches. Some commands are available directly and some require you to mark first. This makes sense since we would get too much shadowing if every region command is directly available with a top-level keybinding. Note that some users also expressed their preference to "hide" many of the general bindings. What we've got is a compromise. Either you act on the target or you press space first to switch to the region target.

**Comment by minad** [comment]
> I guess a short user configurable list of commands which can "act directly on targets as if they were regions" might be a good compromise.

This exists already. It is the set of commands with embark--mark-target in their pre action hooks.

**Comment by minad** [comment]
One thing I should add - it probably makes sense to add embark--mark-target for every command acting on regions which is available as global binding. On top of that Embark can make more commands accessible via its region keymap.

**Comment by hmelman** [comment]
> > Also perhaps case conversion
> 
> I thought of those, but do you really want to put an entire string or defun in all caps that often? Although maybe that's the wrong question, maybe I should be thinking instead: "if an embark user uses a case command as an action, what do they expect to happen?" And I should configure these so they just work if someone decides to try them. OK, I think I talked myself into it. :D

In particular I could see using `capitalize-region` for sentences via embark when writing titles.

**Comment by hmelman** [comment]
> I do have one further question: what actions differ from sentences to paragraphs? I think they should share almost all of them, except transpose-{sentences,paragraphs}.

Just to mention this, there is the obscure but sometimes useful command, `repunctuate-sentences` which puts two spaces at the end of sentences from point to the end of buffer.  It doesn't respect the active region so it could be useful to use with a narrowed paragraph.  I'm not sure if it deserves an embark (paragraph) binding, but it would certainly help me to remember it and find it given it's unusual name.

**Comment by oantolin** [comment]
> esp. if the highlight face changes to indicate it

We could have the highlight indicator *not* highlight region targets, so they get their normal face.

**Comment by minad** [comment]
> We could have the highlight indicator not highlight region targets, so they get their normal face.

While I see the appeal I also think it is misleading since then it is not obvious that you are embarking.

**Comment by oantolin** [comment]
> While I see the appeal I also think it is misleading since then it is not obvious that you are embarking.

I doubt anyone is using _just_ the highlighting indicator, maybe th

**Comment by oantolin** [comment]
Off-topic, but I'm really enjoying putting point on the blank line after a defun and using `<embark-act> i` to duplicate it. (If you noticed I moved `indent-pp-sexp` from `i` to `TAB` a few days ago, this is why! 😉)

**Comment by oantolin** [comment]
So, @hmelman, you'd prefer we keep the defun target for text modes? Or at least for markdown-mode? (I was considering restricting it to modes derived from prog-mode.)

**Comment by oantolin** [comment]
I added the sentence and paragraph targets and actions. Please let me know if any other actions would be good to bind. I made the motion and transpose actions repeatable (dragging stuff forward is super fun; dragging them backwards is, appropriately, a bit of a drag: `C-- t C-- t C-- t ...`).

I can't believe how quickly the default configuration is improving. This new indexed-by-actions format for the {pre,setup-post}-action hooks really encourages one to use them!

**Comment by oantolin** [comment]
I think I agree with @jdtsmith in that we might as well configure lots and lots of region commands to mark the target, so that if someone uses them they aren't disappointed (the politely named "principle of least surprise"). So I added all of these:

- those that have a key binding by default
- those that are bound in some non-region embark keymap
-

**Comment by hmelman** [comment]
> So, @hmelman, you'd prefer we keep the defun target for text modes? Or at least for markdown-mode? (I was considering restricting it to modes derived from prog-mode.)

I'm not sure, I can't say I personally use defuns in `markdown-mode`, though I probably should.  I'm not really an org user (another `text-mode` descendant), and I'm not sure how defuns are used in org-mode (would just it be in source code blocks?).  I think, like in `expand-region` its more important to be able to easily configure the targets for different modes (not sure how this is currently implemented, I just see a single non-buffer-local `embark-target-finders` user option).

**Comment by oantolin** [comment]
> not sure how this is currently implemented

A target finder returns either nil if not applicable or the target it found. So it can check for the mode (or any other condition) before even looking for the target.

For targets that are just `(thing-at-point 'some-thing)` I just added a macro `embark-define-thingatpoint-target` that you call with the thing and the list of applicable modes. For example the sentence target is defined by `(embark-define-thingatpoint-target sentences text-mode help-mode Info-mode man-common)` ---something like that, I may be forgetting the precise list of modes.

**Comment by jdtsmith** [comment]
Since by default embark acts on any marked region, there's no reason not to use both expand-region and embark together.  That said, it might be nice to have (optional) access to expand region capabilities after an embark is underway.  In particular for reducing region and reset (so `@`, `-`, `0`).
