### ISSUE TITLE
Why use `embark-find-definition` rather than `xref-find-definitions`?

### ISSUE THREAD

**Issue by fbergroth** [oantolin/embark#349]
Hi, thanks for a great package!

I'm noticing that `embark-find-definition` is the default target for symbols, and it's weaker than the elisp xref backend (which also finds e.g. faces and features).

Perhaps xref can be used instead, or is there a reason for `embark-find-definition`?

**Comment by oantolin** [comment]
I'm not at Emacs right now but if I recall correctly the issue was that xref-find-definition only worked from an Emacs Lisp buffer. I often use embark-find-definition from help, info, markdown or message-mode buffers.

**Comment by fbergroth** [comment]
I see. Perhaps something like `(xref-backend-definitions 'elisp sym)` can be used.

**Comment by oantolin** [comment]
Thanks for the suggestion!

**Comment by chasecaleb** [comment]
Hi @oantolin, I don't think binding `xref-backend-functions` to a hard-coded value is a very good idea... the point of that variable is to allow users and major modes to customize it.

For instance, I use [Dumb Jump](https://github.com/jacktasia/dumb-jump/) by doing `(add-hook 'xref-backend-functions #'dumb-jump-xref-activate)`. I just spent a while figuring out why it wasn't working with `embark-dwim` until figuring out this issue was the cause. I had `embark-dwim` bound to `M-.` because I thought it was a drop-in improvement over `xref-find-definitions` due to this section of the readme:

> The suggested alternative of M-. for embark-dwim is bound by default to xref-find-definitions. That is a very useful command but overwriting it with embark-dwim is sensible since in Embark’s default configuration, embark-dwim will also find the definition of the identifier at point. (Note that xref-find-definitions with a prefix argument prompts you for an identifier, embark-dwim does not cover this case).

---

I think it would be better to call `xref-find-definitions` directly without overriding `xref-backend-functions`, because that seems outside the scope of what embark is responsible for. If you want to change the behavior of xref, you should do so in your own config with something like `(add-hook 'xref-backend-functions #'elisp--xref-backend)` to add it locally or `(add-hook 'xref-backend-functions #'elisp--xref-backend nil t)` in a mode hook (e.g. `help-mode-hook`) to add it only for certain modes.

**Comment by oantolin** [comment]
So let me see if I understand your problem: you want to use `dumb-jump-xref-activate` for Emacs Lisp identifiers? I'm a little surprised since I thought it would mainly be used for identifiers in other programming languages but for Emacs Lisp where Emacs already was pretty good built-in support.

Also, could you explain this remark?

> I think it would be better to call xref-find-definitions directly without overriding xref-backend-functions, because that seems outside the scope of what embark is responsible for. 

First of all, Embark does bind `xref-find-definitions` directly, it does so in `embark-identifier-map`. The other function `embark-find-definitions` is meant for Emacs Lisp identifier no matter which major mode buffer they are found in. This is not something Emacs already has a function for, the closest function it has being `xref-find-definitions` which does the wrong thing: it doesn't work for Emacs Lisp identifiers in non-Emacs Lips buffers. Why is providing a small function for this task out of Embark's scope?

I'm sure we can fix this in a satisfactory manner but first I'd like to understand exactly what your issue is. And currently I neither know why you want to use dump-jump for Emacs Lisp, nor why you find `embark-find-definitions` out of scope for Embark, nor why you talk about changing the behavior of xref in the last paragraph. I don't think that's what's going on: I repeat, Embark uses `xref-find-definitions` as is without changing it's behavior at all, and additionally has a new function `embark-find-definitions` which performs a different task from `xref-find-definitions` and only happens to use it as an implementation detail.

**Comment by oantolin** [comment]
It is definitely true that `embark-find-definitions` is not as configurable as `xref-find-definitions`. Maybe your point is more a feature request? You'd like it to be as configurable as `xref-find-definitions`? That's probably a good idea. We could either introduce an `embark-find-definition-backend-functions` user option (which I don't think is such a good idea), or we could trust the user to setup `xref-backend-functions` to whatever they want to be used for Emacs Lisp identifiers in new Emacs Lisp mode buffers. For that second approach we could change the definition to:

```elisp
(defun embark-find-definition (symbol)
  "Find definition of Emacs Lisp SYMBOL."
  (interactive "sSymbol: ")
  (let ((xref-backend-functions
         (with-temp-buffer (emacs-lisp-mode) xref-backend-functions)))
    (xref-find-definitions symbol)))
```

**Comment by oantolin** [comment]
Whoops, I forgot to notify you @chasecaleb. See my two comments above.

**Comment by chasecaleb** [comment]
> So let me see if I understand your problem: you want to use dumb-jump-xref-activate for Emacs Lisp identifiers?

I've been toying with it at least. The hope was that I could use dumb-jump for symbols within my project's source code files and elisp for symbols outside it (e.g. Emacs core), because I want to jump to the VCS definitions of things when working on a project, not the ones currently evaluated from `load-path` or wherever. However, xref's design where it queries backends until one returns results (as opposing to querying all of them and merging the results) makes this more or less impossible so I think I'm going to give up on the idea.

> First of all, Embark does bind xref-find-definitions directly, it does so in embark-identifier-map. The other function, embark-find-definitions, is meant for Emacs Lisp identifiers no matter which major mode buffer they are found in.

Okay, that's the big part I misunderstood when commenting initially. I originally thought that `embark-find-definition` would interfere with other modes such as languages using `lsp-mode`, which provides an xref backend of its own. Knowing that, I'm okay with things the way they are currently. So sorry for the wild goose chase, and I really appreciate your explanation!!!
