### ISSUE TITLE
Embark-actions do not work in the context of `package-delete'

### ISSUE THREAD

**Issue by overideal** [oantolin/embark#353]
Most embark actions while selecting a package to delete with `package-delete` are not working. This includes `describe-package`(error message: embark_ PCH: (wrong-type-argument package-desc _nil)), `package-reinstall`, `embark-browse-package-url` and `embark-export` (the exporting list is empty).
I think the problem is that the package names in the completion list of the `package-delete` command have their version appended as a suffix.
By the way, I think the current embark action map of `package-delete` is `embark-package-map`, but for consistency, it should probably have its own map (e.g. `embark-package-delete-map`), because it makes no sense to bind `package-install` in that context. Similarly, the map of `package-install` should not contain `package-delete` as an option.

**Comment by oantolin** [comment]
Thanks for reporting the problem with `package-delete` and its version numbers, which should be fixed now. (I had a workflow where the issue never comes up: I treat `describe-package` as the main entry point for packages ---since it is the only package command to have a default key binding!--- and I only ever run `package-install` or `package-delete` as actions from `describe-package`. That's why I never really noticed the problem.)

I don't think it is really worth the effort to make these commands report different completion categories just so they can have seperate keymaps that are almost identical. I'd recommend just not running `package-install` from `delete-package` and viceversa (though it's harmless to do so).

**Comment by minad** [comment]
I just observed the Marginalia fix, which has one downside - no annotations are shown for the versioned packages. Therefore I reverted this for now. Note that `marginalia-annotate-package` strips version numbers by default.

Is there something which prevents you from always removing version numbers from the `package` category? This way we can use the same category `package` for both versioned and unversioned packages. It is conceptionally not perfectly clean, but having two categories looks like overkill.

**Comment by minad** [comment]
At least I am pretty sure that there are no packages ending with version numbers in their name. MELPA/ELPA should forbid this.

**Comment by oantolin** [comment]
> But I would like to ask first - is there something which prevents you from always removing version numbers from the `package` category?

I think that works. Let's do it that way, instead.

**Comment by oantolin** [comment]
Done, @minad. Thanks for coming up with the simpler solution!
