### ISSUE TITLE
Category type environment-variable when reading file names

### ISSUE THREAD

**Issue by clemera** [oantolin/embark#36]
Hi Omar,

When using `org$` as matching regexp in `find-file` `(completion-metadata-get (embark--metadata) 'category)` returns `environment-variable` while you would expect the `file` category which allows export to dired for example.

**Comment by oantolin** [comment]
This is a little tricky: the behavior is "correct", you can in fact type environment variables with completion at a find-file prompt. (You can use this to your advantage to "bookmark" directories or files by assigning their paths to environment variables.)

**Comment by clemera** [comment]
Do you think it might make sense for embark to workaround this?

**Comment by oantolin** [comment]
Maybe not. The possibility of embedding environment variables in paths is actually a feature people might want, which I guess is the reason Emacs ships with it.

I take it you are still using `orderless`, right? So you want `org$` to match "files ending in `org`" rather than matching literally? If that's the case two simple work arounds are (1) to use `\'` instead of `$`, or (2) to add an extra space after the `$`.

(Technically I think `org$` doesn't match "file names that end in `org`" on Unix-like systems due to the craziness of accepting file names with embedded newlines. It really matches "files that either end in `org` or have `org` right before a newline"! The alternative Emacs regexp `org\'` really means "file names ending in `org`"...)

**Comment by oantolin** [comment]
Personally I don't use this environment variable stuff any more, so for me you suggestion adding `environment-variable` to `embark-keymap-alist` mapping it to `embark-file-map` would be convenient (I'm currently using the work around of typing an extra space after the `$`). I'm just not sure if it should be a default in embark or a personal configuration.

**Comment by clemera** [comment]
> Technically I think org$ doesn't match "file names that end in org" on Unix-like systems due to the craziness of accepting file names with embedded newlines

Yeah, that's right :) But I don't have any filenames with newlines so this never happens to me in practice. But I do use `\'` in code as well so in theory people with newlines in their filenames could use it as well.

Your recommended workaround is fine for me but I think it would be common pitfall and people new to embark would stumble across this at some point and then have to come up with a workaround. Having a mapping of this category to an envar variable action map would already help because it makes it easier for users to change it without investigating what is going on. Maybe there could be an additional feature which shows which category is used. Similar to `hippie-expand` which shows the used try-function in the echo area by default.

**Comment by oantolin** [comment]
I think your suggestion to just map `environment-variable` to `embark-file-map` in `embark-keymap-alist` was probably the right idea. I'm going to do that and close this issue. The one action I wanted for environment variables, seeing their value, is handled by Marginalia now.

**Comment by oantolin** [comment]
Since Marginalia now shows me variable values, which is the one thing I wanted from the `environment-variable` category, I think I can safely take your suggestions of mapping that category to the file action keymap by default (I doubt people use the `getenv`/`setenv` commands that much, I feel the main case for `environment-variables` is in `find-file`).
