### ISSUE TITLE
[FEATURE] Add find file manually action to File

### ISSUE THREAD

**Issue by strikerlulu** [oantolin/embark#400]
Add an action like [counsel-projectile-find-file-action-find-file-manually](https://github.com/ericdanan/counsel-projectile/blob/e30150792a96968f55f34638cbfe63eaa30839cc/counsel-projectile.el#L1495)(Call `find-file` from FILE's directory) to File

**Comment by oantolin** [comment]
I'm inclined to think you should probably just add this action in your personal configuration, but maybe I'm missing something about the broader appeal. Could you explain the use case for this?

**Comment by strikerlulu** [comment]
its use case would be similar to `embark-dired-jump` 

so it should be like this or is there an easier way to change/add keybindings to exists keymap ?
```elisp
(embark-define-keymap embark-file-map
  "Keymap for Embark file actions."
  ("RET" find-file)  ("f" find-file)
  ("o" find-file-other-window)
  ("d" delete-file)
  ("D" delete-directory)
  ("r" rename-file)
  ("c" copy-file)
  ("j" embark-dired-jump)
  ("!" shell-command)
  ("&" async-shell-command)
  ("m" embark-find-file)
  ("M" chmod)
  ("=" ediff-files)
  ("e" embark-eshell)
  ("+" make-directory)
  ("I" embark-insert-relative-path)
  ("W" embark-save-relative-path)
  ("l" load-file)
  ("b" byte-compile-file)
  ("R" byte-recompile-directory))

(defun embark-find-file (file &optional other-window)
  (interactive "fJump to Dired file: \nP")
  (let* ((f (projectile-expand-root file))
         (default-directory (file-name-directory f)))
    (call-interactively #'find-file)))
```

**Comment by oantolin** [comment]
What you wrote shoud work just fine, but there is no need to redefine the whole keymap just to add one new key binding. Instead you can use any of the normal methods you use to add key bindings, such as [define-key](https://www.gnu.org/software/emacs/manual/html_node/elisp/Changing-Key-Bindings.html), or, if you use `use-package`, the `:bind` clause, or maybe [general.el](https://github.com/noctuid/general.el).

With `define-key` it would look like this:

```elisp
(define-key embark-file-map "m" #'embark-find-file)
```

I think instead of adding that `embark-find-file` function, I might just use `embark-become` to switch from `projectile-find-file` to regular `find-file`.

**Comment by strikerlulu** [comment]
My bad i didn't thought it as an actual keymap :(

I actually tried `embark-become` but i get this error
![image](https://user-images.githubusercontent.com/38893265/140683279-88c6850c-a6fd-445e-ae03-2f2c951c13da.png)
And if i press any key after it
![image](https://user-images.githubusercontent.com/38893265/140683398-e449dec5-cb21-453c-91fd-a52d72229396.png)

still pressing `M-o(embark-act) m` would be much easier than `M-o Shift+b` and selecting function

**Comment by oantolin** [comment]
> My bad i didn't thought it as an actual keymap :(

No problem. It's somehow easy to miss. Embark generally reuses all the Emacs concepts it can. Keymaps are normal Emacs keymaps, and actions are normal Emacs commands that prompt you in the minibuffer in the usual way (like your .`embark-find-file`).

The no bindings error just means that Embark didn't find the command you were running (I don't which command it is but I mean the one that printed `[doom] Find file: ` as the minibuffer prompt) in any of the become keymaps. In that case you can still become another commands, but there are no special key bindings, you just use your usual, global key bindings, including `M-x`. For example, when that "No bindinges found" message  is displayed you could type `M-x find-file` to become `find-file` or use whatever key binding you normally use to find a file (I don't use Doom and have no idea what it binds `find-file` to).

You may want to add whatever command you were running to the `embark-become-file+buffer-map`, so that if you are running it and use become you get offered the other key bindings in that map.
