### ISSUE TITLE
Add Corfu candidate collector

### ISSUE THREAD

**Issue by minad** [oantolin/embark#415]
Action support is difficult due to the brittle popup, but a candidate collector could be useful. Would you accept a PR which adds one? Alternatively one can first transfer to the minibuffer, see https://github.com/minad/corfu/wiki#transfer-to-the-minibuffer.

**Comment by oantolin** [comment]
I'd love a PR implementing that. I remember I tried it once and it seemed a little tricky, for the same reason as the target finder is tricky: the popup is very brittle. I tried the obvious:

```elisp
(defun embark--corfu-candidates ()
  "Collect the current Corfu candidates.
Return the category metadatum as the type of the candidates."
  (when corfu--input
    (cons (completion-metadata-get corfu--metadata 'category)
          corfu--candidates)))

(with-eval-after-load 'corfu
  (add-hook 'embark-candidate-collectors #'embark--corfu-candidates))
```

And what happens, I think, is that the popup closes before embark-collect-snapshot gets a chance to do its thing (by the way, you have to bind `embark-collect-snapshot` to a key to even try it, because `<embark-act> S` closes the popup right after embark-act, so it's even worse). I then tried:

```elisp
(add-to-list 'corfu-continue-commands 'embark-collect-snapshot)
```

With this, the export works but Corfu stays alive, which is nice, but different from what happens in the minibuffer.

**Comment by oantolin** [comment]
What am I missing?

**Comment by minad** [comment]
Yes, you have to bind the snapshot key in the corfu-map. But then the following works...somehow...:

~~~ elisp
(defvar corfu--input)
(defvar corfu--metadata)
(defvar corfu--candidates)

(defun embark--corfu-candidates ()
  (when corfu--input
    (embark--run-after-command #'corfu-quit)
    (cons (completion-metadata-get corfu--metadata 'category)
          corfu--candidates)))

(with-eval-after-load 'corfu
  (add-hook 'embark-candidate-collectors #'embark--corfu-candidates))

(define-key corfu-map "\M-s" #'embark-collect-snapshot)
~~~

Unfortunately there are multiple downsides:

* When toggling the view, the collector is executed again and we get the outline due to #408 
* Capfs/completion-in-region tables usually do not provide a completion category and annotations and we don't enhance them via Marginalia

So it seems to me that it would be better to not add a Corfu collector here. Instead we should take the detour via the minibuffer.

**Comment by oantolin** [comment]
Now that I think of it, I hardly ever use embark-collect-snapshot with consult-completion-in-region, so there's a good chance this feature wouldn't get that much use. And when it comes to actions, the only one I use with any regularity is asking for documentation, which already has a dedicated keybinding in Corfu. So I think corfu just doesn't really need Embark intergration.

And for the rare case where you do want to collect the candidates, that `corfu-embark-snapshot` seems perfectly adequate (and it even works around #408 ---which I will fix eventually). I guess moving to the minibuffer is also good if you want an action that corfu doesn't cover, though I'm not sure I have a good example of that, since documentation and goto-definition are probably the main ones and are handled by corfu.

**Comment by minad** [comment]
Yes. I just wanted to see if it would work out. But for actions/snapshot the minibuffer is better. Furthermore the utility of Corfu is for quick in buffer completion, it is okay if it is not as accessible as usual completion.
