### ISSUE TITLE
There are some warnings when byte compiling.

### ISSUE THREAD

**Issue by terlar** [oantolin/embark#43]
```
In embark--setup-action:
embark.el:645:43: Warning: reference to free variable `embark-general-map'

In embark-annotation-function-metadatum:
embark.el:919:28: Warning: reference to free variable
    `embark-occur-annotation-func'

In embark-embark-occur-candidates:
embark.el:988:5: Warning: reference to free variable `embark-occur-candidates'

In embark-occur-choose:
embark.el:1069:38: Warning: reference to free variable `embark-occur-from'
```

**Comment by oantolin** [comment]
Ha! What a funny coincidence: I was just looking at those! (I normally don't get any warnings, since I byte-compile embark with embark loaded, but I just byte-compiled it in `emacs -Q` to check on its general health and noticed them.) All those variables do have declarations, but the declarations come after those lines indicated in the warnings. I am about to fix them.
