### ISSUE TITLE
Custom actions to run as "before" items

### ISSUE THREAD

**Issue by gcv** [oantolin/embark#431]
Newbie problem here. I'd like to add a general Embark action to split a window (run `split-window-below` or `split-window-right`). I want that to be part of `embark-general-map` so it applies to any command I run. That way I don't have to remember to pre-split a window before doing something that will affect the currently open window. I tried this:

```
  (defun /embark-split-window-below (&optional arg)
    (interactive)
    (funcall #'split-window-below)
    (message "arg: %s" arg))

  (defun /embark-split-window-right (&optional arg)
    (interactive)
    (funcall #'split-window-right)
    (message "arg: %s" arg))

  (define-key embark-general-map (kbd "2") '/embark-split-window-below)
  (define-key embark-general-map (kbd "3") '/embark-split-window-right)
```

How do I tell Embark to just do the split and the run the original command, i.e., what should happen instead of the `message` calls? I'm trying to adapt some examples from https://karthinks.com/software/fifteen-ways-to-use-embark/ but the tips there are specific to submaps and specific commands that then get called explicitly with `funcall`. I'm looking for a "oh I forgot to pre-split the window, let me do that without losing minibuffer state" solution. I tried using a prefix argument to `embark-act` with the sample code above, but that just restored the window configuration after calling the command.

**Comment by oantolin** [comment]
That's tricky! Emacs has this deeply ingrained behavior of restoring the window configuration after quitting the minibuffer. It's done in C code and the behavior is hard to modify from Elisp. It's usually easier to somehow schedule for the window configuration changes to take place *after* quitting the minibuffer.

So, I suggest you try this solution. It doesn't work as an Embark action, so I suggest you bind it in `minibuffer-local-map` instead:

```elisp
(defun split-right--hook (&rest _)
  (setf (alist-get :always embark-pre-action-hooks) ; self-destruct
        (remove 'split-right--hook
                (alist-get :always embark-pre-action-hooks)))
  (split-window-right))

(defun later-split-right ()
  (interactive)
  (message "Next embark action will split window to the right.")
  (push 'split-right--hook (alist-get :always embark-pre-action-hooks)))

(define-key minibuffer-local-map (kbd "C-x 3") #'later-split-right)
```

(I suggest binding it to `C-x 3` or whatever you use normally for `split-window-right`, since that command doesn't work from the minibuffer anyway.)

Does that do what you wanted?

**Comment by gcv** [comment]
Very clever! Thank you.

**Comment by minad** [comment]
As far as I know Emacs 28 introduced a variable to disable the minibuffer window restoration behavior. Maybe this is helpful here? I don't think the variable should be set globally, but it could help in some special scenarios.
