### ISSUE TITLE
Bind repunctuate-sentences to text mode region maps in Emacs 29

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#442]
> Just to mention this, there is the obscure but sometimes useful command, `repunctuate-sentences` which puts two spaces at the end of sentences from point to the end of buffer.  It doesn't respect the active region so it could be useful to use with a narrowed paragraph.  I'm not sure if it deserves an embark (paragraph) binding, but it would certainly help me to remember it and find it given its unusual name.

_Originally posted by @hmelman in https://github.com/oantolin/embark/issues/347#issuecomment-899106925_

Based on [Emacs Bug #52769](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=52769) I think on Emacs 29 embark could add this command to the region map.

**Comment by oantolin** [comment]
Thanks to Embark's handy pre-action hooks, we can even bind now, before it's behavior with the region is changed. With this function as a pre-action hook it will act just on the target (and in a few years we can remove the hook):

```elisp
(cl-defun embark--restricted-to-target (&key action bounds &allow-other-keys)
  (cl-labels ((with-restriction (fn &rest args)
                (save-restriction
                  (narrow-to-region (car bounds) (cdr bounds))
                  (unwind-protect (apply fn args)
                    (advice-remove action #'with-restriction)))))
    (advice-add action :around #'with-restriction)))
```

It could be bound in `embark-paragraph-map`, as well as `embark-region-map`.

**Comment by oantolin** [comment]
Oh, I just realized we have a little redundancy: almost every binding in `embark-prose-map` is also in `embark-region-map`. I should make `embark-prose-map` the parent of `embark-region-map`.

There is just one binding that differs: in `embark-prose-map` the command `whitespace-cleanup-region` is bound to `s`; while in `embark-region-map` it is bound to `SPC`. Maybe we can settle on a single keybinding for both? I think `embark-region-map` also used to use `s` for that and `S` as the prefix for the `sort-*` functions. But we moved the `sort-*` functions to the `s` prefix and moved `whitespace-cleanup-region` to `SPC` (which is normally `mark`, but that's of course useless in the _region_ map).

**Comment by oantolin** [comment]
I added the binding "R" for repunctuate-sentences to both the paragraph and region maps, with that pre-action hook. I haven't done anything about making the prose map a parent to the region map because it isn't conceptually a parent and we don't want every conceivable binding in the prose map to be in the region map too, it's just a coincidence that all the existing ones work on regions.

**Comment by hmelman** [comment]
Great.  I'm not sure if it's viable but `.` seems like a particularly appropriate key to bind it too (or even `SPC SPC`) . 😄

**Comment by oantolin** [comment]
I wouldn't use `SPC SPC`, though I agree it would be appropriate because `SPC` marks a paragraph and cleans up whitespace in a region.

I very nearly went with `.`. I mainly didn't because since we recommend `C-.` for `embark-act` in the documentation, I thought maybe people would want to use `.` for `embark-cycle-key`. I have a similar set up: I use `C-;` for `embark-act` and `(setq embark-cycle-key ";")`, which is pretty nice because after the initial `C-;` I hardly ever need `C-` or `M-` modifiers, usually only shift.

I also somehow felt `.` was "too prime" a key for what is probably a fairly uncommon operation. I like `R` because it's not hard to type but it does use the shift key indicating this isn't likely to be a multiple-times-a-day command.

But we can definitely still change it to `.` if you think that's better. As I said, I very nearly used `.` anyway.
