### ISSUE TITLE
embark-act-all with multitargets on the fly

### ISSUE THREAD

**Issue by karthink** [oantolin/embark#447]
Just catching up with `embark-act-all` and `embark-multitarget-actions` here, Embark moves too fast!

I'm wondering if there might be an elegant way to switch between the two types of argument handling (one per command vs list of arguments to a single command) on the fly.

The inspiration for this is `dired-do-async-shell-command`, where 
- the command is called on each marked file in parallel
- when the command ends with `&`, the command is called on each marked file in sequence
- when the command ends with `*`, it is called once with all the marked files as arguments.

The first behavior is not available to Emacs for most actions. The second is the default behavior of `embark-act-all`. The third requires an entry in `embark-multitarget-actions`. I tried to choose between them on the fly by doing something like this:

```elisp
(defun my/embark-act-all-star ()
  (interactive)
  (let ((embark-multitarget-actions (list embark--command)))
    (call-interactively #'embark-act-all)))

(defalias 'my/embark-act-all-ampersand #'embark-act-all)

(define-key minibuffer-mode-map (kbd "C-x *") #'my/embark-act-all-star)
(define-key minibuffer-mode-map (kbd "C-x &") #'my/embark-act-all-ampersand)
```

But I couldn't get the star variant to work. (It was actually difficult to find a command where it makes a difference, but I'm mostly sure it doesn't work as intended now.)

In any case, do you think there's a more elegant way to switch between the two kinds of argument processing?

**Comment by minad** [comment]
Maybe you misunderstood the purpose of `embark-multitarget-actions`? The variable is used to configure the calling convention. When acting on multiple targets there is no other way than calling the action in sequence on each target, if the action accepts only a single target. Usually actions work like this since you inject a single target in the minibuffer. Special actions which want to receive all targets at once instead should be registered in `embark-multitarget-actions`. They will use a different special calling convention where no minibuffer injection is performed. Instead the targets are passed as argument. Therefore there is no point in dynamic toggling between these two modes. What exactly do you want to achieve? I am sure there is a way! :)

**Comment by minad** [comment]
However if one registers an action with `embark-multitarget-actions` then one could call the action either once with all candidates as list argument or with single candidate singleton list arguments in sequence. On this level one could then toggle the behavior.

But it seems to me that this is a special feature. I would approach this by writing two separate actions and bind them to different keys. One with the parallel/multitarget calling convention and one which receives the arguments in sequence. For which type of operation would you like such a toggling? If an operation can be parallelized I'd probably always use the parallel variant with multiple targets at once.

**Comment by oantolin** [comment]
I agree with @minad, this seems like a possible misunderstanding. It's pretty unlikely to have a function which can be called both ways: it would have to be non-interactive and callable with a single string argument or a single argument which is a list of strings. And furthermore, for the toggle to be necessary it would have to behave differently when called with a string than when called with a singleton list of that string. I really don't think there are natural examples of that.

**Comment by oantolin** [comment]
More generally we don't really have many examples of actions taking all arguments at once. That feature was added for use in the citar package and I think that's probably the only use made so far.

Since the introduction of embark-act-all I think the only all-targets-at-once actions I've been tempted to right are ones for files, that prompt for a directory and move or copy the list of files there. You can use copy-file or rename-file for this but then you are prompted for the destination for every single file!

**Comment by oantolin** [comment]
I'm closing this because I don't think it warrants any change in Embark, but as always, we can certainly continue the discussion.
