### ISSUE TITLE
Allow keeping (don't quit) the minibuffer when the pressed key isn't presented in the indicator

### ISSUE THREAD

**Issue by daanturo** [oantolin/embark#448]
Steps to reproduce:
1. Type a complex and long input in the minibuffer prompt
2. Invoke `embark-act`
3. Press a key that isn't recognized, such as `<down>` as `vertico-next`

Expected: 
While not quitting the minibuffer, either:
- The indicator disappears, `vertico-next` is either executed or not
- The indicator persists, `vertico-next` is not executed

Observed: 
The minibuffer command is aborted, typed input is lost.

**Comment by minad** [comment]
I don't see this issue with my configuration where I have set `embark-quit-after-action=nil`.

**Comment by daanturo** [comment]
But setting it to nil will take away the original behavior where calling a presented command would quit the minibuffer.

**Comment by oantolin** [comment]
This is intended behavior: in the scenario you describe you have `embark-quit-after-action = t`, right? Then embark will quit the minibuffer after any action you select, even if the action you select is `vertico-next` which is not very useful to run as an action.

Embark will let you execute any Emacs command as an action, not only the one listed in the embark keymaps. The keymaps are just for convenience, to give shorter keybindings to commands you are likely to want, but you are free to use any of your key bindings (like `<down>` for `vertico-next`) or even choose a command via `M-x`.

People have often asked me to make all commands not listed in Embark's keymaps "illegal", but I'm very insistent on keeping the freedom to run any command as an action.

**Comment by oantolin** [comment]
> 3\. Press a key that isn't recognized, such as `<down>` as `vertico-next`

The key point is that the key *is* recognized `<down>`  is not bound in Embark's own maps, but it is bound to _something_ in your configuration and Embark runs that command as the action. When a key is truly not recognized Embark prints a little `[Canceled]` message and does not quit the minibuffer.

**Comment by oantolin** [comment]
Mmh. There is one concession I made to people who want to restrict your freedom to use any command as an action: `self-insert-command`! I agreed to treat `self-insert-command` specially and not have it usable as an action (unless directly bound in an embark action map). Maybe instead of just `self-insert-command` we can add a user option of commands the user renounces as actions and prefers to be scolded when attempting to use them?

**Comment by minad** [comment]
That's a good idea. The "protected keys" should be undefined keys and self insert by default. But protecting certain additional keys also makes sense like the movement commands which one may press accidentally in Embark. On the other hand the user could just bind the keys in the general map and handle them in this way. It seems more flexible to just do this via the keymap or did I miss something?

**Comment by minad** [comment]
We also had the discussion about an additional transient map before. Maybe Embark could activate some `embark-prompt-map` while the keymap prompter is active and then the user can bind everything there. You could even bind all the self-insert-commands there. I am not sure how to do this, but then it is not a sparse keymap, right?

**Comment by oantolin** [comment]
I'm not sure bindings keys you don't want used as action in either `embark-general-map` or some new `embark-prompt-map` is such a good idea. First, what do you bind them to? A new `embark-not-an-action` command that just prints an error message? And no matter what you bind them to you'd still want to give them special treatment: you'd want to catch them in the keymap prompter so that they don't quit the minibuffer.
