### ISSUE TITLE
What to do about classifiers?

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#45]
Embark's symbol and package classifiers have been added to Marginalia now. I'd like to remove them from Embark to avoid duplication (I already removed everything to do with annotations!). I only want to remove the classifiers, not the actions or action keymaps.

Now, how important is it that Embark's package and symbol actions work out of the box?

- I could simply remove the classifiers and say "install Marginalia to get these actions to work".
- I could formally make Marginalia a dependency.
- Finally, I guess I could just keep the classifiers.

What do you think @minad?

**Comment by minad** [comment]
I would remove the classifiers. Otherwise we just duplicate work and this has to be kept in sync etc. If you keep them, would it interfere with marginalia (probably not since you don't overwrite categories here)? 

If you feel that the marginalia annotators are too fat, we could consider two things:

* Offer a marginalia-mode which only overwrites the categories (basically a linneaus-mode, but this is already achieved by setting the annotator to nil)
* Move the classifiers to a separate linneaus package

But I think marginalia is already pretty complete, robust and only 500 loc, so I think a dependency is not a problem at all. 

If you don't want to have a hard dependency, which is understandable, since it is kind of a weak dependency - as you said, simply state that actions only work for completions with correct completion categories. Unfortunately only few commands get it right and therefore you recommend marginalia - alternatively people can write their own completing-read functions with correct categories or custom minibuffer maps, if for whatever reason they want to avoid marginalia or want to control precisely where embark sets in.

It is a bit ideological but having no hard dependency is also somehow a selling point, that we have these kinds of pluggable components. And maybe some alternative to marginalia comes along?

Regarding actions and keymaps - I thought before, maybe these could be moved to some embark-action.el file and the core logic could be kept in embark-core.el.  This is a stylistic thing, if you rather have a large file or multiple files. But maybe the functions are also entangled and you cannot split them nicely like this?

**Comment by minad** [comment]
@oantolin I should add one thing - except you are unhappy with how marginalia turned out to be. I am pretty happy with it, so I moved all annotation stuff from consult.

But if you feel there is a problem with how marginalia works with regards to Embark, we should simply fix this. Maybe after working a while on Embark with the marginalia integration in mind, you found some design flaws?

**Comment by oantolin** [comment]
I am very happy with Marginalia, @minad!

I'm not seriously considering keeping the package and symbol classifiers in Embark, I just mentioned that option for completeness. I'd much rather remove them. (I do have to keep the other classifiers since they aren't about minibuffer completion so they can't be moved into Marginalia.)

The questions is do I just remove them? Then people without Marginalia can't use the package and symbol actions out of the box. Or do I remove them but make Marginalia a dependency? That way those actions are available out of the box.

Right now, since Embark isn't on MELPA yet I think I can break things and not feel too bad about it. So I think I'm inclined to just remove the classifiers and let people who use the package and symbol actions complain, and I will tell them to install marginalia to get them back.

**Comment by oantolin** [comment]
I do kind of like the no hard dependency rule between embark, consult and marginalia.

**Comment by minad** [comment]
> I do kind of like the no hard dependency rule between embark, consult and marginalia.

I do like that too. If you want to ensure that things work you could still make it a dependency and keep everything else as is, and if something changes, let's say Emacs suddenly fixes all completion categories, then you could reconsider and remove the dependency again. Or vice versa, I wouldn't think too much about breakage, since the current user base are more expert users as far as I see it.

And as I said, in the end people are probably going to use the packages together. And we are going to offer some default configs which help them plug things together, similar to what you already have in the embark wiki or in the selectrum wiki. So maybe this is not really worth thinking about it. When I think about working-out-of-the-box, Emacs certainly does not come to my mind :D 

E.g. Consult is specificially designed to not work out of the box for example regarding keybindings. I really prefer that way in contrast to older packages which predefine everything. Older packages always define their minor-mode and then force some keybinding onto you. Therefore also my proposal to split embark-core and embark-actions if that is possible.

**Comment by oantolin** [comment]
You know what? I'll be cautious about breakage after Embark is on MELPA, for now, I'll just remove the classifiers and rewrite the readme to recommend Marginalia.

> Therefore also my proposal to split embark-core and embark-actions if that is possible.

It is definitely possible. I'm not too sure it is a good idea. I do want Embark to offer some convenience out of the box. I think very few people use `embark-act` on actions *not* found in some `embark-*-map`. If the package isn't large (and I don't consider it large, and it just shrunk!) and almost everyone will use both parts, I don't think splitting is such a good idea. I can certainly split it later.

**Comment by minad** [comment]
> You know what? I'll be cautious about breakage after Embark is on MELPA, for now, I'll just remove the classifiers and rewrite the readme to recommend Marginalia.

This is a good idea. Furthermore, melpa also has melpa stable (not that I think it is a good idea), but as soon as I put a tag on the repository, I make it more clear that the package is somehow stable. I won't do that for a while for consult I think.

> It is definitely possible. I'm not too sure it is a good idea. I do want Embark to offer some convenience out of the box. I think very few people use embark-act on actions not found in some embark-*-map. If the package isn't large (and I don't consider it large, and it just shrunk!) and almost everyone will use both parts, I don't think splitting is such a good idea. I can certainly split it later.

A few points, why I like such splits:
* If a split is really possible such that you don't have mutual dependencies, it gives some large scale structure. As a reader I like that. Now with the annotations/classifiers moved to marginalia, this is already a big improvement. 
* In this case, I think embark-core and embark-action seem to have structurally different code - embark-core is about setting up everything, intricate logic etc. And embark-action is just a bunch of actions without inter-dependencies and keymaps. But maybe my superficial view at it is not correct? Consult for example is like embark-actions, only simple command stuff. Except consult--read and the preview code, this is the mess.
* Maybe someone wants to define their own keymaps, then it is easier if nothing is already there. But this would probably mean that you need three files embark-core, embark-action, embark-map. This is a weak argument. Probably no one would do it.

**Comment by oantolin** [comment]
Do you just mean internally split embark into two files and have a third that loads them both or do you mean two separate packages on MELPA?

**Comment by minad** [comment]
I meant separate files, no separate packages. If it turns out that a split on the package level makes sense, one could still do that later on. The terminology is a bit unclear here, since the elisp files are also called packages. Maybe (M)elpas should be called (M)elpas.

**Comment by oantolin** [comment]
Gotcha. Separate files is a trivial change. I can do it any time. Those two parts are already separated inside `embark.el`.

**Comment by oantolin** [comment]
OK, I pulled the trigger f17b3801cbb62a36648c0b177e989a9407ce97c6.

I think I just needed @minad to remove the last bit of doubt in my mind.

**Comment by oantolin** [comment]
Argh, one last bit of duplication: `embark-open-externally` is the same as `consult-file-externally`. 😆 

I'm so close, might as well remove that last tiny bit...

**Comment by minad** [comment]
Well. You might not want to have that dependency?

**Comment by oantolin** [comment]
I wouldn't make consult a dependency, I'd just remove the action.

**Comment by minad** [comment]
:+1: makes sense! I agree!

**Comment by oantolin** [comment]
Done. f883233376c86e52c48e40b8ad35aa928f89dec5
