### ISSUE TITLE
embark from embark-bindings

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/embark#450]
Often I'd like to see a subset of available key bindings.  `embark-bindings` (`C-h B` for me) is wonderful for this.  I can narrow down to just those bindings of interest.  But then often I want to use embark to _export_ those bindings to a buffer, as a snapshot.  Sadly this does not work, resulting in the user error `Not meant to be called directly`.

**Comment by oantolin** [comment]
I'm going to need a little help reproducing the problem, because here it seems to work just fine: I ran `embark-bindings`, then typed something to narrow the bindings, then ran `embark-export` and got a nice apropos buffer. I tried again with `embark-collect-snapshot` in place of `embark-export` and that worked too. Could you give me step by step instructions, preferably from `emacs -q` to reproduce the problem.

**Comment by jdtsmith** [comment]
I suspected this was already implemented!  

Here's how I just reproduced: start with `emacs -q`, then:

```elisp
(package-initialize)
(require 'embark)
(global-set-key (kbd "C-h B") 'embark-bindings)
(global-set-key (kbd "C-,") 'embark-act)
```

Then `C-h B` to "see" the list of bindings (which reminds me why I like vertico ;).  Then `C-,`.  This give me `user-error: Not meant to be called directly`

**Comment by oantolin** [comment]
Oh, the problem seems to occur only when `embark-cycle-key = nil`. (I set `embark-cycle-key` to the same key I use for `embark-act` but without modifiers in my personal configuration.) I'll look into it.

**Comment by oantolin** [comment]
Other workarounds:

- Bind `embark-export` to a key and use it directly from `embark-bindings`.
- Set `enable-recursive-minibuffers` to `t` and then use `M-x embark-export` from `embark-bindings`.

**Comment by oantolin** [comment]
That should fix it. Now it you have `embark-cycle-key = nil` and you use `embark-act` from within `embark-bindings` you should get a message that says "Cannot cycle; press C-, again to act". Any subsequent `C-,`s will be then intepreted as `embark-act`.

Here's the full story if you're interested:

There's a little design issue with the cycling functionality and the completing read prompter (which is relevant here because internally `embark-bindings` uses the completing read prompter). When `embark-cycle-key = nil`, you are supposed to be able to cycle among targets by repeating you `embark-act` keybinding. But in the completing-read prompter you may also want to be able to act on the completion candidates which are commands decorated with bindings.

Now, if a completing-read user has multiple targets then the their `embark-act` keybinding can either be used for cycling or for acting on the actions. So a `embark-completing-read-prompter` user who wants to be able to act on the actions in the multiple target case should either (1) set `embark-cycle-key` to something other than nil (or their binding for `embark-act`), or (2) should have `enable-recursive-minibuffers = t` to be able to `M-x embark-act` to act on the actions.

But there's an opportunity for even the `embark-cycle-key = nil` crowd to act on actions via key binding in the completing-read prompter in one case: when there is a single target there's no possible cycling so if the user presses the `embark-act` key bindings they must mean to act on the actions. However, since probably `embark-cycle-key = nil` users develop a strong muscle memory for "repeat embark-act" = "cycling", we decided that in the single target case the very first repetition of the embark-act binding would not act on the actions but print a message warning that there can be no cycling and that repeated presses will act on actions.

OK, so that's the slightly convulted design @minad and I wound up with while discussing his implementation of cycling. But we had a tiny bug in the implementation that you just discovered: the way the completing-read prompter checked if cycling was possible was to lookup the key used for cycling in the keymap passed to `embark-completing-read-prompter`. Now, in the `embark-cycle-key = nil` case this means looking up the user's binding for `embark-act` which it did find bound in the "all key bindings" map that `embark-bindings` uses! The correct check is not just whether the key is bound or not, but whether it is bound *to* `embark-cycle`; this is the one line fix in the above commit.

And now you know the whole story. :)

**Comment by jdtsmith** [comment]
Thanks for the full story. Hope it wasn’t too challenging to track down.  I guess I hadn’t considered that embark-bindings was _already_ an embark action.

**Comment by oantolin** [comment]
> Hope it wasn’t too challenging to track down.

No worries, it wasn't hard: since you pointed out that the error message came from `embark-cycle` I thought right away that the binding of the cycle key was the issue. Writing down the explanation took much longer than figuring out the problem and fixing it (😛), but I wanted it documented somewhere where I would be able to find it in the future.

**Comment by oantolin** [comment]
> I guess I hadn’t considered that embark-bindings was _already_ an embark action.

That's not really the problem, the bug was that to figure out if target cycling should be enabled, `embark-completing-read-prompter` just checked whether the embark-cycle key was bound in the keymap it prompts you about. That normally works, but if the cycle key is the same as the embak-act key *and* you happen to pass `embark-completing-read-prompter` a keymap where `embark-act` is bound (like the global keymap that `embark-bindings` works on), then `embark-completing-read-prompter` falsely gets the impression that target cycling should be enabled. And the fix is to not just check if the cyling key is bound, but also to check specifically whether it is bound to `embark-cycle`.
