### ISSUE TITLE
Add eww-open-file action

### ISSUE THREAD

**Issue by minad** [oantolin/embark#454]

**Comment by oantolin** [comment]
Good idea! We could refine `file` to `html-file` when the file has an `html` or `htm` extension, and have a keymap inheriting from `find-file` adding this action.

**Comment by minad** [comment]
> Good idea! We could refine `file` to `html-file` when the file has an `html` or `htm` extension, and have a keymap inheriting from `find-file` adding this action.

The refinement seems unnecessary to me. I think it only makes sense to
refine if there is a larger set of actions which are specific to a
target type. Therefore I would just add it to the file map for now.

**Comment by oantolin** [comment]
I agree, let's just add it to the file map. But I wanted to point out other potential reasons to want to refine: (1) to change the default action, and (2) to reduce clutter for people who use the verbose or which-key indicators (I haven't been too worried about this so far since I think the completing-read prompter mostly solves this problem). 

Is `h` (for html) a good binding for `eww-open-file`? Maybe `H` or `O` (for open)? The bindings `e`, `E`, `b`, `B`, `w` and `W` and `o`,  which I thought of first are all taken!

**Comment by oantolin** [comment]
I think I'll go with `h`. We can always change it later (but preferably soon, before people get used to it). Another option I thought of is to move eshell to `$` and use `e` for `eww-open-file` (but I'm not a big fan of changing old, established key bindings).

**Comment by minad** [comment]
> I think I'll go with `h`. We can always change it later (but preferably soon, before people get used to it). Another option I thought of is to move eshell to `$` and use `e` for `eww-open-file` (but I'm not a big fan of changing old, established key bindings).

Oh, I think I would like "$" for the shell! For "$" we have a slight
conflict with the ispell bindings. Alternatively use "%" or "#", which
are also common prompt symbols, but I prefer "$".

**Comment by oantolin** [comment]
I think I'd like `$` for eshell too (and I don't think the clash with ispell is problematic). I'll change it and use `e` for `eww-open-file`. One other thing I like about `$` is that it is more neutral: what I mean is that if someone prefers `shell` to `eshell` it makes sense for them to override `$`, but overriding `e` would fell weird for `shell` which doesn't start with `e`.

**Comment by oantolin** [comment]
Also, shell-command is on `!` and async-shell-command is on `&`, I think `$` fits better with those.
