### ISSUE TITLE
embark-act-multi error message: No candidates for export

### ISSUE THREAD

**Issue by minad** [oantolin/embark#458]
Should probably be "No candidates of a single type to act on"?

**Comment by oantolin** [comment]
I used "No candidates to act on" because you can still act even if not all candidates are of the same type, the difference is that you get a more generic keymap. For example, in `consult-buffer` if not all candidates are of the same type you get the embark-general-map. And at least `w` and `i` make sense (with the slightly unfortunate tofu at the end).
