### ISSUE TITLE
embark-act-multi: Indicator bug

### ISSUE THREAD

**Issue by minad** [oantolin/embark#459]
1. emacs -Q
2. Execute
~~~ elisp
(package-initialize)
(setq embark-quit-after-action nil
      embark-indicators '(embark-minimal-indicator))
(define-key minibuffer-local-map (kbd "C-.") #'embark-act)
~~~
3. `M-x C-. AAAAAAAAA`

**Comment by oantolin** [comment]
I love this! I'm tempted to call it an easter egg rather than a bug.

**Comment by minad** [comment]
The ∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀hhhh quantifier bug

**Comment by oantolin** [comment]
The problem was lexical scope! After `embark-act-all` you get a fresh new minimal indicator, and since the overlay was kept in a lexically scope variable, it came with a new overlay, so it didn't get correctly deleted. The verbose indicator, for example, uses a global location for its work: the buffer named `*Embark Actions*`, so subsequent fresh copies of the verbose indicator still display stuff in the same location.
