### ISSUE TITLE
Shouldn't 'last-command' be the dispatched command after 'embark-act'?

### ISSUE THREAD

**Issue by woolsweater** [oantolin/embark#460]
I see that `embark-act` binds `this-command` before dispatching, but it seems that the value of `last-command` still ends up being `embark-act` rather than the chosen action. To demonstrate:

```elisp
(defun test-action ()
  (interactive))

(defun check-last-command ()
  (interactive)
  (message 
   (pcase last-command
     ('test-action "Okay")
     ('embark-act "Not what I want")
     (_ "Something else entirely"))))

(define-key embark-general-map (kbd "x") #'test-action)

;; Target
```

I invoke `embark-act` on the "Target" comment, selecting `test-action`, then immediately invoke `check-last-command` (either via M-x, or optionally by adding a keybinding directly to it). The result is the `embark-act` case.

Is this the intended behavior? It seems like it would be preferable for `embark-act` to be "transparent" like `execute-extended-command`, since it is just a dispatcher.

**Comment by woolsweater** [comment]
Ah, I think it's because `this-command` is just `let`-bound rather than being actually _set_. It seems like this line https://github.com/oantolin/embark/blob/5faf1389162dd64bfe3511dfb8f52c18efb5140b/embark.el#L1845 should perhaps be swapped for `(setq this-command action)`. I tried this out locally, and `last-command` holds the actually executed command. I admit I don't know whether there are other consequences of this change, however.

**Comment by oantolin** [comment]
Thanks for diagnosing the problem! I will change to using `(setq this-command action)` , because as you say, `embark-act` is just a dispatcher. For example, `execute-extended-command` also sets `this-command` for the same reason. The docstring for `this-command` does not discourage setting it either: "The command can set this variable; whatever is put here will be in `last-command` during the following command."

**Comment by woolsweater** [comment]
Sounds great, thank you very much!
