### ISSUE TITLE
[feature request] Make  "*Embark Occur*" supporting wgrep for some special command 

### ISSUE THREAD

**Issue by jixiuf** [oantolin/embark#47]
Xref provides helpful commands for code navigation and discovery, such as `xref-find-definitions` and `project-find-regexp` ,and   `project-find-regexp` support `ripgrep` now( on emacs master) .

When a xref query hits multiple candidates Emacs shows a Xref
buffer with the various candidates and their location.

On emacs master, it support using `completing-read` showing the multiple candidates  now with `xref--show-defs-minibuffer`

https://lists.gnu.org/archive/html/emacs-devel/2020-11/msg00707.html

```
(with-eval-after-load 'xref
  (setq xref-search-program 'ripgrep)     ;default `grep`,  for project-find-regexp
  (when (functionp 'xref--show-defs-minibuffer)
    (setq xref-show-definitions-function 'xref--show-defs-minibuffer) ; using completing-read
    (setq xref-show-xrefs-function 'xref--show-defs-minibuffer)))

```
this is a screenshot of `project-find-regexp` in minibuffer
<img width="654" alt="image" src="https://user-images.githubusercontent.com/461743/101976673-a2392080-3c82-11eb-8278-f8768001e0be.png">

And I can export the result to   "*Embark Occur*" with `embark-occur` 

<img width="714" alt="image" src="https://user-images.githubusercontent.com/461743/101976721-f5ab6e80-3c82-11eb-9105-c9025e88b6ca.png">

So I think it is great for "*Embark Occur*" support `wgrep` like ivy-occur/grep,
I think https://github.com/minad/consult/issues/46 can benefit from it too, once consult-rg/ag is implemented.

**Comment by oantolin** [comment]
I wouldn't want to reinvent `wgrep` here. So I think the best option is to not use `embark-occur`, but rather make it so `embark-export` works with these functions you mentioned, and produces an actual grep buffer you can use with the standard wgrep.

**Comment by jixiuf** [comment]
it’s ok for me

**Comment by manuel-uberti** [comment]
I second @jixiuf enthusiasm on this. :)

**Comment by jixiuf** [comment]
```
(require 'wgrep)

;;;###autoload
(defun embark-occur-wgrep-setup ()
  (set (make-local-variable 'wgrep-header/footer-parser)
       'embark-occur-wgrep-prepare-header/footer)
  (wgrep-setup-internal))

(defun embark-occur-wgrep-prepare-header/footer ()
  (let ((beg (point-min))
        (end (point-min)))
    ;; Set read-only grep result header
    (unless tabulated-list-use-header-line
      (save-excursion
        (goto-char (point-min))
        (setq end (point-at-eol))))
    (put-text-property beg end 'read-only t)
    (put-text-property beg end 'wgrep-header t)
    ;; embark-occur-mode have NO footer.
    ))


;;;###autoload
(add-hook 'embark-occur-mode-hook 'embark-occur-wgrep-setup)

```
With this code, "*Embark Occur*" should support wgrep for `project-find-regexp` `xref-find-definitions` .

**Comment by manuel-uberti** [comment]
Thanks, but I am not able to save the changes with it. I can edit the Embark Occur buffer, replace something in it with `query-replace` and see the changes in the buffer, but I cannot "commit" the changes nor save the modified files. Am I missing something?

**Comment by oantolin** [comment]
I'm sorry I took so long, this turned out to be trivial to do!

I added an exporter for grep mode results, and I associated it to category `grep` because that's the category consult uses for `consult-grep`, `consult-git-grep` and `consult-ripgrep`. If you want to use the exporter for `project-find-regexp`, the easiest way is to install Marginalia, add `(project-find-regexp . grep)` to `marginalia-command-categories`, and activate `marginalia-mode` (same for any other commands you might

Once you've done that, running `embark-export` (which you can get as action `E` in `embark-act`) from one of these grepping commands, will produce a normal grep buffer. Then you can use `wgrep` on it as usual.

**Comment by oantolin** [comment]
Oh, I spoke to soon. The grep mode buffers produced by export seem to work fine as grep buffers (pressing `RET` on a link works, and next/previous-error works too), but wgrep doesn't seem to work on them, it makes the text read-only, which is the opposite of what you want.

**Comment by oantolin** [comment]
OK, I inserted a fake header into the exported buffer, and now wgrep works.

If wgrep accepts your pull request, @jixiuf, then we could remove this fake header.

**Comment by oantolin** [comment]
Please test, and reopen or file another issue if there is any problem.

**Comment by oantolin** [comment]
@jixiuf, I noticed that Emacs 28 will report `xref-location` as the category when prompting you in the minibuffer for a grep result. So you can add `(xref-location . embark-export-grep)` to `embark-exporters-alist` instead of configuring Marginalia as I described above. If you can confirm that adding `xref-location` works, I'll add it to the defaults in Embark. (My Emacs doesn't have these xref features yet).

**Comment by oantolin** [comment]
Quick update: Embark now uses the grep exporter for the `xref-location` category (instead of `grep`), so it should work with `project-find-regexp` out of the box now, as well as with the consult-*grep family of commands.
