### ISSUE TITLE
How to replace the current target with another value within an action?

### ISSUE THREAD

**Issue by rdrg109** [oantolin/embark#472]
I want to write an action that imply replacing the target at point with another computed value.

I've tried executing `(delete-region (region-beginning) (region-end))` and then inserting the value I want, but `delete-region` doesn't delete the whole target at point. I've also searched for functions in the embark default functions that do something similar. I found that functions in `embark-region-map` act on a region, so they require the region to be set beforehand, but I didn't find one that does what I'm looking: replace the target at point with another value without the region to be set beforehand.

Please note that I don't want to set the region beforehand. I know that If I did this, then `(delete-region (region-beginning) (region-end))` would work, but I don't want to do this because `embark` is capable of recognizing the boundaries of a target, so it must be capable of deleting those boundaries, but I don't know how to retrieve those boundaries from within an action.

I've written this minimal working example for you to test your possible solution to my question. In that example, the function`my-replace-number-with-three` should replace the target at point with `3`. As I mentioned, I've tried using `(region-beginning)` and `(region-end)` (see `my-replace-number-with-four`), but this doesn't always delete the whole target, because the region is not always the whole target at point.

```
(defun embark-target-number-at-point ()
  "Target the identifier of a wikibase item in any buffer"
  (when-let* ((number (thing-at-point 'number)))
    `(number ,number . ,(bounds-of-thing-at-point 'number))))

(push 'embark-target-number-at-point embark-target-finders)

(defun my-message-a (number)
  "Show a message of NUMBER prefixed with \"a\""
  (message "a: %s" (number-to-string number)))

(defun my-message-b (number)
  "Show a message of NUMBER prefixed with \"b\""
  (message "b: %s" (number-to-string number)))

(defun my-replace-number-with-three (number)
  "Replace number at point with number 3"
  ;; TODO: Do something that ensures that the number is deleted before
  ;; "3" is inserted. Recall that we want the whole number at point be
  ;; replaced with "3".
  (insert "3"))

;; The following is what I've tried, but using (delete-region
;; (region-beginning) (region-end)) doesn't always remove the whole
;; target.

(defun my-replace-number-with-four (number)
  "Replace number at point with number 4"
  (delete-region (region-beginning) (region-end))
  (insert "4"))

(embark-define-keymap embark-number-map
  "Keymap for Embark actions for dealing with numbers."
  ("a" my-message-a)
  ("b" my-message-b)
  ("t" my-replace-number-with-three)
  ("f" my-replace-number-with-four))

(push '(number . embark-number-map) embark-keymap-alist)
```

Any help is appreciated.

**Comment by oantolin** [comment]
It sounds like all you need is:

```elisp
(push (alist-get 'my-replace-number-with-three embark-pre-action-hooks)
      'embark--mark-target)
```

That way Embark will mark the target prior to running the action `my-replace-number-with-three`. This relies on the target finder reporting the correct bounds for the target, but your target finder does.

I'm closing because this requires no changes to Embark, but feel free to continue the discussion if needed.

**Comment by rdrg109** [comment]
@oantolin  Thanks for your quick answer, I really appreciate it. I have done what you suggested (see below)

```
(push '(my-replace-number-with-three embark--mark-target) embark-pre-action-hooks)
```
```
(defun my-replace-number-with-three (number)
  "Replace number at point with number 3"
  (delete-region (region-beginning) (region-end))
  (insert "3"))
```

This doesn't delete the whole target. I've noticed that the text that is replaced by 3 is the cursor position and the last mark set, but not necessarily the whole target. Am I doing something wrong?

Here's some text to test possible solutions:

```
| 123 | <- number needs to be replaced with 3
| 123456 | <- number needs to be replaced with 3
| 123456789 | <- number needs to be replaced with 3
```

**Comment by oantolin** [comment]
Odd! Does your target finder highlight the number correctly?

**Comment by oantolin** [comment]
Ah, that's the problem! `(bounds-of-thing-at-point 'number)` doesn't actually work, it just returns `nil`! You can either fix that (thing-at-point is extensible, I think there is a way to provide your own bounds function for numbers), or replace it with code of your own that correctly reports the bounds.

**Comment by rdrg109** [comment]
@oantolin You are right, `(bounds-of-thing-at-point 'number)` wasn't getting the boundaries. I'm now using `org-in-regexp` (from Org Mode) as it follows `(org-in-regexp "[0-9]+")` and it works like a charm. Here's the complete snippet for those interested.


```elisp
(defun embark-target-number-at-point ()
  "Target the identifier of a wikibase item in any buffer"
  (when-let* ((number (thing-at-point 'number)))
    `(number ,number . ,(org-in-regexp "[0-9]+"))))

(push 'embark-target-number-at-point embark-target-finders)

(defun my-message-a (number)
  "Show a message of NUMBER prefixed with \"a\""
  (message "a: %s" (number-to-string number)))

(defun my-message-b (number)
  "Show a message of NUMBER prefixed with \"b\""
  (message "b: %s" (number-to-string number)))

(defun my-replace-number-with-three (number)
  "Replace number at point with number 3"
  (delete-region (region-beginning) (region-end))
  (insert "3"))

(defun my-replace-number-with-four (number)
  "Replace number at point with number 4"
  (delete-region (region-beginning) (region-end))
  (insert "4"))

;; Using `push' because we are sure that there isn't an alist whose
;; car is any of `my-replace-number-with-three' or
;; `my-replace-number-with-four'.

(push '(my-replace-number-with-three embark--mark-target) embark-pre-action-hooks)
(push '(my-replace-number-with-four embark--mark-target) embark-pre-action-hooks)

(embark-define-keymap embark-number-map
  "Keymap for Embark actions for dealing with numbers."
  ("a" my-message-a)
  ("b" my-message-b)
  ("t" my-replace-number-with-three)
  ("f" my-replace-number-with-four))

(push '(number . embark-number-map) embark-keymap-alist)
```

**Comment by rdrg109** [comment]
@oantolin I have a suggestion for you: Would it be feasible to change the core code of Embark in a such a way that actions can obtain the known boundaries of the target? I think this would give more flexibility to the user and avoid having to maintain a list of functions in `embark-pre-action-hooks` for that sole purpose.

As we could see in the solution posted above, it is necessary that `embark--mark-target` is executed beforehand, which is accomplished by adding a list to `embark-pre-action-hook` which adds some extra work. This could be avoided if the boundaries of the current target (which are already known thanks to the target finder) are passed to the action as a function parameter.

**Comment by minad** [comment]
> This could be avoided if the boundaries of the current target (which are already known thanks to the target finder) are passed to the action as a function parameter.

No, this wouldn't work since Embark uses a minibuffer injection mechanism to pass the target to the action. See https://github.com/oantolin/embark/#how-does-embark-call-the-actions for details. I recommend you read through the entire Embark documentation, in particular if you are interested in implementing your own actions. There is a lot of valuable information there.

Now the question is - why does Embark jump through these hoops via its target injection mechanism instead of just passing the target and bounds as function arguments? There is a good reason for this: Embark allows you to reuse any interactive command as action! Every command which reads from the minibuffer can be used as Embark action as is without an additional wrapper. The code reusability enabled by this design is amazing. If you look at the Embark keymaps, almost all the default actions are normal commands. Personally I find the target injection idea by Omar brilliant! :)

**Comment by oantolin** [comment]
I agree with everything that @minad said. I don't want to change Embark's calling convention @rdrg109, and the current one is sufficiently flexible, thanks to the pre-action, target injection and post-action hooks.

The idea behind of Embark's calling convention is that you should almost never need to write a function that is only useful with Embark. The vast majority of the actions bound in the Embark's keymaps in the configuration that comes with Embark are pre-existing built-in Emacs commands. Those were written long before (decades in some cases!) Embark existed and can be used as is! If Embark insisted in passing target bounds as arguments to actions for almost all of those function we'd have to write a trivial little wrapper that ignores the bounds and calls the wrapped command for every single one of those commands!

This idea of reuse goes the other way too: whenever I'm writing a function I intend to use as an Embark action I ask myself, "Is there any way I can make this into a command that is useful on its own, without being called from Embark as an action?" The answer is almost always yes. Maybe in your example you discover you sometimes want to mark a region and call `my-replace-number-with-three` (for example, maybe you notice sometimes you want to only replace part of the number at point with 3, not the whole number). To allow for that use case I'd write `my-replace-number-with-three` as a normal command:

```elisp
(defun my-replace-number-with-three (start end)
  "Replace region with the number 3"
  (interactive "r")
  (delete-region start end)
  (insert "3"))
```

This means you can now call the action from outside Embark with `M-x` or assign it a key binding, and of course you can still use it as an Embark action (still using the `embark–mark-target` pre-action hook).

Now, @minad is right to say that while there is no changing how Embark calls actions which are commands (i.e. are `interactive` functions), we could conceivably change how Embark calls functions which are not commands, adding the bounds as arguments in that case. I still would rather not do that. I think of non-command functions used as Embark actions as a niche case and wanting to know the bounds of the target seems to be a tiny niche within that niche. I currently have only 7 non-command Embark actions bound in my personal configuration:

- `bookmark-edit-annotation`
- `bookmark-show-annotation`
- `browse-url-default-browser`
- `citar-run-default-action`
- `kill-new`
- `mark`
- `pocket-lib-add-urls`

I didn't write any of those functions: one comes from pocket-reader package, one from the citar package and the other 5 are built-in to Emacs (the ones built-in to Emacs are bound in Embark's default configuration). In each case I was able to use the function as is! If we instead passed bounds to non-interactive actions I would have needed to write 7 trivial wrappers that discard the bounds and call the underlying function. I think the current calling convention does a great job of letting you reuse existing functions and adding the bounds to the call would definitely spoil that.

Now, I guess you could argue that Embark could _detect_ whether a function takes a single argument and in that case call it with the target string only, but if the function can accept more than one argument it could call it with the target string and the bounds. But this seems like an unnecessary complication to me: the full Embark calling convention already takes a few minutes to explain, it doesn't need to be even more complicated! And a simple `embark--mark-target` pre-action hook can bridge the gap, so why complicate matters further?

Finally, not all useful targets have bounds! The main example are targets that are minibuffer completion candidates if you are using a completion UI that (1) does display the completions, but (2) not in a dedicated buffer. Examples of completion UIs like that include Vertico, Icomplete and Selectrum. But there are other examples, for instance I have a low-priority target which represents the entire buffer. I would find highlighting of the entire buffer pretty annoying, so I simply don't return bounds for that one.

**Comment by oantolin** [comment]
By the way, we should file a bug report about `(bounds-of-things-at-point 'number)`. Do you want to that @rdrg109?

**Comment by oantolin** [comment]
(Oh, including `mark` in the list of non-interactive functions bounds as Embark actions is cheating: that one does use an `embark--mark-target` pre-action hook and indeed the pre-action hook does all the work! But the point stands with the other 6 functions.)

**Comment by oantolin** [comment]
Is leaking the text properties really so bad? I kind of like this idea. I feel we probably didn't use it mostly because `completing-read` strips text properties so this way of including metadata wouldn't work for command actions, but it does work just fine for non-interactive actions and is maybe more convenient that handling type an bounds specially.

**Comment by minad** [comment]
> Is leaking the text properties really so bad? I kind of like this idea.

Maybe it is not. It should be quite easy to convert this. We can still support old style target finders which return a cons for a transitional period, printing a warning.

>  I feel we probably didn't use it mostly because completing-read strips text properties so this way of including metadata wouldn't work for command actions

Maybe we refrained from using text properties more widely because of `completing-read`. I think we strip text properties before minibuffer injection, which is the correct thing to do and we should continue to do this. Using text properties would only be useful for non-interactive actions.

**Comment by minad** [comment]
Also the target finder and transformer code can probably be changed to work purely with text properties instead of the plist we use now:

https://github.com/oantolin/embark/blob/1bedea7531c749c8131928b39889db9a8ad0da5b/embark.el#L1928-L1932

**Comment by minad** [comment]
But @oantolin I am still unsure of the overall advantages of such a change:

- This will likely result in more code.
- Function actions get access to the metadata. Do we have examples where this simplifies things? Do we have examples where an action would benefit from the properties?

**Comment by oantolin** [comment]
Very good questions! I think the answer has to be no. There are really only two pieces of metadata: the type and the bounds. The type is not really useful unless you have an action that (1) is used for more than one type of target, but (2) does different things for different targets. As for the bounds, we do use them a lot to either mark the region or position point at one end or other of the target. But all of those uses are done through pre-actions because they reuse existing commands which expect those preconditions.

And for stuff like marking the target I even think that handling it in a pre-action hook is _better_ than having the action uses the bounds directly even for actions you write since it allows you to write the action as a normal Emacs command that might be useful independently.

So yeah, it's probably not a _useful_ change to make. I think what I find attractive about the idea is that it packages the target and its metadata in a single object for which the metadata is easy to ignore. The bit about being able to treat the whole thing as just a string instead of having to extract the string with `car` or `(plist-get :target _)` sounds nice. But this is just a small internal cosmetic matter that isn't really important.

**Comment by minad** [comment]
> So yeah, it's probably not a useful change to make. I think what I find attractive about the idea is that it packages the target and its metadata in a single object for which the metadata is easy to ignore. The bit about being able to treat the whole thing as just a string instead of having to extract the string with car or (plist-get :target _) sounds nice. But this is just a small internal cosmetic matter that isn't really important.

While this is indeed attractive text properties also have downsides: They makes the whole thing less obvious, since text properties are often ignored and overlooked. I would probably not make this change if there is no clear benefit, e.g., a reduction in the amount of code. In my https://github.com/oantolin/embark/issues/472#issuecomment-1074074964 I only wanted to mention the option to use text properties for completeness, not because I think that it is a significantly better design. But I believe it would be a better design than passing additional metadata as separate action arguments as originally proposed in  https://github.com/oantolin/embark/issues/472#issuecomment-1073916091.

**Comment by rdrg109** [comment]
> @minad: The code reusability enabled by this design is amazing.

> @ontolin: The idea behind of Embark's calling convention is that you should almost never need to write a function that is only useful with Embark.

True. I didn't consider that when making the suggestion. Before knowing Embark, I've been using the opposite convention: create functions tailored to the completion framework that I'm using and I've realized that this opposite convention implies much more extra work when tweaking my system.

> By the way, we should file a bug report about `(bounds-of-things-at-point 'number)`. Do you want to that @rdrg109?

@oantolin , yes, I've already done it. You can find the bug report here: #54555 ([message in the archive here](https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-03/msg01041.html)).

@minad @oantolin Thank you both for the thoroughly discussion around the suggestion I made (especially, since both of you have developed the packages under discussion). Your opinions and thoughts have helped me to understand the principles of these packages which will allow me to better integrate my functions to the core of these packages. I'm sure this will also help those users that find this issue.

I hope this discussion results in an improvement of these packages that can ultimately benefit the Emacs community.
