### ISSUE TITLE
What's the intended purpose of embark-live?

### ISSUE THREAD

**Issue by mohkale** [oantolin/embark#481]
It looks like after some recent refactoring `embark-collect-snapshot` has been removed and the two seperate `embark-collect-live` functions have been combined into `embark-live`. Firstly I'd like to ask why was the snapshot function removed? I sometimes use it when I'd like to move from a minibuffer to a regular buffer without any completion-specific conversions (such as find-file exporting into a dired buffer when I just wanted a list of all the candidates as is). Secondly what's the intended purpose of `embark-live`? I'll admit I've never really used the old collect-live functions so I'm not sure what this new one does. It looks like it pops open a buffer with all the completion candidates and leaves you in the minibuffer so you can continue searching and changing it. That's cool. But since with vertico the minibuffer is still active and showing candidates I end up seeing a duplication of candidates in the embark-live buffer and the minibuffer which makes me think that's not what this is for. Could you clarify this?

**Comment by minad** [comment]
Actually this refactoring was mostly about simplifying the code base. The commands have been renamed, embark-collect-snapshot to embark-collect and embark-collect-live to embark-live.

**Comment by mohkale** [comment]
> The commands have been renamed, embark-collect-snapshot to embark-collect and embark-collect-live to embark-live.

Ah you're correct. Thanks.

I'm still not sure on the intended usage of embark-live, is it documented somewhere?

**Comment by minad** [comment]
The important function is embark-collect. The renaming was about emphasizing this. Embark-collect is the one you want to use to collect minibuffer candidates.

Embark-live is an auxillary function based on embark-collect. Its purpose is to create a live updating candidates buffer. This is useful if you don't use Vertico or if you run it from a normal buffer. There it produces a live updating table of contents.

The README should be updated to document this. See also #407.

**Comment by mohkale** [comment]
> This is useful if you don't use Vertico or if you run it from a normal buffer.

Ah, that makes sense. Thanks :-).

**Comment by oantolin** [comment]
Ha, I wrote a long reply that basically just repeats @minad's too comments, which I hadn't seen.

Maybe I'll just emphasize that `embark-collect` is the old `embark-collect-snapshot` with a new sleeker name and is the main command of the two, and that  `embark-live` has two main use cases:

- From the minibuffer use it instead of `embark-collect` when (1) you do want to get an Embark collect buffer in the end, but (2) you are using a completion UI that does not show you the candidates and their annotations. Examples of (2) including default tab completion but also Vertico in unobtrusive mode, for example.

- From text (markdown, Org, etc.) or programming buffers it produces the live updating table of contents that @minad mentioned. In dired buffers it would produce a live updating list of marked files, which can be useful in a really long dired buffer where you've only marked a few files, so you can see the marked files together at a glance. And of course, feel free to implement whatever candidate collector is appropriate for the buffers you work with and use `embark-live` to get a live updating list of those things. For example, maybe you use @minad's amazing osm package to view maps, but would like to see a sidebuffer with your recent location searches.
