### ISSUE TITLE
embark-act on keywords in emacs-lisp buffer sometimes thinks it's a file

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/embark#530]
When I embark-act on some keywords in my `.emacs` (like the commonly used use-package keyword `:custom`), very oddly the first target type is the file `custom.el.gz`.  This is _not_ the case when acting on the same keyword in other buffers, like `*scratch*`.  

I tracked it down and `ffap-file-at-point` (used by `embark-target-file-at-point`) is the culprit.  It thinks `:custom` is a file, because of this "fallback" alist item of `ffap-alist`:

```elisp
 (emacs-lisp-mode . ffap-el-mode)
```

What happens specifically is that ffap strips the leading colon (`:custom` -> `custom`), here:

```elisp
	 ;; If it contains a colon, get rid of it (and return if exists)
	 ((and (string-match path-separator name)
	       (setq name (ffap-string-at-point 'nocolon))
	       (> (length name) 0)
	       (ffap-file-exists-string name)))
```

finds no files matching "custom", then eventually (via the above alist entry), calls `(ffap-locate-file "custom" '(".el") load-path)`, which returns `custom.el.gz` among the native libraries bundled with emacs.   Sigh.  

So maybe this should be considered an ffap bug, and it should not strip any _leading_ colons, but who knows who relies on this strange behavior.  Not sure the best place to work around this.  Perhaps demote `embark-target-file-at-point` below `embark-target-identifier-at-point` in `embark-target-finders` (or maybe not: a real file name is apparently also an identifier).

**Comment by jdtsmith** [comment]
Could just remove the offending alist item:

```elisp
(use-package ffap
  :init
  (assoc-delete-all 'emacs-lisp-mode ffap-alist))
```

**Comment by oantolin** [comment]
I agree that the right place to fix this is in ffap. It looks to me like the reason it tries to interpret the string without the colon as a file is because of colon-separated paths found in, say, shell scripts. But `:custom` shouldn't really count as colon-*separated*: it just has an initial colon! On the other hand, the current rule probably works well for Common Lisp where `:foo` does designate the `foo` library in some contexts.

**Comment by oantolin** [comment]
I wouldn't remove the `emacs-lisp-mode` entry from `ffap-alist` since I do want its services performed in most cases. It would be nice to work around this in `ffap-el-mode`, but by then the information that the thing had a leading colon is lost, which makes it awkward. This is a little ugly because it calls `ffap-string-at-point` again, but seems to work:

```elisp
(defun ffap-el-mode (name)
  ;; If name == "foo.el" we will skip it, since ffap-el already
  ;; searched for it once.  (This assumes the default ffap-alist.)
  (and (not (string-match "\\.el\\'" name))
       (not (equal (ffap-string-at-point) (concat ":" name)))
       (ffap-locate-file name '(".el") load-path)))
```

**Comment by oantolin** [comment]
So the above workaround can just go in our personal configurations (probably best not to redefine the `ffap-el-mode` function but instead to make a new function with that definition and replace the `ffap-alist` entry), but as a fix for `ffap` what I'd do is change the `(string-match path-separator name)` check to `(string-match (format ".%s." path-separator) name)`. (And maybe to keep the desirable leading colon behavior for Common Lisp, I'd add a separate entry to `ffap-alist` that tries stripping the leading colon.)

**Comment by oantolin** [comment]
At any rate, I'm closing because I don't think this should be handled at the embark level.

**Comment by oantolin** [comment]
Ah, I think I misjudged when the alist entry is used and maybe your idea of simply removing the `emacs-lisp-mode` entry is just as good as the function I wrote.
