### ISSUE TITLE
perserve position when operating the target as a region

### ISSUE THREAD

**Issue by ilupin** [oantolin/embark#563]
Hi, 

When I execute region commands on some targets (e.g. expression/sentence/paragraph), the original position is lost after execution.

1. place point inside an expression or a sentence/paragraph
2. M-x embark-act and press TAB for expression (i.e. indent-region) or l for sentence/paragraph (i.e. downcase-region)
3. the point goes to the beginning of the target

It is very inconvenient when you still need to edit at original position. Even if I set a mark, the mark is also lost and I cannot jump back with `pop-to-mark-command`. Maybe embark can wrap related commands with `save-excursion`?

**Comment by oantolin** [comment]
It should definitely be at least made easy for users to configure this behavior. I think this calls for the around-style actions hooks proposed by @DamienCassou in #518.

**Comment by oantolin** [comment]
I wrote an initial implementation of around hooks in a separate branch called around-hooks. I want to test more before merging, and would appreciate it if you tested it too, @ilupin.

In that branch I included an `embark--save-excursion` around hook, but I did *not* configure any actions to use it by default. I was hoping maybe you could suggest which actions would benefit from having it. I guess the actions you mentioned originally, but any others too?

**Comment by ilupin** [comment]
I find `(push '(indent-region embark--save-excursion) embark-around-action-hooks)` doesn't work because `embark--mark-target` in pre-action hook is executed before  `embark--save-excursion`. I have to remove `embark--mark-target` from the pre-action hook and mark the target inside `embark--save-excursion`.

After checking region-related actions used by non-region targets, I think at least `indent-region capitalize-region downcase-region upcase-region fill-region` should use `embark--save-excursion` by default. `ispell-region whitespace-cleanup-region count-words-region` could use it too, and in this case `embark--unmark-target` should be used when the target is not region.

I also suggest that all actions currently using `embark--mark-target` in pre-action hooks can be replaced with `save-mark-and-excursion + mark-target` in around hooks, because `embark--mark-target` always changes previous mark and moves the point to the beginning of region.

**Comment by oantolin** [comment]
Thanks for testing, @ilupin! I think I like the pre-action hooks running before the around hooks, so that the around hooks wrap only the action by itself. (Maybe the best system would be like the advice system where around, before and after hooks would all be on a single list and the order in that determines in what order they execute, but I think I prefer the simpler change I implemented.)

So if we keep the current strategy, then I think the best thing to do to solve the problems you noticed is to turn `embark--mark-target` into an around hook and have it also `save-excursion`. I don't think anybody will want a version of `embark--mark-target` that does _not_ `save-excursion`, but if someone says they need it they can certainly put it in their own configuration and if the use case seems important enough we can add it to embark. I'll tweak the default configuration in the around-hooks branch and report back.

**Comment by ilupin** [comment]
> So if we keep the current strategy, then I think the best thing to do to solve the problems you noticed is to turn `embark--mark-target` into an around hook and have it also `save-excursion`.

I agree! Maybe it is better to use `save-mark-and-excursion` if the new `embark--mark-target` changes previous mark.

**Comment by minad** [comment]
@oantolin I would keep the current order, pre, around, post and not depend on the order of the list. This would only introduce weird and hard to debug side effects when users start to manipulate the list. However it may make sense to unify the customization variables in order to avoid customization variable proliferation. What about using an alist of plists?

~~~ elisp
(defvar embark-action-hooks
  '((eval-last-sexp :pre embark--end-of-target :post ... :around ...)
    (indent-pp-sexp :pre embark--beginning-of-target)
    (backward-up-list :pre embark--beginning-of-target)
    ...))
~~~

**Comment by minad** [comment]
Hmm, but we already support multiple hooks. Then it would get quite ugly.

~~~ elisp
(defvar embark-action-hooks
  '((eval-last-sexp :pre (embark--end-of-target) :post ... :around ...)
    (indent-pp-sexp :pre (embark--beginning-of-target))
    (backward-up-list :pre (embark--beginning-of-target))
    ...))
~~~

Another alternative would then be a list where we specify for each hook if it is pre, post or around.

~~~ elisp
(defvar embark-action-hooks
  '((eval-last-sexp (:pre . embark--end-of-target) (:post . ...))
    (indent-pp-sexp (:pre . embark--beginning-of-target))
    (backward-up-list (:pre . embark--beginning-of-target))
    ...))
~~~

Maybe sticking to three variables is indeed simpler then. But I have two concerns with the three variables: 1. since the configuration is scattered, we cannot easily see all the installed hooks for a command. 2. Embark has so many variables already. I prefer if we can unify common ones together.

**Comment by DamienCassou** [comment]
> I wrote an initial implementation of around hooks in a separate branch called around-hooks.

I think the reference to `embark--cd` must be updated in embark-consult.el.

**Comment by oantolin** [comment]
You're right, thanks @DamienCassou.

**Comment by oantolin** [comment]
After some more cleanup and testing I merged the around hooks branch. I really like that the new `embark--mark-target` restores point, @ilupin! I hadn't noticed I wanted that behavior. One case that came up for me a lot was marking an s-expression or defun to reindent it, and that used to leave point at the start of the expression.

**Comment by oantolin** [comment]
For now I left things with an added variable, @minad, but you're right that I should consider consolidating the hook variables into a single one.
