### ISSUE TITLE
Integration with xah-fly-keys 

### ISSUE THREAD

**Issue by Cletip** [oantolin/embark#579]
Hello !

# Problem
As you know, embark allows to launch commands depending on the context. Moreover, these commands are mapped on keys.

So my problem is : how to do if I don't have the same keyboard ? For example, if I use dvorak?
Yes, the keys will always be on the same letters, but not at the same place for the muscle memory. So, if one day you want to change the layout of your keyboard, your muscle memory is useless.
So it would be necessary to be able to define a kind of variable allowing to choose a keyboard, and then load embark with no more keys such as "k" which is the `"k" `key, but rather `(the-function-that-translates-the-key-with-the-keyboard "k")` which would return the letter at the k location.

A concrete example:
`(setq variable-for-keyboard "azerty") ;; default keyboard is qwerty`
`(the-function-that-translates-the-key-with-keyboard "q") ;; return "a", because on the letter "q" in qwerty, it is "a" in azerty`

And if, one day, you change your keyboard, you just have to modify a variable and here we go again!

# Resolution

As for the implementation of this problem, I suggest to use the functions of the [xah-fly-keys](http://xahlee.info/emacs/misc/xah-fly-keys.html) packages, which do exactly what I just said (the only difference is that the default keyboard is dvorak and not qwerty).

All you have to do is this: 
- add a dependency to xah-fly-keys
- call the function `(xah-fly-keys-set-layout "your-keyboard")` to choose the keyboard. Many keyboards are available. Moreover, if the user forgets, the basic keyboard is qwerty
- modify in the macro `embark-define-keymap` the variable "key" like this : `(setq key (xah-fly--convert-kbd-str (kbd key)))`. xah-fly--convert-kbd-str is the function which allows to make the famous conversion according to the chosen keyboard.
- make query-replace in embark.el to transform the letters from qwerty to dvorak, and thus keep the same location

What do you think?
I'm thinking of making my own branch, is that a good idea?

**Comment by minad** [comment]
Depending on `xah-fly-keys` is not an option. But you could create a `xah-embark` package, which implements the integration you are seeking.

**Comment by Cletip** [comment]
Thank you for your answer
Can I know the reason for not having an addiction? The user could just have a variable to set to say "I want to use "extension" with xah-fly-key" no?

No worries, I think I will make a package. The only problem is the following: I have to define the new macro after the original macro. But if I do that, I have to reload the keymap with the right keys. I don't mind, but if one day you change the location of a key, I won't be able to know it automatically (there will be no conflict). I thought of making a branch based on the main branch of embark. That way, if a key is changed, it's supposed to be confused. 
What do you think about it?

**Comment by minad** [comment]
First, let me say that I am just a contributor to this package and I am not speaking for the author @oantolin.

From my understanding, the philosophy of Embark and the other packages which interact with it (Marginalia, Orderless, Vertico, Consult, ...) is that stick to default facilities and try to avoid additional dependencies. Most users of these packages don't and won't use xah-fly-keys. Therefore integration is best provided as a separate package xah-embark, which depends on both xah-fly-keys and embark. Furthermore since probably none of the current contributors to Embark uses xah-fly-keys it is hard to maintain proper integration. This is a general problem which applies to many packages in Emacs, also Evil. If Evil integration is needed into a package quetzalcoatl it is best done separately as evil-quetzalcoatl, since the quetzalcoatl may not be familiar enough with evil.

> The only problem is the following: I have to define the new macro after the original macro.

I think it should be possible to implement your integration without modifying or overriding the macros. Instead you should use the advice mechanism to modify functions at the runtime. Keymaps can also be changed dynamically at runtime, as soon as your package is loaded after Embark.

**Comment by Cletip** [comment]
> From my understanding, the philosophy of Embark and the other packages which interact with it (Marginalia, Orderless, Vertico, Consult, ...) is that stick to default facilities and try to avoid additional dependencies. Most users of these packages don't and won't use xah-fly-keys. Therefore integration is best provided as a separate package xah-embark, which depends on both xah-fly-keys and embark. Furthermore since probably none of the current contributors to Embark uses xah-fly-keys it is hard to maintain proper integration. This is a general problem which applies to many packages in Emacs, also Evil. If Evil integration is needed into a package quetzalcoatl it is best done separately as evil-quetzalcoatl, since the quetzalcoatl authors may not be sufficiently familiar with evil.

I understood perfectly and I understand why, thank you.

And why not just make a package that allows to do the bare minimum about these features: create a "keyboard"/conversion table, a variable to choose a keyboard, a function taking a letter and converting it taking into account the chosen keyboard.
Would it be useful to make this package as a dependency in embark ?
It would not change anything from the user's point of view, would not add any other function, but it would allow the user to choose his keyboard. 

I don't want to force the integration of this feature in embark, I'm just trying to understand why a package should be created, or not ^^

> I think it should be possible to implement your integration without modifying or overriding the macros. Instead you should use the advice mechanism to modify functions at the runtime. 

a little like that ? 
(advice-add #'embark-define-keymap :override #'my-version-of-embark-define-keymap)

>Keymaps can also be changed dynamically at runtime, as soon as your package is loaded after Embark.

Yes, I understand that it is dynamic. The problem is that if I rewrite the "embark-define-keymap embark-X-map" with my own keys, if one day you add for example a function to an embark-X-map, I would not be able to see it. I would have to add things by hand by looking at every commit made.
Do you know what I mean by that?

**Comment by Cletip** [comment]
> Also no. Embark just uses the mechanisms used in Emacs, so if you need remappings you have to apply them in Emacs itself and Embark. There is no point that Embark should be treated specifically. You should see Embark on the same level of Emacs (or slightly above). Any further integration/modification package should then sit on top.

Ok ok I understand perfectly. So I'll think about doing a package on the side.

> My proposal is that you don't override the keymap but instead modify it dynamically. Remove the keys you don't like and add the keys you want. You could define a function `(xah-embark-remap KEYMAP FROM TO)` which maps the key FROM to the key TO in KEYMAP.


Yes, but once I've done this function, I'll have to call it on all the keys (if I want to change them all). I don't find this very practical.

**Comment by minad** [comment]
> Yes, but once I've done this function, I'll have to call it on all the keys (if I want to change them all). I don't find this very practical.

You can probably define some more convenient helpers, which take lists of keys. But there is no other solution - if you want different keys, you have to change them one by one.

**Comment by Cletip** [comment]
Ok,  thanks you again for all your answer.

So I'm hesitant to do these things: 
- create a personal branch where I add the functionality of create a "keyboard"/conversion table, a variable to choose a keyboard etc, and change all the letters to match the basic keyboard. That way, if a key is changed, when I do a merge with master, I will have a conflict
- create a separate package to manage the keyboard
- create a separate package with a dependency to xah-fly-keys
- 
I prefer that oantolin close the issue himself to have an opinion, but I think this issue is finished. Thanks!

**Comment by oantolin** [comment]
As usual @minad got here faster than I did. :) I agree with pretty much everything he said. This functionality of changing keybindings based on keyboard layout is out of scope for Embark, but if you want it I do encourage you to make a package that depends on Embark and provides that functionality (possibly by also depending on xah-fly-keys).

The key bindings in the default configuration for Embark are provided in the same spirit as Emacs's key bindings:

1. They are just a suggested default: it is expected that most users will keep most of them, that many users will change some of them, and that many users will add some of their own; a few users will probably want to throw all of them out make their own.

2. They are not chosen for their *location* on the keyboard but because the character chosen has some mnemonic value (so, personally, I don't actually think it makes much sense to move them to a different character based on the layout, since you'd loose the mnemonic value, but of course feel free to move them if it makes sense for you!).
