### ISSUE TITLE
`embark-define-keymap' still mentioned in ELPA docs

### ISSUE THREAD

**Issue by jdtsmith** [oantolin/embark#589]
[Here](https://elpa.gnu.org/packages/doc/embark.html#Creating-your-own-keymaps).

**Comment by oantolin** [comment]
I think that since I bumped the version number the new docs will get picked up on the next build.

**Comment by minad** [comment]
Not anymore :)

**Comment by jdtsmith** [comment]
OK, now you may have the impression that I stalk your docs ;).  But the consult-info upgrade (already a top 5 consult command for me!) lead to the need to upgrade embark, since the version I had from last July wasn't producing functional consult-info collections.  Then marginalia was unhappy so I upgraded it.  Then the new version of embark threw an error about embark-define-keymap...

Since there is non-negligible contact surface between them, I wonder if you've ever considered a "veccom meta package" — a content-free package which simply requires some set of "known latest working versions" of this set of packages.  Might reduce frustration & non-bugs from mixed versions.   voccem?

**Comment by minad** [comment]
@jdtsmith If you don't upgrade all packages at once it is always a user error since packages cannot specify upper dependency bounds, which could possibly prevent mixup. The Consult manual makes it clear that all versions must be updated. I wonder why anyone would use outdated versions of packages anyway. Either use ELPA/MELPA-stable or use ELPA/MELPA-devel depending on your stability preferences. In both cases you must upgrade to the newest versions. Alternatively use straight and upgrade to the exact versions you want but then it is purely your responsibility to find the correct versions which work well together.
