### ISSUE TITLE
Hitting g in a collect buffer coming from consult-info doesn't work

### ISSUE THREAD

**Issue by oantolin** [oantolin/embark#590]
It puts the search terms at the first prompt, which is the prompt for manuals. I don't think there is a general solution for all commands that prompt more than once, instead I should probably make it easy to customize the rerun function for specific commands.

**Comment by minad** [comment]
Yes, consult-info is not Embark friendly. Any ideas on how to improve it? I think we should neither invent a complicated general solution nor implement messy workarounds given how rare such two-prompt commands are.

**Comment by minad** [comment]
Yes, but there you trigger the bad behavior explicitly.

**Comment by oantolin** [comment]
True

**Comment by minad** [comment]
I think we should close this as wontfix. I recommend to define commands like these in the personal configuration, since you probably want to access the same manuals most of the time anyway. 

~~~ elisp
(defun +consult-info-emacs ()
  "Search through Emacs info pages."
  (interactive)
  (consult-info "emacs" "efaq" "elisp" "cl" "compat"))

(defun +consult-info-calc ()
  "Search through the Calc info page."
  (interactive)
  (consult-info "calc"))

(defun +consult-info-org ()
  "Search through the Org info page."
  (interactive)
  (consult-info "org"))
~~~

**Comment by oantolin** [comment]
Sounds reasonable to me.
