### ISSUE TITLE
Improve docstring of embark-target-finders

### ISSUE THREAD

**Issue by hmelman** [oantolin/embark#601]
I'm making my own target finder and I think the docstring of `embark-target-finders` would be better as follows:

	  "List of functions to determine the target in current context.
	Each function should take no arguments and return one of:

	1. a cons (TYPE . TARGET) where TYPE is a symbol looked up
	   in `embark-keymap-alist' and TARGET is a string

	2. a list structure (TYPE TARGET BEG . END) where BEG and
	   END are buffer positions bounding TARGET for highlighting

	3. a possibly empty list of targets, each of type 1 or 2."

FYI, the README calls form 2 "an improper list" but I found the term "list structure" used in the elisp manual at the bottom of the "Lists and Cons Cells" node.  Just a question: I find the form 2 inconvenient and wonder why it isn't just a list of 4 elements (TYPE TARGET BEG END)?  I get it's slightly more space efficient without a `nil` terminator, but the form is much less common. I changed the existing term "triple" and the notation (TYPE TARGET . (BEG . END)) to the printed representation (TYPE TARGET BEG . END) because I suspect some people won't know (or remember):

```elisp
(equal '(a b c . d) `(a b . (c . d)))
t
```

Also I think the "New target example" in the README should refer to this docstring for the full specification for the return values of target finders.  As near as I can tell this is the only place it's described.

I'm sorry this isn't in the form of a PR. FYI, I have *not* signed copyright over to FSF, but it is not required for documentation only changes such as this.

**Comment by oantolin** [comment]
I don't think there is any good reason for the target finders returning `(TYPE TARGET START . END)` rather than a four element list `(TYPE TARGET START END)`. But it would also probably be more trouble changing it now than it is worth, since everybody who has written a target finder would have to update it. If I did change the format, I think I'd use plists `(:target TARGET :type TYPE :bounds (START . END))`, which is what the action hook use, and which is also more easily extensible, if we ever want to add other metadata to targets.

I apologize for calling those "improper lists", which is what they call them in other lisps, like Common Lisp or Scheme. I just assumed without checking that Emacs Lisp would use the same terminology. But the word "improper" does not even occur in the elisp info manual! They are called "dotted lists" instead. Oddly enough, lists whose last `cdr` is `nil` _are_ called "proper lists", it's just that the non-proper ones are called dotted rather than improper. Oh, well.

I'll make (versions of) all the changes you suggested to the wording, including mentioning the docstring in the manual. I haven't ever treated the manual as comprehensive, which is probably because the source for it is contained in a file called "README"... Instead it contains sort of the highlights of the full documentation which is in the docstrings. The docstrings while meant to be complete are very dry and, for example, don't have any examples. Now, the README is not too far from being complete, so it's probably worth completing: it's already too long for a README so I should switch to thinking of it as the manual, that you are meant to read in info, and just secondarily a README for GitHub users.

**Comment by minad** [comment]
Why did we choose `(TYPE TARGET START . END)` back then? Probably such that you can use `cddr` to access the bounds as a pair? Given that it is not such a bad choice. However we could have also used `(TYPE TARGET (START . END))`. I agree that a plist would be better, but it does not look like we want to add more fields? If that happens in the future we can add support for a plist format.

**Comment by oantolin** [comment]
Yes, it was probably chosen so the bounds can easily be accessed as a pair (rather than as a 2-element list). I agree with only moving to a plist if the need for more target metadata arises.

**Comment by oantolin** [comment]
Please check to see if you agree with the changes, @hmelman.

**Comment by hmelman** [comment]
- I agree it's too late to change the format.
- I'm good with the term "dotted list"
- "either" is used when there are only two choices, that's why I changed it to "one of"
- in form 2, why not describe TYPE and TARGET in the order they appear (as is typical)
- as I just hit now, there needs to be a fourth choice value listed (or described somehow), `nil` in the case the target finder doesn't match in order for other targets to be tried.  My initial attempt at my film target didn't do this.
- in the README sample `(url actual-url-of-the-page start . end)` it's not clear at a glance that `url` is a symbol and the others are variables. Perhaps the last 3 should be capitalized.

**Comment by oantolin** [comment]
Either is most commonly used for two options but 
can also be used for more. But if people expect it to only be used for two options, I guess it doesn't matter what the dictionary says, so I'll change it. 

nil is the empty list, covered by point 3. Do you think it warrants adding a separate, redundant point for emphasis?

In the second point I described the target first so that the parenthetical remark about the type didn't interrupt the flow of the sentence. I do that in code too: I make the short branch of an `if` statement come first, negating the condition if necessary.

Capitalizing to emphasize url is the symbol is a good idea, I'll do that.

**Comment by oantolin** [comment]
Also, returning nil isn't used to indicate that other target finders should be tried: they are _always_ tried and you can cycle among all the targets found. That's why I think nil doesn't need to be mentioned separately, and why I think "possibly empty list" is mention enough of nil.

**Comment by oantolin** [comment]
In the end I figured it cost me nothing to be redundant about nil. 8e7c53a

**Comment by hmelman** [comment]
Hmmm, I may have made some other mistake.  What I think important to say explicitly is, what should the function return if it doesn't match a target.

**Comment by oantolin** [comment]
> What I think important to say explicitly is, what should the function return if it doesn't match a target.

Yes, that's what I realized: it isn't so much that the docstring needs to describe what returning nil means, but the other way around: it should tell you that if you don't find targets you should return nil.
