### ISSUE TITLE
wrong-type-argument sequencep embark-copy-as-kill

### ISSUE THREAD

**Issue by rickalex21** [oantolin/embark#617]
Hello,

I'm wanting to do something simple like get all the marked candidates from
embark-collect when I run a function (e.g., consult-theme) or any function and act on
them with mapconcat or get them into a list if they are not already in one.

The problem is how do I get all the arguments at once from `embark-act-all`? The
function is being called with one argument at a time. The function `kill-append` would
not work because it would continue copying. What I need is to modify
`embark-copy-as-kill` and get all the arguments at once:

```sh
(kill-new (format "%S" all-marked-targets) )
```

Example of what would be on collect:
```text
doom-monokai-classic              
doom-old-hope                     
doom-one                          
```

What I would like for my `kill-new` to be:
```text
'("doom-monokai-classic" "doom-old-hope" "doom-one")
```

Run an interactive function on candidates, not sure if this is available already?
Probably could create this with funcall and callback, not sure if that's the best route.

```text
Enter function to run on candidates:  (concat x "_ ")
doom-monokai-classic_ doom-old-hope_ doom-one_
```

This is what I tried, won't work cause the function gets called several times.
Instead of once with all the arguments?

```lisp
(defun my/embark-run-func (string-arg)
  (kill-append string-arg nil))

(define-key embark-general-map "Y" #'my/embark-run-func)
```

I even tried to use the original function and I got this error.

```lisp
;; Built in embark function.
(defun my/embark-run-func  (strings)
  "Join STRINGS and save on the `kill-ring'.
With a prefix argument, prompt for the separator to join the
STRINGS, which defaults to a newline."
  (kill-new (string-join strings (embark--separator strings))))

(define-key embark-general-map "Y" #'my/embark-run-func)
```

```sh
Debugger entered--Lisp error: (wrong-type-argument sequencep 100)
  mapconcat(identity "doom-monokai-classic" "\n")
  string-join("doom-monokai-classic" "\n")
  (kill-new (string-join strings (embark--separator strings)))
  my/embark-run-func("doom-monokai-classic")
```

Thanks, for this great package.

**Comment by oantolin** [comment]
I don't think I fully understand what you are trying to achieve. I will make a guess as to what it is but please tell me if I am wrong. I think you want to put several candidates as **separate** items into the kill-ring, right? In that case you could use `kill-new` as an action for `embark-act-all`:

```elisp
(define-key embark-general-map "Y" #'kill-new)
```

That way, if you have `embark-act` bound to `C-.`, say, then you can go `C-. A Y` (A for `embark-act-all` and `Y` for `kill-new`) and it will add each candidate to the kill-ring separately. Is that what you wanted?

You mention getting an error when using `my/embark-func`. That is probably because you forgot to tell Embark that it should recieve the multiple targets as a single list argument:

```elisp
(add-to-list 'embark-multitarget-actions 'my/embark-func)
```

When you use a non-interactive function as an action for `embark-act-all` one of two things happens: if the function _is_ a member of `embark-multitarget-actions` it gets called once with a single argument which is a list of all the targets; if the function is _not_ a member of `embark-multitarget-actions`, then it will get called once per target with the target as a strign argument.

If you want to write your own actions that receive multiple candidates as a single list argument, don't forget to make them non-interactive functions and to add the function to `embark-multitarget-actions`.

Does that answer your questions? Please let me know.

**Comment by rickalex21** [comment]
@oantolin Thanks for your help, that's what I was looking for. 
I must have missed `embark-multitarget-actions` somewhere, didn't see it in the readme.

It looks like interactive does work once the function is added to  `embark-multitarget-actions`
I was using it to test the embark functions but it's not needed since I will be calling from keybindings.

I came up with this:

```lisp
(define-key embark-general-map "k" #'my/embark-kill-singles)
(define-key embark-general-map "K" #'my/embark-kill-multi)

(nconc embark-multitarget-actions  '(my/embark-kill-singles my/embark-kill-multi) )

(defun my/embark-kill-singles (targets)
;; TODO: Don't output to the minibuffer. Useful? Not useful?
"Evaluate expression on each embark collect target and create result as new kill.

EXAMPLE

Act on x: (format \"\\=%s,\\n\" x)
⇒
doom-one,
default,
doom-badger,

If You need to act on all at the same time see `my/embark-kill-multi'."
  (let ((expr (read--expression "Act on x: ")))
    (dotimes (count (length targets)) 
      (let ((x (nth count targets)))
      (if (= count 0)
          (kill-new (eval-expression expr ))
          (kill-append (eval-expression expr ) nil))))))

(defun my/embark-kill-multi (targets)
"Evaluate expresion on embark collect targets all at once and create result as new kill.

EXAMPLE

Act on x: (format \"\\='%S\" x)
⇒ \\='(\"doom-one\" \"default\" \"doom-badger\")

If You need to act on each one indivdually see `my/embark-kill-singles'."
  (let ((x targets))
    (kill-new
    (eval-expression   (read--expression "Act on x: ")))))
```

**Comment by oantolin** [comment]
I'm glad that helped, and those are pretty cool actions, @rickalex21!
