### ISSUE TITLE
Bind key only for minibuffer embark actions

### ISSUE THREAD

**Issue by mohkale** [oantolin/embark#622]
Hi there,

I'd like to bind `vertico-multiform-map` into embark only when embark-act is called from an active minibuffer session. Is this possible? I can't see a straightforward way to do so from the documentation.

**Comment by oantolin** [comment]
You can use the `:filter` parameter on a menu-item to make a key binding valid only in certain contexts:

```elisp
(define-key embark-general-map "G"
  `(menu-item "Vertico grid"
              ,(lambda ()
                 (interactive)
                 (with-selected-window (minibuffer-window)
                   (vertico-multiform-grid)))
              :filter ,(lambda (item) (when (minibufferp) item))))
```

Notice that the `:filter` isn't just a boolean function; it would be nice to be able to simply use `minibufferp`.

Also notice that we need to select the minibuffer in the action. This is because Embark actions are run in "the target buffer", and when you call an action from the minibuffer the target buffer is actually the buffer you were in prior to opening the minibuffer.
