### ISSUE TITLE
org-heading target within org-mode agenda

### ISSUE THREAD

**Issue by fhansen42** [oantolin/embark#639]
When I call embark-act from within the org-mode agenda, the org-heading does not show up as a target. Is that the intended behavior or can I configure it to recognize a heading from within the agenda?  I've largely replaced org-speed-commands with embark-org and I'd like to also replace the org-agenda-mode-map with embark-org so that I have one consistent key map across org items.

**Comment by oantolin** [comment]
Oh, that's an oversight. I'm traveling but will fix it when I get the chance.

**Comment by oantolin** [comment]
Mmh, it looks like those aren't technically headings, in the sense that org agenda offer special commands to act on them. I think we'll need a new `org-agenda-item` target type with a keymap containing a bunch of the `org-agenda-*` commands. I'll add that soon.

**Comment by oantolin** [comment]
Let me know if there are any other `org-agenda-*` commands you'd like bound in `embark-org-agenda-item-map`.

**Comment by minad** [comment]
@oantolin Is this map really needed? The agenda buffer is already a special mode, so any commands could be bound directly without modifiers. Is the point that you get a better correspondence with the normal heading map? I wonder where to draw the line - one can basically define an action map in every special mode which manipulates some items, but there wouldn't be any advantage.

**Comment by oantolin** [comment]
Yes, the main point is consistency in the key bindings. This was well-articulated by @fhansen42 in the description of the issue. I agree with you that the necessity of doing this is debatable. You do however get a second small advantage: embark's methods (either the help key or the verbose indicator) of reminding you of the keybindings are a little better than C-h m, in my opinion.

**Comment by minad** [comment]
It is probably a good rule to provide Embark maps in specialised modes if the targets also exist elsewhere. There is also a Dired file finder for example. Nevertheless I think these bindings should be kind of discouraged. Why press `C-. <key>`, when you can simply press `<key>`.

**Comment by oantolin** [comment]
Yeah, I'm a little conflicted. This agenda item case is not quite like the situation for files and dired. In the case of files, we could add no specific support for dired and things would be almost the same. The file target finder has some special code for dired for two reasons:

1. So you can target the file from anywhere on the line, even on the permissions or modification date, for instance.

2. Because ffap gets confused about files with spaces in them. I wish I could fix this in general, but at least I can fix it in dired. :tongue:

But then there is *no special action keymap for files in dired*, it is just the general file action keymap.

This agenda case is pretty different: the agenda items feel like they are just org headings, but (1) they aren't, they don't start with asterisks, and the org parser does not recognize them as headings, (2) you can use the normal heading commands on them, you need these other `org-agenda-*` versions. Point (1) means we need a separate target finder for agenda items, and (2) means we need a separate action keymap. :(

I think this is a borderline case and I can empathize with both sides of the argument.

**Comment by oantolin** [comment]
I do like `embark-dwim` on an agenda item taking you to the corresponding heading in the file in which it occurs. :)

**Comment by minad** [comment]
Hmm, right. We need an extra map. That's not great and probably reason enough to not support this. If you press RET on a heading you can already jump, right?

**Comment by oantolin** [comment]
Mmh. I messed up with uniformizing the keybindings, in particular the default action should be to cycle through todo states. I'll fix that.

**Comment by oantolin** [comment]
I think I'm currently inclined to keep this (now that I've uniformized things a little better). It is definitely a borderline case. What persuades me is that agenda items do feel a lot like headings and Embark supports those, so I think it could feel a little strange if Embark didn't work on agenda items out of the box. You are right, @minad, that since the agenda is a special mode you get a lot less benefit out of having Embark support agenda items. The benefits are small: there are a couple of key bindings which are a lot shorter than the default ones, Embark has a nice interface to remind you of the bindings (nicer than `C-h m`, in my opinion), and the consistency which is what @fhansen42 was after in the first place. I already got used to `M-.` to toggle todo status (since it works on any part of the heading, while speed keys only work on bol).

If more cases like this start cropping up, I might rethink the policy. Certainly this configuration could easily go to the wiki or a separate tiny package.

**Comment by minad** [comment]
We also have an embark-bindings command, which could be used instead of C-h m. It may be worth to even add an embark-major-mode-bindings command?

Imo the wiki would be the better place for this since the key bindings here are just an alternative to the already existing major mode bindings. This doesn't look like a good practice, even if you might wish for more consistency. I think one selling point of Embark is that you get access to actions at point which you could otherwise not access directly. In contrast, the mechanism here looks as if we just dress the major mode map as an action map when pressing C-. on the current line if there is no other target - something you could do in every special mode.

The M-. toggle might be a minor advantage. In my config I have a +embark-dwim wrapper around embark-dwim which checks for a few other objects at point (buttons, widgets, links) which may not be supported by Embark. This yields a general dwim command at point for me. You could use that approach to enable toggling of agenda headings too, if you like that special case. But then, toggling the todo state in the agenda even feels not quite right to me. I would expect the dwim command to jump to the heading in the corresponding file, consistent with other Embark dwim jump actions.

I wonder if there are other target types which are affected by this problem. For example we don't provide the bookmark map in the bookmark buffer. We could do that even if it wouldn't bring any benefits, same with acting on files in Dired. But both these cases are less problematic than this one since on doesn't have to replicate the map.

**Comment by fhansen42** [comment]
Thanks for making this change. Finally had a chance to try it out today. Though it wasn't my original intent, I also find the real benefit here to be:

> Embark has a nice interface to remind you of the bindings (nicer than `C-h m`, in my opinion)

Given @minad's point

> Why press `C-. <key>`, when you can simply press `<key>`

I think my approach is going to be to primarily use org-agenda-mode-map but to use embark to help remember the commands.  I've added the following to my .init: 

`(add-to-list 'embark-keymap-alist '(org-agenda-item org-agenda-mode-map))`

**Comment by oantolin** [comment]
What do you use in embark to remind you of keybindings, @fhansen42? The verbose indicator (which displays a static list) or the completing-read prompter (where you can type part of the key binding or command name to narrow the list of actions)?

If you use the completing-read prompter (which I recommend), you can use the `embark-bindings` command that @minad mentioned to get the list of current bindings with a completing-read interface. @minad also mentioned maybe adding an `embark-major-mode-bindings` command, but I don't think we really need one: the existing `embark-bindings` command when called with a prefix argument will exclude the bindings from the global keymap. This is pretty close to listing only the major mode key bindings: it also includes the bindings from local minor modes and from exotic things like keymaps in overlays at point.

Personally, I bind `embark-bindings` to `C-h b`, and use `C-u C-h b` as better version of `C-h m`. By the way, @minad, I'd be open to flipping the meaning of the prefix argument to `embark-bindings` (i.e., no argument = local, prefix = include global), what do you think?

So if you really just want Embark to remind you of the bindings in `org-agenda-mode-map`, @fhansen42, maybe simply using `embark-bindings` is better. You could even bind `h` in `org-agenda-mode-map` to `(defun show-agenda-bindings () (interactive) (embark-bindings-in-keymap org-agenda-mode-map))`. (`h` is bound to `org-agenda-holidays`, but so is `H`, so you can comfortably reuse one of them.)

I just went over the keymap I wrote and I do like it better than `org-agenda-mode-map` for some things, but that's not a compelling reason to keep it around.

So I see three options:

1. Keep this addition as is.
2. Modify the current addition to use `org-agenda-mode-map` directly instead of defining a new keymap.
3. Remove the current addition and put it in the wiki mentioning both options for the keymap.

I'm currently inclined to go for option 3, since @jhansen42 plans to use embark mostly for reminders of the bindings and prefers `org-agenda-mode-map` over `embark-org-agenda-item-map`, and since I find @minad's arguments pretty convincing.

**Comment by minad** [comment]
Flipping C-u for embark-bindings seems like a good idea. I would go with option 3.

**Comment by oantolin** [comment]
I just realized there is an intriguing option 4: we could make all actions on org agenda items be forwarded to the corresponding heading, and then reuse the `embark-org-heading-map`. (More precisely, a pre-action hook for agenda items could visit the heading corresponding to an agenda item, so that the action is run on the actual heading.) 

That way the code for agenda items would only be a few lines and, more importantly, Embark actions on agenda items would not all be redundant with the org-agenda-mode commands. I can imagine wanting to promote or demote headings, copying the entire subtree to the kill-ring, and a few others things like that which I believe are not covered by agenda mode.

**Comment by minad** [comment]
Oh indeed, this seems like an intriguing alternative in the spirit of Embark. I am not sure if it will work well enough though. Maybe updating the agenda would be needed, something which can be done efficiently only by using the special agenda commands? Another option would be to implement some remapping from normal heading commands to agenda commands. But anyway, all these options show that we are in somewhat unexplored territory with respect to the usual Embark functionality. The best option is not self-evident.

**Comment by fhansen42** [comment]
> What do you use in embark to remind you of keybindings, @fhansen42?

I use the completing-read prompter.

> you can use the `embark-bindings` command that @minad mentioned

I had tried this when reading @minad's response yesterday but found it to be too verbose. I was not aware that the prefix argument could exclude bindings from the global keymap. Using `embark-bindings` with the prefix argument definitely meets my needs.

Actually, I have one issue with it, but I think it is unique to my config: I use the `disable-mouse` package. For some reason, bindings in `disable-mouse-mode-map` are not excluded when using the prefix argument. There are almost 3k of these bindings. Who knew there were so many ways to use the mouse? I wrote the following function to address it, however: 

```
(defun show-agenda-bindings ()
  (interactive)
  (disable-mouse-global-mode -1)
  (embark-bindings-in-keymap org-agenda-mode-map)
  (disable-mouse-global-mode 1))
```
Thank you to both of you for your work on this terrific package.

**Comment by oantolin** [comment]
Since in your `show-agenda-bindings` command, you specifically use `embark-bindings-in-keymap` to show only the bindings in `org-agena-mode-map`, you shouldn't need to turn `disable-mouse-global-mode` off and on, @fhansen42.

**Comment by oantolin** [comment]
I'm thinking of revisiting this and changing the support for agenda items to the [option 4 briefly discussed above](https://github.com/oantolin/embark/issues/639#issuecomment-1609038270). That way (1) the bindings are not completely redundant with the keybindings in agenda mode, and (2) it automatically gives support for acting on @alphapapa's `org-ql-find` minibuffer candidates. An implementation of this alternate way of defining actions for agenda items is available in the remote-org-heading branch. I'm not fully decided yet, but I think I'd replace the current support with that.

**Comment by oantolin** [comment]
I've decided to switch to option 4. @minad's argument about the redundancy of giving org-agenda-mode commands key bindings when they already have mostly single-letter ones is convincing. And I believe @fhansen42's main desire was to be reminded of org agenda bindings, for which `embark-bindings` is a better tool. (By the way @fhansen42, the sense of the prefix argument has changed and now `embark-bindings` by default excludes global bindings, and includes with `C-u`; I find that makes it much more useful.)

**Comment by minad** [comment]
Is it possible to support Embark actions in consult-org-heading? It seems I need an org-marker property and the org-remote-heading category?

**Comment by minad** [comment]
Btw, Omar, the category org-remote-heading is something you introduced purely for Embark? I would prefer the name org-heading-reference since this seems to be more meaningful, but do we have to distinguish org-heading and org-heading-reference? I think it would be even more elegant to have only the type org-heading and a transformer in Embark which normalizes org-heading -> org-heading. Headings can either be "direct" or references if they carry a org-marker property. This way we avoid the org-heading-reference type which seems a bit like an Embark implementation detail. I haven't checked the code though, so using a single type may not work. What do you think?

**Comment by alphapapa** [comment]
> Headings can either be "direct" or references if they carry a org-marker property.

What would a "direct" heading be exactly?  If it lacked a marker pointing to the heading in the source buffer, how would it be useful?

**Comment by oantolin** [comment]
@minad:

> Btw, Omar, the category org-remote-heading is something you introduced purely for Embark?

They do occur in Emacs as org agenda items. I initially called the category `org-agenda-item` but changed the name when I realized @alphapapa's `org-ql-find` also produced this type of target. The name is more general just to cover those two cases.

> I would prefer the name org-heading-reference since this seems to be more meaningful

Seems about equally meaningful to me, but I do like the sound of "reference" better.

> but do we have to distinguish org-heading and org-heading-reference?

They currently share an action keymap and the pre-action that jumps to a heading only does it if there is an `org-marker` text property, so no, if we are happy with the current actions there is no need to distinguish them.

>I think it would be even more elegant to have only the type org-heading and a transformer in Embark which normalizes org-heading -> org-heading. Headings can either be "direct" or references if they carry a org-marker property.

There is no need for a transformer to normalize them, I think. What would it even do? As you said an `org-heading` target is a reference if it has an `org-marker` text property.

> I haven't checked the code though, so using a single type may not work. What do you think?

It would work, I only made it a separate type because of two reasons, both of them bad: (1) inertia: when I was using the org agenda commands asactions for org agenda items it made sense to have a different action keymap, when I switched to use the heading keymap I was too lazy to unify the types; and (2) in case I wanted to change back to having different action keymaps in the future. Now, after trying it a bit I'm inclined to keep the same action keymap and unify the types.

@alphapapa:

> What would a "direct" heading be exactly? If it lacked a marker pointing to the heading in the source buffer, how would it be useful?

You get those direct headings from org mode buffers (so they are in fact, quite abundant): headings in an org mode buffer do not have an `org-marker` text property (I guess because it would just point to right there). 

You may claim it's kind of pointless to use Embark in an org mode buffer to act on a heading there since you can just directly use org mode key bindings, and you'd be correct for people who can memorize the org mode key bindings and never need a refresher on them. :)

**Comment by minad** [comment]
@oantolin Okay, so it seems we can unify the types? I think it would be good to do this since the type org-heading sounds much more canonical than org-heading-reference or org-remote-heading.

**Comment by oantolin** [comment]
Yep, I'll unify them, @minad.

**Comment by minad** [comment]
@oantolin Great, thanks! If the need for separate actions come up we can still reconsider. But I think context sensitivity is a common problem regarding actions at point and in the minibuffer, not restricted to org-heading only. 

The Consult implementation looks alright, do you agree? Still need to update the category then.

@alphapapa By "direct" I meant simply a heading at point in an org buffer, since Embark supports both acting in the mb and in normal buffers.

**Comment by oantolin** [comment]
Damn it, they do differ in one key aspect: the default action! For a heading at point, the default action is cycling todo status; for  heading reference the default action is to jump to the heading. I want to keep those default actions, so I can't fully unify them.

**Comment by oantolin** [comment]
> The Consult implementation looks alright, do you agree?

I'm confused: Consult implementation of what?

**Comment by oantolin** [comment]
I mean, I could still unify them, and have a default action override that jumps to the heading if it is a reference, and if it isn't does todo status cycling. 😬 That sounds kludgy.

**Comment by minad** [comment]
A bit kludgy indeed but I think I would still prefer that. The minibuffer default action is already a kludge from the get go in the minibuffer with the this-command override etc.

**Comment by oantolin** [comment]
> But I think context sensitivity is a common problem regarding actions at point and in the minibuffer, not restricted to org-heading only.

It has come up before, @minad, but I don't think it's really that common.

> The Consult implementation looks alright, do you agree?

Are you talking about `consult-org-agenda`? Are you planning to add `org-marker`s to its candidates?

**Comment by oantolin** [comment]
> See [minad/consult@40d784f](https://github.com/minad/consult/commit/40d784f18fb6792f3f11b6b1f3f48db17a12de1c)

Thank you! I had no idea what you meant! Shouldn't `consult-org-agenda` also change in the same way?

**Comment by minad** [comment]
> It has come up before, @minad, but I don't think it's really that common.

I agree. What I wanted to say is that I rather see things unified (like here with org-heading) if possible, even if there exist some context sensitive actions not working in a certain context. We are also not locked in a modal mode as you like to point out. ;)

**Comment by minad** [comment]
> Shouldn't consult-org-agenda also change in the same way?

This is just a small wrapper around consult-org-heading.

**Comment by oantolin** [comment]
The only real downside of the kludgy default action override (that would do both jumping and todo-cycling) is that it keeps people from easily changing the default action for the heading at point in a normal org buffer. The other downside is just aesthetic, and can be ignored (with some effort).

**Comment by oantolin** [comment]
OK, so it's decided: a unified `org-heading` it is, then. And I'll make the necessary default action override. It'll be an improvement for embark-collect from org-consult-heading, because while pressing RET in the collect buffer currently works it's pretty slow since org-consult-heading gathers all the headings again.

**Comment by alphapapa** [comment]
> OK, so it's decided: a unified `org-heading` it is, then. And I'll make the necessary default action override. It'll be an improvement for embark-collect from org-consult-heading, because while pressing RET in the collect buffer currently works it's pretty slow since org-consult-heading gathers all the headings again.

@oantolin Ok, what needs to happen in `org-ql` with regard to this?  Does https://github.com/alphapapa/org-ql/issues/299 need to be updated?

Thanks.

**Comment by oantolin** [comment]
In my PR alphapapa/org-ql#369 I need to change the category from `org-remote-heading` to `org-heading`, and that's it, @alphapapa

**Comment by oantolin** [comment]
On second thought, maybe I should also remove the refile-to action from that PR and add it to embark-org. That action would also be very helpful for consult, so we have to options: I keep it in embark-org or you guys let me duplicate it in both org-ql and consult. That second option seems wasteful.

**Comment by oantolin** [comment]
Yes, @alphapapa, it would work as follows: you first put point on the heading you want to refile, you then run `org-ql-find` to locate the heading you want to refile it *to*, and once you have that heading selected in the minibuffer you call `embark-act` and select the refile-to action.

It makes no difference which library defines the refile-to action, since it needs no access to `org-ql` or `embark` internals, it only depends on org. All this action does is receive as argument a string with an `org-marker` property and call `org-refile` with the appropriate argument to refile to the location of the marker.

**Comment by oantolin** [comment]
The unification is done d1069bb4e50d93843dc77226b3984342cc6e0945 (and I decided that for headings-at-point it will lookup RET in embark-org-heading-map---falling back to org-todo if RET is unbound--- to keep it easy for people to change the default action). Now @minad should just change `org-remote-heading` to `org-heading` and Consult is all set. For org-ql, I will fix my PR.

**Comment by minad** [comment]
Fixed in https://github.com/minad/consult/commit/4b8f8a55e875f705925b954822127bfbc7045c82

**Comment by oantolin** [comment]
I've added an `embark-org-refile-here` action to `embark-org`. It works with `org-ql-find` and `consult-org-heading`, but I also made it work with the agenda: if you open the agenda from an org buffer and use `embark-org-refile-here` on an agenda item, it will refile the heading that was at point in the org buffer to the heading containing the agenda item. I'm not sure that's a great idea, but I felt reluctant to add an action that only works in conjunction with third party packages.

**Comment by alphapapa** [comment]
> I also made it work with the agenda: if you open the agenda from an org buffer and use `embark-org-refile-here` on an agenda item, it will refile the heading that was at point in the org buffer to the heading containing the agenda item. I'm not sure that's a great idea, but I felt reluctant to add an action that only works in conjunction with third party packages.

That's an interesting idea.  I feel like it might be confusing, but could also be useful, so...  :)  Thanks for your work.

**Comment by oantolin** [comment]
I've fixed alphapapa/org-ql#369 now, @alphapapa. Now all it does is add the category to the completion metadata in `org-ql-completing-read`.

**Comment by alphapapa** [comment]
> I've fixed [alphapapa/org-ql#369](https://github.com/alphapapa/org-ql/pull/369) now, @alphapapa. Now all it does is add the category to the completion metadata in `org-ql-completing-read`.

Thanks.  I intend to tag v0.7.2 of org-ql soon, then I'll merge that for 0.8.

**Comment by oantolin** [comment]
No worries, @alphapapa. Early adopters (like me) can use Marginalia to do the external equivalent of that PR anyway. I have to say, I really like using embark-dwim in org-ql-find to get a preview of the a heading in its context (I guess consult has made me pretty dependent on previews, @minad).

**Comment by alphapapa** [comment]
@oantolin Just used `org-ql-find` to find a heading, and Embark with `C-. I` to clock in to it.  Raised my hands in celebration.  Works so well, saves so much time.  Thank you again for your work on this.

**Comment by oantolin** [comment]
Great to hear that, @alphapapa! I've been using `org-ql-find` a lot now and it's fantastic. I haven't felt the need for any fancy searches yet but just the fact that the body text is searched too makes it so convenient!

**Comment by alphapapa** [comment]
Yeah, since I made the default predicate the "smart"/"rifle" one, it works really well.  Something I still need to work on is sorting the results to bring the most relevant ones to the top.  I have a primitive one in this branch (which also implements a command you may find interesting: `org-ql-find-link`): https://github.com/alphapapa/org-ql/tree/wip/find-links
