### ISSUE TITLE
Why the difference between Embark Collect and Embark Export?

### ISSUE THREAD

**Issue by WorldsEndless** [oantolin/embark#644]
What is the reason for the difference between collect and export buffers? I just had a lengthy debug session while trying to refactor a project and found that my wgrep solution was failing ( #555 ) because I was trying to wgrep a Collect buffer instead of an exported buffer. I can only imagine others having this same confusion. What's the reason for Collect buffers?

**Comment by oantolin** [comment]
I'll answer in two parts.

First, why is there an `embark-collect-mode`? You could say it's there to support `embark-export`. What the `embark-export` command does is produce a buffer that collect all the current candidates (for example, from a minibuffer completion session; or if some targets have been selected with `embark-select` in the current bufer, those targets) into a dedicated buffer with a major mode appropriate to that type of candidate.

The default configuration will make a dired buffer for file candidate, an ibuffer buffer for buffer candidates, an occur-mode buffer for `consult-line` candidates, a grep-mode buffer for `consult-grep` candidates, a customize buffer for candidates which are Emacs Lisp variables, etc.

But what should `embark-export` do if there is no reasonable major mode for the list of candidates you are exporting? What if you are exporting a list of email addresses, or of sentences, or of s-expressions, etc.? Or what if the list is of mixed type, such as you often get from `consult-buffer`, list which include a mix of files, buffers and bookmarks?

One possible design choice would be to raise an error: "no appropriate major mode found for the current candidates". But I thought it would be more helpful to export them anyway, to a generic type of buffer that can hold an arbitrary list of candidates for further action. These are the `embark-collect-mode` buffers, the fallback major mode for `embark-export` when no other more specific major mode is available.

OK, but why is there an `embark-collect` command then that always produces an `embark-collect-mode` buffer? Why not only have `embark-export` and force people to only use `embark-collect-mode` when no other more specific major mode is available.

The answer is that I'm not fond of forcing people to do things a certain way. If someone prefers embark collect buffers I want them to be able to use use them. For example, I sometimes use them even for grep results, because I like that results get nicely grouped by file into collapsible sections. Of course, I don't get to use wgrep then, so I usually prefer to export.

And if you want to only use `embark-collect-mode` when there is no other choice that's easy! Just never use `embark-collect` and stick to `embark-export`. If you really want to make it hard to run `embark-collect` by accident, just unbind it.

**Comment by minad** [comment]
@oantolin I took another look at the README and I think you could make the motivation for collect a little bit more clear. I assume for export it is obvious since we get a dedicated and appropriate buffer. This is the list of collect advantages I come up with after reading your answer:

- Fallback if there is no appropriate major mode.
- Mixed export from `consult-buffer` and other multi category commands.
- A uniform candidates view, compare Dired, the customization export or the apropos export.
- Useful for text manipulation on candidates. Some of the export modes are too rich and noisy.
- The collect buffer supports acting via Embark, multi select etc. This is not possible in all the export modes. With collect you stay in Embark, without loss of information.
- Grouping, but I think this will also be part of grep/compile buffers in Emacs 30.

**Comment by WorldsEndless** [comment]
that makes excellent sense -- collect as a fallback when there is no appropriate export method, or when they actively don't want the export format
