### ISSUE TITLE
creation of file with consult--tofu-char at end of file name

### ISSUE THREAD

**Issue by stevenbagley** [oantolin/embark#646]
The following sequence unexpectedly creates a new file with the consult--tofu-char as the last character in the file name.

1.  `find file` on file1.txt and file2.txt (contents of files does not matter).
2.  From buffer file1.txt, run `consult-buffer`. Navigate to `file2.txt`, and hit TAB to select.
3.  Run `embark-act`
4.  Run `embark-become`
5.  Enter "f" for find-file
6.  Hit RET

This creates a new buffer for file file1.txt (with consult--tofu-char after ".txt")

(Also, I am not sure if this is a consult bug or an embark bug.)

**Comment by oantolin** [comment]
Oh, this is a tough one, in the sense that it is both the expected behavior and clearly not what you'd normally want.

What happens is that consult-buffer, like many consult commands, invisibly add some special characters to its candidates either to disambiguate or to add some extra information (in this case consult-buffer adds a character to specify the type of candidate). When you press TAB you get the candidate's name into the minibuffer with the extra invisible character too.

Then you run embark-become whose job is to write whatever is in in the minibuffer right now into the minibuffer for the command you become. So you get the whole thing including the extra character.

So, all parts are working as designed but the combination is annoying.

I think here probably the best advice is to just not do that: you can instead use embark-act (which the embark-consult package configures to remove those extra characters) to run find-file.

**Comment by oantolin** [comment]
I guess I should think about whether embark-become should also know about consult tofus (that's what those characters are reffered to in the consult source code). I'm tempted to keep things simple, as they are, with embark-become doing no transformation on the minibuffer contents.

**Comment by oantolin** [comment]
Maybe having embark-become strip all invisible characters is reasonable. One could argue that behavior is less surprising than copying the entire minibuffer input since users are likely to be unaware of the invisible portions.

**Comment by oantolin** [comment]
I think that for the few examples of commands I know that add invisible information to completion candidates, there is usually no other command you'd want to switch to with `embark-become` that would know what to do with the invisible information. So I think removing invisible text in `embark-become` fixes this corner case and has no real downsides.

**Comment by minad** [comment]
I don't think there is really a need for the stripping. embark-act is better than TAB+become. And in the rare cases of TAB+become, the full candidate string may even be desired?

**Comment by oantolin** [comment]
So first of all, I agree that stripping invisible characters isn't really necessary, since users can simply not do TAB+become and it is not a common situation at all.

But the question I find more compelling is: if a user does happen to use TAB+become, what is the least surprising possible outcome? I'd argue that the least surprising outcome is that the target command receives as input the text _you can see_ in the minibuffer.

It is true that one can invent situations where the full candidate would be desired, but I'd argue that (1) we don't have those in the wild yet, and (2) those could probably be better handled with `embark-act`.

I think the tiny extra complexity of sticking in a call to `embark--display-string` in the `embark-become` source is worth the trouble to get more predictable behavior.

**Comment by minad** [comment]
> I think the tiny extra complexity of sticking in a call to embark--display-string in the embark-become source is worth the trouble to get more predictable behavior.

Agree. At least we can reuse existing code which achieves the desired behavior.
