### ISSUE TITLE
Bind embark-select to key

### ISSUE THREAD

**Issue by walseb** [oantolin/embark#648]
Hello!

I want embark-select bound to a key so I can mark items without having to go into embark act, but `embark-select` doesn't appear to do anything. This is what I have done:

`(define-key vertico-map (kbd "C-,") #'embark-select)`

Running `C-h k` shows that the command is correctly bound, it just doesn't do anything. I'm trying to mark in the command `consult-buffer`.

Thoughts?

Thanks for any help!

**Comment by walseb** [comment]
I just realized it's bound to ignore: `(defalias 'embark-select #'ignore)`

**Comment by walseb** [comment]
I don't see any interactive command I can use to mark. Is there any way to do this?

**Comment by oantolin** [comment]
The implementation of embark-select cheats a bit and does all its work through embark hooks, which is why the command itself does nothing. This does however mean that you must run embark-select through embark-act.

Probably the easiest way to do this is to use keyboard macros. If you have `embark-act` bound to `C-.`, say, you can bind your `C-,` to the keyboard macro `C-. SPC`:

```elisp
(define-key vertico-map (kbd "C-,") (kbd "C-. SPC"))
```

**Comment by minad** [comment]
On 7/11/23 03:19, Omar Antolín Camarena wrote:
> The implementation of embark-select cheats a bit and does all its work
> through embark hooks, which is why the command itself does nothing. This
> does however mean that you must run embark-select through embark-act.

Ha! If I recall correctly I complained about this specific
implementation before. ;) It would be better to come up with an
implementation where we end up with a command which can be bound to a
key directly.

**Comment by oantolin** [comment]
Well, a select command needs a way to know which of all the possible targets at point the user wants to select, so it is natural to have it work as an action: let the user cycle to the desired target and then invoke the select action.

I could also add a second way to select, a less flexible command that selects the first target at point, a sort of embark-swim (select what I mean).

**Comment by oantolin** [comment]
In fact, I think I had planned on adding that "select top target" command back when the feature was being worked on and you wisely suggested to wait to see if anyone wanted it, @minad.

**Comment by minad** [comment]
On 7/11/23 08:36, Omar Antolín Camarena wrote:
> In fact, I think I had planned on adding that "select top target"
> command back when the feature was being worked on and you wisely
> suggested to wait to see if anyone wanted it, @minad
> <https://github.com/minad>.

You are right. I am even responsible for this problem since I suggested
to go via embark-act (and target finders) for the selection mechanism.
:-P Would it make sense to revise this design such that embark-select
can be bound on the toplevel too? It could obtain the target via the
target finder hook, but then we will just end up with code duplication.
So better stick to the macro approach if someone wants a direct key?

**Comment by minad** [comment]
On 7/11/23 08:50, Daniel Mendler wrote:
> On 7/11/23 08:36, Omar Antolín Camarena wrote:
>> In fact, I think I had planned on adding that "select top target"
>> command back when the feature was being worked on and you wisely
>> suggested to wait to see if anyone wanted it, @minad
>> <https://github.com/minad>.
> 
> You are right. I am even responsible for this problem since I suggested
> to go via embark-act (and target finders) for the selection mechanism.
> :-P Would it make sense to revise this design such that embark-select
> can be bound on the toplevel too? It could obtain the target via the
> target finder hook, but then we will just end up with code duplication.
> So better stick to the macro approach if someone wants a direct key?

If we take a step back - this is a general problem affecting all kinds
of commands which are turned into actions. Since actions need injection,
they can never be bound directly. Therefore it should be okay to keep
things as is, otherwise we would have to generate special
directly-bindable variants of various actions. But then, embark-select
is maybe a bit of a special case.

**Comment by oantolin** [comment]
Just to confirm, [my initial idea](https://github.com/oantolin/embark/issues/253#issuecomment-1509886796) was to have both an action that could select any target you cycle to and also a command that selects the first available target. And in the very next comment after that one @minad says it's probably best to hold of on implementing the "select first target" command since people can just use a keyboard macro. 😄 

I think having those separately does make sense, since a top-level command can't know which target you want (unless it reimplements target cycling or some other target selection mechanism) and a command that always selects the first available target is not flexible enough on its own. It's probably best to have both.

**Comment by oantolin** [comment]
Huh, I just realized I can have `embark-select` do both: when called through `embark-act` toggle the selection status of the target being acted on, and when called outside `embark-act` toggle the selection status of the first target at point. I'll implement that tomorrow. (Just use a aroung action hook to completely replace it when used as an action.)

**Comment by minad** [comment]
> Huh, I just realized I can have embark-select do both: when called through embark-act toggle the selection status of the target being acted on, and when called outside embark-act toggle the selection status of the first target at point.

Yes, this is what I thought. It is not nice to have such a code duplication though.

**Comment by minad** [comment]
> There's no duplication, I just call embark--select on the first target, @minad.

Indeed this is extremely simple since `embark--select` can be reused as is. But I think there is still potentially some duplication - imagine other actions like `kill-buffer` being able to handle both invocation via `embark-act` (via target injection) and directly on the target at pont. The question is which actions are supposed to get such a special treatment to work in both usage modes. Hopefully `embark-select` is the only one?

**Comment by oantolin** [comment]
Yeah, I think embark-select deserves special treatment because it is "infrastructure".

So I won't add command to Embark to kill the buffer at point, etc., but since the question comes up fairly often I think I should do something.

The easiest option is to just document the keyboard macro approach. I could additionally document how to write a command that calls `embark--act` on `(car (embark--targets))`. And the documentation could go in the manual or just the wiki. Finally, I could offer a macro to help define these commands...

**Comment by minad** [comment]
> The easiest option is to just document the keyboard macro approach.

Yes, this should definitely be documented and also that `embark-select` is bindable as "infrastructure" command like `embark-act` or `embark-dwim`.

> I could additionally document how to write a command that calls embark--act on (car (embark--targets)). And the documentation could go in the manual or just the wiki. Finally, I could offer a macro to help define these commands...

Hmm, I am not sure we should do this. This is not worth the complication and eMACs is about macros, so let's rather teach users that.

**Comment by minad** [comment]
> I give the advice of binding keyboard macros to a key much more often than I follow that advice. 

Haha, me too. In the case of Embark I am also happy to always go through `embark-act`.

**Comment by hmelman** [comment]
FWIW, I use keyboard macros a lot but I never bind them to keys.  If it's going in my init I want real elisp.  I don't want the fragility if I were to change the binding of embark-act (which for a while I experimented with). I'd rather see a template command I can copy with a spot to put my specific command call. I think making that template a macro is fine, but I wouldn't do it unless you want to maintain it and get requests to use it in more cases.

**Comment by walseb** [comment]
Thanks so much for the help!
