### ISSUE TITLE
Add custom command to embark-consult-search-map

### ISSUE THREAD

**Issue by manuel-uberti** [oantolin/embark#663]
Hi,

first of all thanks for Embark, such an awesome package. I have recently wrote a custom command, `mu-consult-ugrep`[1], which I'd like to add to `embark-consult-search-map`. I tried this:

```emacs-lisp
(with-eval-after-load 'embark-consult
  (keymap-set embark-consult-search-map "u" #'mu-consult-ugrep))
```

However, when I hit `C-.` (`embark-act`) on a symbol and then hit `C u` nothing happens. There is no message in the minibuffer, no error, and I cannot act on that symbol any more.

I sure am missing something basic here, but I can't figure it out. :)

<hr>

[1] https://manueluberti.eu/2023/09/16/consult-ugrep.html

**Comment by oantolin** [comment]
Sorry, weird clipboard bug. I will answer coherently soon.

**Comment by oantolin** [comment]
I wrote an answer in Emacs to paste here, but occasionally clipboard-sharing between the Linux vm in which Emacs runs and the main OS just stops working. So instead of getting that highly relevant answer you got some gobbledygook about the thing I was writing about before this issue.

**Comment by oantolin** [comment]
While the Linux VM restarts let me just say that Consult async search commands are tricky to use as Embark actions, which is why there is an entire, nontrivial embark-consult package to set up the integration. The particular problem of nothing seeming to happen is because Embark is pressing RET for you *immediately*.

**Comment by oantolin** [comment]
OK, here's the configuration you need:

```elisp
(setf (alist-get 'mu-consult-ugrep embark-target-injection-hooks)
      '(embark-consult--prep-async embark--allow-edit))

(setf (alist-get 'mu-consult-ugrep embark-pre-action-hooks)
      '(embark--unmark-target))

(setf (alist-get 'mu-consult-ugrep embark-around-action-hooks)
      '(embark-consult--projectless embark--cd))
```

In particular, the `embark--allow-edit` keeps Embark from automatically pressing RET.

**Comment by oantolin** [comment]
Check out the docstring of those functions used as hooks to see what each does, and feel free to ask me any questions.

**Comment by oantolin** [comment]
I must confess I didn't immediately remember the reasons I added all those hooks for consult async search commands. Rereading the code, the thing I didn't remember is that you can use `consult-grep`, etc. as an action on a directory and it will run in that directory with empty initial input. Same goes for a file or buffer, and it uses the directory containing the file or the `default-directory` of the buffer. Since I had forgotten this, I don't use this feature enough!
