### ISSUE TITLE
Error when using `embark-org-refile-here`: `embark PCH: (error "Cannot refile to position inside the tree or region")`

### ISSUE THREAD

**Issue by alphapapa** [oantolin/embark#674]
Hi Omar,

Just now I tried to refile a heading within an Org buffer using `org-ql-find-path` to select a heading, then `C-. R` to refile the entry at point to the selected candidate.  I got this error: `embark PCH: (error "Cannot refile to position inside the tree or region")`.  But when I used the `org-ql-refile` command to do the same thing (same heading to the same candidate), without using Embark, it worked.

I'm using Org 9.6.6, Embark 0.23, and org-ql 0.8-pre (the latest commit).

Thanks for your work!

**Comment by oantolin** [comment]
Oh, that used to work! (I now get the same error you got.) I'll look into it.

**Comment by oantolin** [comment]
Ha! Remember in #670 you asked if we shouldn't just run all actions with point on the heading? And remember I said yes? I was wrong! This bug was caused exactly because the `embark-org-refile-here` command should be run with point where it was (the titular _here_ in the command name), not with point on the heading you want to refile! It was trying to refile the heading to itself!

After looking through the action map, there was one more action which should run with point were it was: `embark-org-insert-link-to`. (Which was also broken, but is now a powerful tool to insert links to headings you search for with `org-ql-find`!)

**Comment by alphapapa** [comment]
Thanks!
