### ISSUE TITLE
Use ffap-string-at-point-region

### ISSUE THREAD

**Issue by minad** [oantolin/embark#682]
Can `ffap-string-at-point-region` be used in the file at point finder? Or are the bounds unreliable?

https://github.com/oantolin/embark/blob/3f08fc8ede9dddad3752223e01643058594781b2/embark.el#L722-L729

**Comment by minad** [comment]
@oantolin I wonder if you tried `ffap-string-at-point-region` in the past and rejected it for some reason. In my tests it seems to return acceptable results.

**Comment by oantolin** [comment]
In my testing `ffap-string-at-point-region` is mostly fine except for typos. For example, say you have a file name in a string in some prog buffer, `"~/path/t0/file.txt"` but imagine the actual path should have `to` instead of `t0`, which does not exist. Then `ffap-file-at-point` returns `"~/path/"`, i.e., as much of the path as does exist, but `ffap-string-at-point-region` still returns the entire string `"~/path/t0/file.txt"`.

(I think that's what "string" in the variable name means: it corresponds to `ffap-string-at-point` which I believe is a syntax-only function and does not test for file existence.)

This variable does correctly handle some cases that `(bounds-of-thing-at-point 'filename)` got wrong.

**Comment by oantolin** [comment]
Yeah, I think I need to use thingatpt anyway, to detect URLs because ffap is really weird about them.
