### ISSUE TITLE
embark-occur is broken after closing the target window

### ISSUE THREAD

**Issue by minad** [oantolin/embark#69]
After calling embark-occur on consult-buffer, I have two windows, the original one and the occur window. When I close the original window such that I am left with the occur window, I get an error window-valid-p, wrong type argument. Is this Embark's fault?

**Comment by oantolin** [comment]
Probably embark's fault. When exactly do you get the error?

**Comment by minad** [comment]
This is the keysequence `M-g l M-SPC O C-x 1 RET`.

Futhermore this is broken too `M-g l M-SPC RET`, but not related to occur.

**Comment by oantolin** [comment]
Thanks, that reproduces the problem nicely!

As you know, we recently changed things so that actions run in the target window. If it's dead I could give a more informative message, "The target window for this action is dead".

Or maybe I should also save the target buffer. If the target window is dead, I can still run the action in the target buffer, or maybe even display the target buffer and then run the action. 

If both the target window and the target buffer are gone, as a last ditch effort I could run the action in the Embark occur buffer. Plenty of actions would still make sense.

**Comment by minad** [comment]
> Or maybe I should also save the target buffer. If the target window is dead, I can still run the action in the target buffer, or maybe even display the target buffer and then run the action.

Sounds good! I would switch to the buffer if it still exists - show it in a new window. 

In the case when the buffer is dead I don't see many options since then everything is lost. I would only print a message.

**Comment by oantolin** [comment]
> Sounds good! I would switch to the buffer if it still exists - show it in a new window.

Agreed.

> In the case when the buffer is dead I don't see many options since then everything is lost. I would only print a message.

No, not everything is lost: the candidate remains! You can always save it on the kill ring. If it is a symbol, you can describe it, find its definition, evaluate it if it's a variable or call it if it's a function, etc. For file candidates, you also still have the directory they are in (the default-directory of the occur buffer), so you can still delete, rename, copy, open eshell in the directory, etc.

**Comment by minad** [comment]
> No, not everything is lost: the candidate remains! 

Sure. I would refrain from adding special casing to handle this case. But probably many actions are still valid, so just opening a new dummy buffer or using the occur buffer itself may handle many cases, but it won't be 100% safe.

**Comment by minad** [comment]
What does helm/ivy do in such a case?

**Comment by oantolin** [comment]
> Sure. I would refrain from adding special casing to handle this case. But probably many actions are still valid, so just opening a new dummy buffer or using the occur buffer itself may handle many cases, but it won't be 100% safe.

I'll run the actions in the occur buffer. I'm pretty sure that for my usage patterns that's fine, because for many months all actions were run there! ---we only recently started running them in the target window. If it causes too much trouble, we can revisit this decision later.

**Comment by oantolin** [comment]
There's a tricky case I hadn't considered: what if the target window is still live but is no longer showing the target buffer? My instinct is to display the target buffer, ignoring the window.

**Comment by oantolin** [comment]
I decided the "target window" concept makes no sense, because you can switch buffers and having the target window display a buffer that is not the original target buffer means it is no longer the "target window".

So now, I only record the target buffer and display it prior to executing an action. With the defaults for display-buffer-alist, if the so-called target window is still open and still displaying the target buffer, this should simply select that window.

**Comment by minad** [comment]
> I decided the "target window" concept makes no sense, because you can switch buffers and having the target window display a buffer that is not the original target buffer means it is no longer the "target window".

Yes, but can we make sure that when you switch to the target buffer, that the target buffer is also shown in the selected window? Otherwise we get the inconsistency `(window-buffer (selected-window))/=(current-buffer)` and then #62 is broken again.

**Comment by minad** [comment]
See ^^^ for the change in Consult. But I have to check for the live buffer. If the buffer is dead, no preview is performed, which is okay I guess.

**Comment by oantolin** [comment]
> Yes, but can we make sure that when you switch to the target buffer, that the target buffer is also shown in the selected window?

I think you already figured this out, but just to be explicit, I display the target buffer in some window and select that window.

The change to Consult looks good, too.
