### ISSUE TITLE
Provide a complete working example (own actions don't work)

### ISSUE THREAD

**Issue by inigoserna** [oantolin/embark#72]
I'm currently experimenting with embark. Reading the docs, some concepts are a bit confusing.
Anyway I've been able to write a simple tool, but I've found some issues that I can't understand.

I've created a simple `consult` command to list `tab-bar-mode` tabs, and I've also written my first `embark` tools to manage them.
I can see the actions after executing `embark-act` in `consult-tab`.
There "s" action works, but not my own defined functions under "k" and "r" keys.
They show this error message: `Error running timer: (wrong-number-of-arguments ((t) (tab) (interactive) (tab-bar-rename-tab-by-name tab (or (read-string "New name: " tab) ""))) 0)`

So my question is: what is needed in order to write custom actions?
It looks that if I replace my functions with internal commands the error disappears... but why? which are the missing arguments in the definition of my functions?

``` emacs-lisp
(defun consult-tab ()
  (interactive)
  (tab-bar-select-tab-by-name
   (consult--read
    "Tabs: "
    (or (mapcar #'(lambda (tab) (cdr (assq 'name tab))) (tab-bar-tabs))
        (user-error "No tabs found"))
    :sort nil
    :require-match t
    :category 'tab)))


(defun embark--tab-close-tab (tab)
  (interactive)
  (when (y-or-n-p (format "Close tab '%s'? " tab))
    (tab-bar-close-tab-by-name tab)))

(defun embark--tab-rename-tab (tab)
  (interactive)
  (tab-bar-rename-tab-by-name tab (or (read-string "New name: " tab) "")))

(embark-define-keymap embark-tab-map
  "Tab keymap with some actions for `tab-bar-mode' bars."
  ("s" tab-bar-select-tab-by-name)
  ("k" embark--tab-close-tab)
  ("r" embark--tab-rename-tab))

(push (cons 'tab 'embark-tab-map) embark-keymap-alist)

(add-hook 'embark-target-classifiers
          (defun embark--add-target-tab (target)
            (when (equal target "tab")
              'tab)))
```

**Comment by oantolin** [comment]
Ah, this is a perfect example of documentation I am missing. Sorry about that and thanks for pointing this out.

OK, so:

1. Since your command `consult-tab` has `:category 'tab`, Embark understands the command prompts for tabs automatically, you do not need your `embark--add-target-tab` function or to add anything to `embark-target-classifiers` (or to `embark-classifiers`)!
2. The actions should be normal commands that first prompt you for a tab. Notice that no-one wrote `tab-bar-select-tab-by-name` with Embark in mind, it is a normal command that prompts for a tab and then selects it. When used as an Embark action, Embark supplies the tab at the first prompt automatically.

So for `embark--tab-close-tab` you could change the interactive spec to `(interactive "sTab to close: ")` and it should work. Analogously for `embark--tab-rename-tab`. Although I think `tab-bar-rename-tab-by-name` already does exactly hat you want so you should just use it directly.

Does that clear things up? I have some further comments about `embark--add-target-tab`, which I'll give separately.

**Comment by oantolin** [comment]
So key point: Embark actions are completely normal commands and any command can be used as an action! When using a command as an action, Embark pretends to type the target at the first minibuffer prompt for you.

**Comment by oantolin** [comment]
About `embark--add-target-tab`: you might think it was working since Embark was offering you the right actions for `consult-tab`. It was not working!

Embark new to use the `embark-tab-map` because your `consult-tab` function set `:category 'tab` and you associated the `embark-tab-map` to the category `tab` in `embark-keymap-alist`. The `embark--add-target-tab` was not run at all!

OK, so what is `embark-target-classifiers` for then? Well, Embark can also act on things outside the minibuffer, such as the candidate at point in a `*Completions*` or `*Embark Occur*` buffer, or the file, url or symbol at point in a regular buffer. If the target is acquired that way, the functions in `embark-target-classifiers` are called to figure out what it is. Your function could conceivably be used that way, but it only recognizes the literal word `tab`!

If you really wanted to act on tab names written in regular buffers you would need to:

1. Write a function to recognize the tab name at point, and add that function to `embark-target-finders`.
2. Fix your function `embark--add-target-tab` to recognize names of tabs, instead of recognizing the literal word `tab`.

**Comment by oantolin** [comment]
The whole `embark-target-finders`, `embark-classifiers`, `embark-target-classifiers` is a little bonkers. I want to replace with a single list of function that find a target *and* classify it. Over on reddit, @alphapapa very rightly complained about this silliness.

**Comment by oantolin** [comment]
I started to wonder what I was waiting for with the unification of target acquisition and classification and just did it! e9aa0d7a941c1fc31cfd9112f2446701201aceed

I hope I didn't screw it up: it touched many parts of the code. I like the end result, though.

**Comment by minad** [comment]
I like all kinds of unification and simplification!

My initial complaints about complexity/feature creep in Embark are more and more baseless now!

Happy new year : 🥳 😷

**Comment by inigoserna** [comment]
> About `embark--add-target-tab`: you might think it was working since Embark was offering you the right actions for `consult-tab`. It was not working!
> 
> Embark knew to use the `embark-tab-map` because your `consult-tab` function set `:category 'tab` and you associated the `embark-tab-map` to the category `tab` in `embark-keymap-alist`. The `embark--add-target-tab` was not run at all!
> 
> OK, so what is `embark-target-classifiers` for then? Well, Embark can also act on things outside the minibuffer, such as the candidate at point in a `*Completions*` or `*Embark Occur*` buffer, or the file, url or symbol at point in a regular buffer. If the target is acquired that way, the functions in `embark-target-classifiers` are called to figure out what it is. Your function could conceivably be used that way, but it only recognizes the literal word `tab`!
> 
> If you really wanted to act on tab names written in regular buffers you would need to:
> 
>     1. Write a function to recognize the tab name at point, and add that function to `embark-target-finders`.
> 
>     2. Fix your function `embark--add-target-tab` to recognize names of tabs, instead of recognizing the literal word `tab`.

Thanks. I now understand!

**Comment by inigoserna** [comment]
Thanks for the explanations! I get it working now.
Btw, you can use this code as an example for the documentation if you want.

``` emacs-lisp
(defun consult-tab ()
  (interactive)
  (tab-bar-select-tab-by-name
   (consult--read
    "Tabs: "
    (or (mapcar #'(lambda (tab) (cdr (assq 'name tab))) (tab-bar-tabs))
        (user-error "No tabs found"))
    :sort nil
    :require-match t
    :category 'tab)))


(require 'embark)

(defun embark--tab-close-tab (tab)
  (interactive "sTab to close: ")
  (when (y-or-n-p (format "Close tab '%s'? " tab))
    (tab-bar-close-tab-by-name tab)))

(defun embark--tab-rename-tab (tab)
  (interactive "sTab to rename: ")
  (tab-bar-rename-tab-by-name tab (or (read-string "New name: " tab) "")))

(embark-define-keymap embark-tab-map
  "Tab keymap with some actions for `tab-bar-mode' bars."
  ("s" tab-bar-select-tab-by-name)
  ("k" embark--tab-close-tab)
  ("r" embark--tab-rename-tab))

(push (cons 'tab 'embark-tab-map) embark-keymap-alist)
```

Also, an example of the new target-finders/target-classifers could be good.
F.e. "prefix:some_word_without_spaces_and_quotes" (like sample:test1) in a buffer for an easy to understand example.

**Comment by inigoserna** [comment]
I miss a function to add new binding (or modify an entry) to an existing map. Something like

``` emacs-lisp
(defun embark-keymap-add-binding (map &optional overwrite)
  ...)
```

What do you think?

**Comment by minad** [comment]
@inigoserna Just use define-key for that!

**Comment by inigoserna** [comment]
> @inigoserna Just use define-key for that!

Ouch. I feel silly. Hadn't noted they are normal keymaps!

Thanks and happy new year!

**Comment by oantolin** [comment]
> Hadn't noted they are normal keymaps!

Yep, actions are normal commands, keymaps are normal keymaps. I like normal. 😄

**Comment by inigoserna** [comment]
> Yep, actions are normal commands, keymaps are normal keymaps. I like normal. smile

... and this makes them much more useful for me that what I thought initially!

Thanks again for your work and happy new year!

**Comment by oantolin** [comment]
Happy new year!

**Comment by oantolin** [comment]
Hey @inigoserna, can you please take a look at the README and let me know if you think the added documentation of these features is adequate?

**Comment by oantolin** [comment]
This is [the relevant section](https://github.com/oantolin/embark#defining-actions-for-new-categories-of-targets). I should have said this in the previous comment.

**Comment by inigoserna** [comment]
> This is [the relevant section](https://github.com/oantolin/embark#defining-actions-for-new-categories-of-targets). I should have said this in the previous comment.

Superb!

[Sorry, I started holidays_with_family mode and left anything else unattended.]

**Comment by oantolin** [comment]
Thanks for looking it over. And for asking for more documentation in the first place! I'd been meaning to gives some examples but kept putting it off and this issue gave me the final push I needed to do it.
