### ISSUE TITLE
keymap for `virtual-buffer`/separate buffers and files from `virtual-buffer` type

### ISSUE THREAD

**Issue by junyi-hou** [oantolin/embark#74]
Calling `(run-hook-with-args-until-success 'embark-target-finders)` on candidates in `consult-buffer` won't return the correct types (buffer or file) even when `marginalia-mode` is enable. Instead, it returns a `virtual-buffer`type that is neither buffer nor file.

A cheap way to circumvent this problem is just to define a `virtual-buffer-map` and use it. However, I was wondering if something can be done to "translate" `virtual-buffer` type into `file` or `buffer` type so the right keymap is called.

Thanks!

**Comment by minad** [comment]
Marginalia has special treatment for virtual buffer. The equivalent in Embark would be to define a virtual buffer keymap and special actions.

But we could consider generalizing this - virtual-buffer is a super category of multiple subcategories like file, buffer and more. A command like consult-buffer could specify (via completion metadata) its subcategories and some function which extracts the candidates of the subcategory.

Then marginalia and embark could use this to delegate to the corresponding annotators and action keymaps.

However as of now the only command which combines multiple categories is consult-buffer. Therefore this generalization would be pointless for now.

**Comment by oantolin** [comment]
Actually, let me disagree slightly with @minad here. First of all `virtual-buffer` is **not** a supercategory of `buffer` and `file`, this is because `virtual-buffer` candidates start with a character that specifies what type of thing the *rest* of the string is. Because of that extra prefix, none of the usual file and buffer commands will work on virtual-buffers!

I think instead it is time to revive the idea @minad and I discussed at some point of candidate transformers. I propose they have type (in Haskellish terms):

```haskell
type Transformer = (Category, String) -> (Category, String)
```

Something like the following should be made into part of Embark's default configuration, but for now you can just add this to your init.el (I'll probably put this somewhere in the wiki for now):

```elisp
(defun virtual-buffer-dispatch (pair)
  (pcase pair
    (`(virtual-buffer . ,cand) 
     (cons (pcase (- (elt cand 0) #x100000)
             ((or ?b ?p) 'buffer)
             ((or ?f ?q) 'file)
             (_ 'general))
           (substring cand 1)))))

(advice-add 'embark-target-top-minibuffer-completion
            :filter-return 'virtual-buffer-dispatch)
```

With that configuration Embark will offer you the right kind of actions for each virtual-buffer.

Note that this does not help with Embark occur or with Embark export: those will still just give you an Embark occur buffer full of virtual-buffers and the only actions that will really work on them is `consult-buffer` (I mean, `embark-save` and `embark-insert` work, but they include the prefix character). Indeed, right now only `embark-act` support heterogeneous collections, where not all candidates have the same category. I have some ideas about how to generalize embark-occur at some point, but embark-export is really meant to be homogeneous. Again in Haskell terms, these function could in principle have types:

```haskell
embarkOccur : [(Category, String)] -> Buffer
embarkExport : (Category, [String]) -> Buffer
```

(With the current implementation they both have the type of `embarkExport`, I'm saying `embarkOccur` could be reworked to have the first type.)

**Comment by oantolin** [comment]
> A command like consult-buffer could specify (via completion metadata) its subcategories and some function which extracts the candidates of the subcategory.

Ah, sorry, I missed this! We do not disagree at all then, it's just that I wouldn't use the word "supercategory" for that relationship, unless the extractor is the identity.

**Comment by junyi-hou** [comment]
> > A command like consult-buffer could specify (via completion metadata) its subcategories and some function which extracts the candidates of the subcategory.
> 
> A command like consult-buffer could specify (via completion metadata) its subcategories and some function which extracts the candidates of the subcategory.

Thanks for the prompt response! I'll test the `virtual-buffer-dispatch` and report back.

**Comment by junyi-hou** [comment]
Happy new year!

I tried the advice and it works with buffers. However, for files in the `recentf-list`, it classifies them as `'general` instead of `'file` for some reasons.

**Comment by oantolin** [comment]
Ah, I don't use recentf so I am not surprised. I'll investigate.

**Comment by oantolin** [comment]
I can't reproduce this @junyi-hou. I activated recentf, opened and closed a few files, and I do get file actions for the recently closed files in consult-buffer.

**Comment by minad** [comment]
@oantolin It would be very weird if this doesn't work. The marginalia annotators for recent files also work perfectly for me.

**Comment by oantolin** [comment]
@minad How does add a `embark-target-transformers` list sound? It would be a list of functions of type `(Category, String) -> Maybe (Category,String)`, they would be run in order until one returns something. I would make predefined transformers for `virtual-buffers` to dispatch to the right thing, and one for `line` that strips the prefix.

In principle the transformer for `virtual-buffers` could also benefit Marginalia, but since in Marginalia that seems to be the only case we'd want it so far, it might be best to not add the transformer concept to Marginalia. More generally, Marginalia feels pretty much finished to me.

**Comment by minad** [comment]
I agree, Marginalia is mostly finished! But I wonder why you would need the target transformer? Are there more use cases for this, except line and virtual buffers? I wouldn't commit to quickly on something here in order to not add more complexity.

**Comment by oantolin** [comment]
I was only thinking of it for `virtual-buffer` and `line`. I thought maybe two cases was enough to warrant having the general mechanism, but maybe it's premature.

I do want Embark, out of the box, to do the `virtual-buffer` dispatch and to remove the prefix from lines. One thing I used to do with my old `consult-line` equivalent, which is a little annoying with `consult-line` is duplicate a faraway line from the same buffer I'm in, by using the `embark-insert` action. You can do that, of course, but currently you have to manually delete the line number prefix.

**Comment by oantolin** [comment]
I could special-case `virtual-buffer` and `line` for now, and if more cases come up, generalize the mechanism.

**Comment by minad** [comment]
> I do want Embark, out of the box, to do the virtual-buffer dispatch and to remove the prefix from lines. One thing I used to do with my old consult-line equivalent, which is a little annoying with consult-line is duplicate a faraway line from the same buffer I'm in, by using the embark-insert action. You can do that, of course, but currently you have to manually delete the line number prefix.

Okay, then it would already be okay to add a category alist with the transformers. Better than special casing with some conditionals I think.

**Comment by oantolin** [comment]
Well, the special-casing would be pretty unobstrusive. I'd re-add the `embark--target` function that I inlined when it became simply `(run-hook-with-args-until-success 'embark-target-finders)` and do the transformation in it.

**Comment by oantolin** [comment]
I'm an idiot: I shouldn't strip the line number prefix for `line` targets, because `consult-line` needs to know to which of several identical lines you are trying to jump. 😞 

I'll keep the `virtual-buffer` transformation, and instead create special `embark-{save,insert}-line` actions, and an `embark-save-line-number` action. An `embark-insert-line-number` action wouldn't be very useful, would it? To insert the number of line into the same buffer you found the line in?

**Comment by minad** [comment]
Sounds good. But for me the unicode prefix artifact is not that bad, I just delete it manually. It is also a bit of a statistics counter - by the number of bug reports regarding this artifact we can count the number of users of this particular command 😁

**Comment by oantolin** [comment]
> Sounds good. But for me the unicode prefix artifact is not that bad, I just delete it manually. It is also a bit of a statistics counter - by the number of bug reports regarding this artifact we can count the number of users of this particular command 😁

Well, I changed it. I hope you don't *miss* deleting the prefix manually. 😛

**Comment by junyi-hou** [comment]
> I can't reproduce this @junyi-hou. I activated recentf, opened and closed a few files, and I do get file actions for the recently closed files in consult-buffer.

sorry for the late reply. I can confirm that this is causing by my user config and not embark.

**Comment by oantolin** [comment]
That's a relief @junyi-hou, thanks for letting me know.
