### ISSUE TITLE
embark-live-occur-after-input fails when prompt has default value

### ISSUE THREAD

**Issue by protesilaos** [oantolin/embark#87]
Hello Omar! I have noticed that commands which set a default value will activate the live occur buffer even if no input is provided.

This happens, for example, with `describe-variable` (`C-h v`).  When you call it while point is over a variable, the live occur buffer pops up.  Otherwise it does not (the desired state of affairs).  The difference between the two is that the former has a default value.

All `describe-*` functions I tried exhibit this behaviour.  Same for `switch-to-buffer`.

**Comment by oantolin** [comment]
Hi Prot! This is triggered by `(setq minibuffer-eldef-shorten-default t)`. I removed it from my configuration because I find this issue you are reporting more annoying than having `(default ...)` instead of `[...]`. 😢 

But that's just a workaround. I do want to fix this.

**Comment by oantolin** [comment]
Mmh. Apparently `(setq minibuffer-eldef-shorten-default t)` causes the shortened default prompt to be inserted into the minibuffer. So the after change hook I'm using thinks you typed ` [variable-name]:` in the minibuffer, when using `C-h v`, for example.

**Comment by oantolin** [comment]
This seems a little tricky. For now I recommend not using `(setq minibuffer-eldef-shorten-default t)`.

**Comment by oantolin** [comment]
OK, here's a way you can keep `(setq minibuffer-eldef-shorten-default t)`. Also add this to your configuration:

```elisp
(defun stealthily (fn &rest args)
  (let ((inhibit-modification-hooks t))
    (apply fn args)))
    
(advice-add 'minibuf-eldef-setup-minibuffer :around #'stealthily)
```

I'm going to report a bug, asking for `minibuf-eldef-setup-minibuffer ` to include `(let ((inhibit-modification-hooks t)) ...)` because that function really shouldn't count as modifying the minibuffer.

Is it OK if I close this issue? I really don't think Embark needs to do anything differently. Really `minibuf-eldef-setup-minibuffer` should inhibit modification hooks, and in the meantime you and I can just use this advice (or give up on the shortened prompts...).

**Comment by oantolin** [comment]
Here's the [bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45686).

**Comment by protesilaos** [comment]
> Is it OK if I close this issue? I really don't think Embark needs to do anything differently. 

Fine by me.

**Comment by oantolin** [comment]
I'm pretty happy with advising `minibuf-eldef-setup-minibuffer` to inhibit modification hooks. I really do like the square brackets better than the word "default" which takes up so much space.

**Comment by protesilaos** [comment]
I thought I would wait a bit to see how the bug report goes, but I will follow your lead.  I also prefer the square brackets.
