### ISSUE TITLE
Consider don't rename embark-occur

### ISSUE THREAD

**Issue by BooAA** [oantolin/embark#94]
Hi, thanks for the tremendous contribution for Emacs completion system.

For 174cf21, `embark-occur` is a good name IMHO. As a heavy occur user, I think the "sence of occur" is that you have buffers side by side, one is your original buffer, the other one displaying the "occurrence" of the search pattern, and you go through each of them in the original buffer just by moving in the *occur* buffer. Although `helm-occur` and `ivy-occur` or some other packages may have different UI design and may support different operation, the spirit is similar and most Emacs users are used to this kind of naming convention as far as I know. So please consider keep the `embark-occur` name.

**Comment by minad** [comment]
Since I've been one of the people who was initially confused about the occur name, I take the freedom to write down some thoughts/arguments why collect is good. Note that I do not speak for @oantolin.

* embark-collect seems more general than the other occurs.
* From what I understood, helm-occur/ivy-occur already don't agree regarding their functionality. Why are they sharing a name?
* There is a name clash with Emacs builtin occur and multi-occur.
* The candidates in Embark are retrieved by collectors.
* Collect makes more sense, since it shows the collected candidates, not occurrences of a search pattern.
* There is not a big downside in "renaming" things, since Embark is new and different.

Over time I got more accustomed to calling the buffers occur buffers, but now I am still more happy with the rename. In the end the names do not matter much since you have them bound to the L=live key and S=snapshot key in the Embark keymap.

**Comment by oantolin** [comment]
I agree with all of @minad's points. I think the most convincing argument for me is that out of `occur`, `multi-occur`, `helm-occur` and `ivy-occur` only `ivy-occur` is similar to `embark-occur`, the others only collect matches for regexps, not general completion candidates. I think we should suggest instead that `ivy-occur` be renamed. 😛 I think the naming convention you say Emcas users are used to is probably that occur = matches of regexps, and that both `ivy-occur` and `embark-occur` were actually violating the Emacs naming conventions.

Plus, collect does also just make more sense in the general context: you collect the completions. On the other hand occur makes perfect sense for regexp matches: you get the list of lines where the pattern occurs!

I'm not going to go back to `embark-occur`, but this is Emacs! You don't need me to rename it! You are welcome to define an alias in your configuration or to bind `embark-collect-snapshot` to `O` in `embark-general-map`, whatever you want.
