### ISSUE TITLE
Anonymous commands

### ISSUE THREAD

**Issue by astoff** [oantolin/embark#99]
It looks like interactive lambdas are not listed in the help popup. I don't like to invent names for things which are used at a single place, and so I would like to set, for instance

``` elisp
(define-key embark-symbol-map
  "b" (lambda (x) "Bind command to key"
        (interactive "C")
        (define-key
          (if (y-or-n-p "Bind globally? ")
              (current-global-map)
            (current-local-map))
          (read-key-sequence (format "Bind ‘%s’ to: " x) nil t)
          x)))
```

This works, but doesn't show in the `C-h` prompt. I'd expect to see an entry
```
b → Bind command to key
```

PS: It seems a bit magical how the "subject thing" is bound to an argument of the embark action. I think this deserves a word in the docs.

**Comment by oantolin** [comment]
About the lambdas: that's a nice enhancement, I'll try to make it.

> It seems a bit magical how the "subject thing" is bound to an argument of the embark action. I think this deserves a word in the docs.

The readme says: "you can use any command that reads from the minibuffer as an action and the target of the action will be inserted at the first minibuffer prompt". What else should I add?

**Comment by minad** [comment]
>> It seems a bit magical how the "subject thing" is bound to an argument of the embark action. I think this deserves a word in the docs.

> The readme says: "you can use any command that reads from the minibuffer as an action and the target of the action will be inserted at the first minibuffer prompt". What else should I add?

It seems the misunderstanding here is that it is not bound to an argument, but magically injected as input to completing-read. Maybe you could point that out in the readme, that the embark actions are called interactively and as such the arguments are inserted by the interactive prologue.

**Comment by astoff** [comment]
> The readme says: "you can use any command that reads from the minibuffer as an action and the target of the action will be inserted at the first minibuffer prompt". What else should I add?

No, that looks good. I guess I missed it because it's a bit different from what I expected.

In fact, binding `global-set-key` to an action basically works (only the prompt for a key behaves a bit weird). This is kinda magical!

**Comment by oantolin** [comment]
> It seems the misunderstanding here is that the target is not bound to an argument, but magically injected as input to completing-read.

It is injected at the first use of completing-read. Whether you bind that to an argument or not is up to you, of course. I prefer always binding to an argument if possible, so I would rewrite this:

```elisp
(defun my-action ()
  (interactive)
  (let ((target (completing-read "Arg 1: " some-list-of-candidates)))
    ...))
```

as this:


```elisp
(defun my-action (target)
  (interactive
    (list (completing-read "Arg 1: " some-list-of-candidates)))
  ...)
```

> Maybe you could point that out in the readme, that the embark actions are called interactively and as such the arguments are inserted by the interactive prologue?

I thought I did! And that that's what the sentence I quoted means! But I should definitely be more explicit.

**Comment by oantolin** [comment]
You can also access the target as `(cdr (embark--target))` (the `car` is the "type"), but I'm not sure if I want to make that an officially supported way of getting the target. I much prefer people using as actions normal commands that prompt the user.

**Comment by oantolin** [comment]
> > The readme says: "you can use any command that reads from the minibuffer as an action and the target of the action will be inserted at the first minibuffer prompt". What else should I add?

> No, that looks good. I guess I missed it because it's a bit different from what I expected.

It is weird! But I couldn't figure out any other way of doing things. I wanted to use, for example, `rename-file` as an action. The target should be the first argument, and you shouldn't be prompted for it *but* you should be prompted for the new file name. Emacs has a `call-interactively`, but I needed a `call-interactively-except-don't-prompt-for-the-first-argument-and-use-this-value-instead`. My solution was to inject the target in a minibuffer setup hook.
 
> In fact, binding `global-set-key` to an action basically works (only the prompt for a key behaves a bit weird). This is kinda magical!

😄

**Comment by oantolin** [comment]
> only the prompt for a key behaves a bit weird

You mean that the cursor jumps to a weird spot? Blame @minad for that. He convinced me to run all actions selecting the window that was selected prior to opening the minibuffer. 😄

**Comment by oantolin** [comment]
> In fact, binding `global-set-key` to an action basically works

Also, if you don't think you'll want `global-set-key` as an action often, and you don't want it cluttering up the list of actions you could *not* bind it, and instead use `M-x global-set-key` as the action when you want it. The Embark keymaps are just for convenience, you actually don't need them at all to run actions. You can use the normal key bindings for the actions or `M-x`.

**Comment by minad** [comment]
Uh what did I do to the poor cursor? 😆

**Comment by oantolin** [comment]
How much does the cursor moving to the previous window bother you @astoff?

I've been thinking that while running actions in the context of the previous *buffer* is a great idea, selecting the previous *window* is overkill most of the time. Maybe I should always use the previous buffer but make selecting the window optional. A `uses-window` property on the function symbol maybe. What do you think @minad? You requested selecting the window in the first place.

**Comment by minad** [comment]
Oh I wouldn't want per-function properties, this is like these evil-jump properties! I think moving to the last window is the correct behavior since this is the context where the actions should run. In my case, the recenter was the problem if I recall correctly. When does the cursor jump? I hope there is a better fix than introducing some special casing.

**Comment by oantolin** [comment]
I'm not sure about the cursor jump with the completing-read, I'll check later when I'm at my computer. 

The issue I'm taking about (which probably is the same one you mention, but I don't promise it is), is the following. Say you run M-x, then type a bit and realize you want a key binding for some command in the candidate list. You can select the command, run embark-act and use `M-x global-set-key` as the action. It works, it prompts you for a key sequence and does the binding. But normally, if you run `global-set-key` directly, while you are prompted for the key sequence the cursor stays in the minibuffer. If you run it as an action, the cursor jumps to the target window. It still works, the key sequence you type gets correctly used by global-set-key and does not affect the target window, but it does feel a little weird. And this happens because Embark selects that target window when running any action.

It doesn't bother me, I think so far running actions in that window has been better, but a few cases are a little funny, visually. For example, say you run consult-line, then embark-collect-snapshot. Say you close the window with the buffer you ran consult-line in and then want to save one of the result lines from the collect buffer to the kill ring. You can do that of course with `embark-act w`, but perhaps surprisingly, this opens a window showing the searched buffer again!

**Comment by minad** [comment]
If I run `M-x global-set-key`, the cursor also jumps to the original window. I don't see how Embark has anything to do with this. This is the fault of `global-set-key`, or more specifically of `read-key-sequence`, which shows a prompt in the minibuffer but does not move the cursor to the minibuffer. I tried this on emacs -Q without having loaded any additional packages.

For the second behavior you described with consult-line and embark-collect-snapshot, there I see why always selecting the window is overkill for certain commands. Similar to what you suggest, one could go with some kind of whitelist which only selects the buffer for benign commands, which do not require current buffer=window buffer. Or use a list of commands which require the window switching, but this is more problematic, I rather have the weird window opening behavior instead of errors. I would prefer a list in any case over properties. We are already doing that consistently I think, since having all the commands in one list is much better for introspection.

Another more general solution could be the following:

1. Check if the original window is visible
2. If yes, just select it, everything is alright, run action command
3. If not, save window configuration, select the window, run action command, restore window config afterwards

**Comment by oantolin** [comment]
> If I run `M-x global-set-key`, the cursor also jumps to the original window. I don't see how Embark has anything to do with this. This is the fault of `global-set-key`, or more specifically of `read-key-sequence`, which shows a prompt in the minibuffer but does not move the cursor to the minibuffer. I tried this on emacs -Q without having loaded any additional packages.

You're right! I completely misremembered what happens normally! That's what I get for typing on my phone instead of Emacs where I can test. Forget what I said. This also means I was probably wrong about what @astoff meant was a bit weird when he said:

> In fact, binding global-set-key to an action basically works (only the prompt for a key behaves a bit weird).

What did you mean @astoff?

> For the second behavior you described with consult-line and embark-collect-snapshot, there I see why always selecting the window is overkill for certain commands. Similar to what you suggest, one could go with some kind of whitelist which only selects the buffer for benign commands, which do not require current buffer=window buffer. Or use a list of commands which require the window switching

I'm starting to think this isn't really worth the trouble.

> but this is more problematic, I rather have the weird window opening behavior instead of errors.

Agreed!

By the way, the window selecting benefits some commands that don't *need* it, too, like `embark-insert`. Strictly speaking it can work with just the buffer, but selecting the window makes it obvious that something was inserted.

> I would prefer a list in any case over properties. We are already doing that consistently I think, since having all the commands in one list is much better for introspection.

Agreed.

> Another more general solution could be the following: [...]
> But 3. would obviously mess up actions which manipulate the window configuration 😆

Lets hold off on doing anything until we see if the window-selecting really bothers anyone. It doesn't really bother me.

**Comment by astoff** [comment]
> This also means I was probably wrong about what @astoff meant was a bit weird when he said:

You are absolutely right about that, sorry for not being more specific earlier. :-)

What happens to me is that I type, say, `C-1` (and that's not a prefix key) after invoking `global-set-key` via Embark, but the `read-key-sequence` prompt keeps showing in the echo area.  Then I type some other random key, say an arrow key, and I briefly see `C-1 <down>` in the echo area. Strangely enough, though, the command I originally acted upon is bound to `C-1` after all of this (and the `<down>`d motion happens as well).

**Comment by oantolin** [comment]
@astoff You inspired me to add `{global,local}-set-key` as actions for the `command` category. 846cfbd7212ba3a3a47a059ba35400d534968815

**Comment by astoff** [comment]
Nice! But does that mean I need to come up with another example of useful anonymous command? :stuck_out_tongue:

The glitch I mentioned in my previous comment still happens to me, even on emacs -Q (version 27.1). But it doesn't seem to affect the functionality.

> You can also access the target as `(cdr (embark--target))` (the `car` is the "type"), but I'm not sure if I want to make that an officially supported way of getting the target. I much prefer people using as actions normal commands that prompt the user.

This is really debatable, but maybe `embark--target` should be documented but not public in the "single dashed" sense. If a compelling need arises, you will probably want to provide two separate little functions to access the car and cdr anyway.

**Comment by minad** [comment]
I would really keep `embark--target` private! If possible all actions should just be normal commands and I took some care before to convert Embark-specific actions to plain commands. The function `embark--target` should only be a last resort for special cases and should stay private not to encourage its use.

**Comment by oantolin** [comment]
> The glitch I mentioned in my previous comment still happens to me, even on emacs -Q (version 27.1).

I see it here too. It's pretty weird.

> But does that mean I need to come up with another example of useful anonymous command?

No. 😄 So for `C-h` you'd want the anonymous command's docstring to be accepted?

**Comment by astoff** [comment]
> So for `C-h` you'd want the anonymous command's docstring to be accepted?

Well, yes... I guess this discussion shows that this is a pretty minor feature, but it would be nice (and correct). The `documentation` function fetches the docstring.

**Comment by oantolin** [comment]
Selecting a command by typing its docstring feels more weird than correct to me, but I guess in the absence of a name there's not much else you could type to select the command.

**Comment by iSeeU816** [comment]
Hello,

The last comment by @oantolin  got my attention, sorry if this comment turned
out to be an off-topic.

[emacs-key-assist](https://github.com/Boruch-Baum/emacs-key-assist)
package is very useful to search for a command by its docstring or
keybinding.

Here is the list of candidates when running `M-x key-assist consult-`:

``` text
C-,	consult-outline (not documented)
C-.	consult-imenu (not documented)
s-r	consult-recent-file (not documented)
s-y	consult-yank (not documented)
C-z b	consult-buffer (not documented)
M-g L	Read line number and jump to the line with preview.
M-g M	consult-global-mark (not documented)
M-g l	Search for a matching line and jump to the line beginning.
M-g m	consult-mark (not documented)
M-s C	consult-complex-command (not documented)
M-s R	Search for REGEXP with rg in DIR.
M-s c	Run a command from the MODES.
```

I use it when I don't remember a command's name but what it does.

I'm not sure why it doesn't show all Consult commands like when calling
`M-x ^consult-`.

I will take this chance and say thank you to both of @oantolin  and @minad  for the
packages you develop.

**Comment by astoff** [comment]
> I would really keep `embark--target` private!

FWIW, `embark--target` already creeped into [Protesilaos's config](https://protesilaos.com/dotemacs/#h:98d3abcc-f34e-4029-aabc-740f0b6421f8). But of course he is tinkering.

Actually, I'm not even sure what private means in Elisp, but thankfully it doesn't mean the same thing as in Java. Packages hack into each other all the time. This allows awesome stuff to be done and somehow works fine.

By the way, @minad, there some "private" things in consult I would rather make public. For instance, I would need to use `consult--grep` directly to port my Ivy-based dictionary command (which greps [these](https://en.wiktionary.org/wiki/User:Matthias_Buchmeier/download) Wiktionary dumps). And while it's neither your fault that the `completing-read` API is really awkward nor your duty to fix it, `consult--read` is pretty handy if you want to put together some utility command in your config (I would use it if I wanted to port my hacks to access RefTeX with a sane Ivy interface).

**Comment by oantolin** [comment]
> Actually, I'm not even sure what private means in Elisp

I take the double dash to mean: "Yes, go ahead use it! But don't come complaining to me if an update removes this function or changes its meaning."

**Comment by minad** [comment]
@astoff Yes, please go forward and use the "private" functions but don't complain if they don't change ;) I try to not break the double dash functions unnecessarily, but I also don't want to give strong stability guarantees on them, since this will restrict me too much. I considered making consult--read public, but right now it is better as is. Consult is meant as end-user package and not so much as a package on which you can build other packages. The set of commands is what the package provides, not the internal API. But for your init.el functions it is no problem to use consult--read as is.

**Comment by oantolin** [comment]
I finally got around to implementing this @astoff. Please test.

**Comment by astoff** [comment]
Works for me, thanks!
